$ !
$ ! XPG4 data files -- locale source, iconv table source and charmap files
$ !
$ ! fetch all the charmap files and move them to the locale
$ ! directory on the result disk [SYS$I18N.LOCALES.SYSTEM]
$ ! 
$ SRCUPDATE      BIG5.CMAP		! charmap file
$ CPYRESLOC SRC$:BIG5.CMAP
$ SRCUPDATE      DECHANYU.CMAP		! charmap file
$ CPYRESLOC SRC$:DECHANYU.CMAP
$ SRCUPDATE      DECHANZI.CMAP		! charmap file
$ CPYRESLOC SRC$:DECHANZI.CMAP
$ SRCUPDATE      DECKANJI.CMAP		! charmap file
$ CPYRESLOC SRC$:DECKANJI.CMAP
$ SRCUPDATE      DECKOREAN.CMAP		! charmap file
$ CPYRESLOC SRC$:DECKOREAN.CMAP
$ SRCUPDATE      EUCJP.CMAP		! charmap file
$ CPYRESLOC SRC$:EUCJP.CMAP
$ SRCUPDATE      EUCTW.CMAP		! charmap file
$ CPYRESLOC SRC$:EUCTW.CMAP
$ SRCUPDATE      ISO8859-1.CMAP		! charmap file
$ CPYRESLOC SRC$:ISO8859-1.CMAP
$ SRCUPDATE      ISO8859-2.CMAP		! charmap file
$ CPYRESLOC SRC$:ISO8859-2.CMAP
$ SRCUPDATE      ISO8859-5.CMAP		! charmap file
$ CPYRESLOC SRC$:ISO8859-5.CMAP
$ SRCUPDATE      ISO8859-7.CMAP		! charmap file
$ CPYRESLOC SRC$:ISO8859-7.CMAP
$ SRCUPDATE      ISO8859-8.CMAP		! charmap file
$ CPYRESLOC SRC$:ISO8859-8.CMAP
$ SRCUPDATE      ISO8859-9.CMAP		! charmap file
$ CPYRESLOC SRC$:ISO8859-9.CMAP
$ SRCUPDATE      SDECKANJI.CMAP		! charmap file
$ CPYRESLOC SRC$:SDECKANJI.CMAP
$ SRCUPDATE      SJIS.CMAP		! charmap file
$ CPYRESLOC SRC$:SJIS.CMAP
$!
$! Fetch the locale sources
$!
$!  1. 8 bit locales
$!     
$ SRCUPDATE CS_CZ_ISO8859-2.LSRC ! Czech
$ SRCUPDATE DA_DK_ISO8859-1.LSRC ! Danish
$ SRCUPDATE DE_CH_ISO8859-1.LSRC ! Swiss German
$ SRCUPDATE DE_DE_ISO8859-1.LSRC ! German
$ SRCUPDATE EL_GR_ISO8859-7.LSRC ! Greek
$ SRCUPDATE EN_GB_ISO8859-1.LSRC ! Great Britain
$ SRCUPDATE EN_US_ISO8859-1.LSRC ! U.S.A
$ SRCUPDATE ES_ES_ISO8859-1.LSRC ! Spanish
$ SRCUPDATE FI_FI_ISO8859-1.LSRC ! Finnish
$ SRCUPDATE FR_BE_ISO8859-1.LSRC ! Belgian French
$ SRCUPDATE FR_CA_ISO8859-1.LSRC ! Canadian French
$ SRCUPDATE FR_CH_ISO8859-1.LSRC ! Swiss French
$ SRCUPDATE FR_FR_ISO8859-1.LSRC ! French
$ SRCUPDATE HU_HU_ISO8859-2.LSRC ! Hungarian
$ SRCUPDATE IS_IS_ISO8859-1.LSRC ! Icelandic
$ SRCUPDATE IT_IT_ISO8859-1.LSRC ! Italian
$ SRCUPDATE IW_IL_ISO8859-8.LSRC ! Hebrew
$ SRCUPDATE NL_BE_ISO8859-1.LSRC ! Belgian Dutch
$ SRCUPDATE NL_NL_ISO8859-1.LSRC ! Dutch
$ SRCUPDATE NO_NO_ISO8859-1.LSRC ! Norwegian
$ SRCUPDATE PL_PL_ISO8859-2.LSRC ! Polish
$ SRCUPDATE PT_PT_ISO8859-1.LSRC ! Portuguese
$ SRCUPDATE RU_RU_ISO8859-5.LSRC ! Russian
$ SRCUPDATE SK_SK_ISO8859-2.LSRC ! Slovak
$ SRCUPDATE SV_SE_ISO8859-1.LSRC ! Swedish
$ SRCUPDATE TR_TR_ISO8859-9.LSRC ! Turkish
$ 
$! 2. Multi byte locales
$    
$ SRCUPDATE JA_JP_DECKANJI.LSRC		! Japanese
$ SRCUPDATE JA_JP_EUCJP.LSRC		! Japanese
$ SRCUPDATE JA_JP_SDECKANJI.LSRC	! Japanese
$ SRCUPDATE JA_JP_SJIS.LSRC		! Japanese
$    
$ SRCUPDATE ZH_CN_DECHANZI.LSRC		! PRC
$ SRCUPDATE ZH_CN_DECHANZI_PINYIN.LSRC	! PRC
$ SRCUPDATE ZH_CN_DECHANZI_RADICAL.LSRC	! PRC
$ SRCUPDATE ZH_CN_DECHANZI_STROKE.LSRC	! PRC
$    
$ SRCUPDATE ZH_TW_DECHANYU.LSRC		! Taiwanese
$ SRCUPDATE ZH_TW_DECHANYU_CHUYIN.LSRC	! Taiwanese
$ SRCUPDATE ZH_TW_DECHANYU_RADICAL.LSRC	! Taiwanese
$ SRCUPDATE ZH_TW_DECHANYU_STROKE.LSRC	! Taiwanese
$    
$ SRCUPDATE ZH_TW_EUCTW.LSRC		! Taiwanese
$ SRCUPDATE ZH_TW_EUCTW_CHUYIN.LSRC	! Taiwanese
$ SRCUPDATE ZH_TW_EUCTW_RADICAL.LSRC	! Taiwanese
$ SRCUPDATE ZH_TW_EUCTW_STROKE.LSRC	! Taiwanese
$    
$ SRCUPDATE KO_KR_DECKOREAN.LSRC	! korean
$    
$ SRCUPDATE ZH_TW_BIG5.LSRC		! Taiwanese
$ SRCUPDATE ZH_TW_BIG5_CHUYIN.LSRC	! Taiwanese
$ SRCUPDATE ZH_TW_BIG5_RADICAL.LSRC	! Taiwanese
$ SRCUPDATE ZH_TW_BIG5_STROKE.LSRC	! Taiwanese
$    
$ SRCUPDATE ZH_HK_BIG5.LSRC		! Hong-Kong
$ SRCUPDATE ZH_HK_DECHANYU.LSRC         ! Hong-Kong
$ SRCUPDATE ZH_HK_DECHANZI.LSRC         ! Hong-Kong
$ SRCUPDATE ZH_HK_EUCTW.LSRC		! Hong-Kong
$
$ ! Get the converter source files
$ 
$ SRCUPDATE BIG5_DECHANYU.ISRC
$ SRCUPDATE BIG5_EUCTW.ISRC
$ SRCUPDATE DECHANYU_BIG5.ISRC
$ SRCUPDATE DECHANYU_MITELX.ISRC
$ SRCUPDATE DECKANJI_EUCJP.ISRC
$ SRCUPDATE DECKANJI_SDECKANJI.ISRC
$ SRCUPDATE DECKANJI_SJIS.ISRC
$ SRCUPDATE DOOSAN_DECKOREAN.ISRC
$ SRCUPDATE EUCJP_SDECKANJI.ISRC
$ SRCUPDATE EUCJP_DECKANJI.ISRC
$ SRCUPDATE EUCJP_SJIS.ISRC
$ SRCUPDATE EUCTW_BIG5.ISRC
$ SRCUPDATE EUCTW_MITELX.ISRC
$ SRCUPDATE MITELX_DECHANYU.ISRC
$ SRCUPDATE MITELX_EUCTW.ISRC
$ SRCUPDATE SDECKANJI_DECKANJI.ISRC
$ SRCUPDATE SDECKANJI_EUCJP.ISRC
$ SRCUPDATE SDECKANJI_SJIS.ISRC
$ SRCUPDATE SJIS_DECKANJI.ISRC
$ SRCUPDATE SJIS_EUCJP.ISRC
$ SRCUPDATE SJIS_SDECKANJI.ISRC
$!
$! Parts for the I18N datafile kit
$!
$ SRCUPDATE LOCALE_KITINSTAL.COM
$ SRCUPDATE LOCALE_MAKEKIT.COM
$ SRCUPDATE LOCALE_IVP.COM
