.\" @(#)rotary.1 1.2 91/04/15
.TH rotary 1-IUCS
.SH NAME
rotary \- display current dialin rotary usage
.SH SYNTAX
.B rotary
.SH DESCRIPTION
.B Rotary
displays each device on the dialin rotary in order with the name of any
user currently using the line.
A "-" is displayed if the line is currently unused.
.SH FILES
/usr/local/etc/dialins
.br
/nfs/*/dev/ttyd?
.SH "SEE ALSO"
who(1), finger(1)
.SH AUTHOR
Stephen Kinzler, kinzler@cs.indiana.edu, July 1990
