$	OPEN/READ INPT REGISTRY.RPT
$	OPEN/WRITE OUTP REGISTRY.TXT     
$ READ_LOOP:
$	READ/END=ENDE INPT REC
$	IF F$ELEMENT(1,"|",REC)  .EQS. "" THEN GOTO READ_LOOP
$	DN4A = F$ELEMENT(1,"|",REC)  
$	DN4N = F$ELEMENT(2,"|",REC)
$	DN5N = F$ELEMENT(3,"|",REC)
$	DEV = F$ELEMENT(4,"|",REC)
$	WRITE OUTP F$FAO("!10<!AS!> !10<!AS!> !20<!AS!> !20<!AS!>",DN4A,DN4N,DN5N,DEV)
$	GOTO READ_LOOP
$ ENDE:
$	CLOSE INPT
$	CLOSE OUTP
$	PURGE REGISTRY.TXT
$	EXIT
