$ if AXP
$ then	link/exe=xsokoban.exe -
  MAIN,DISPLAY,PLAY,RESOURCES,SAVE,SCORE,SCOREDISP,SCREEN,VMS_STRDUP,VMS_UNLINK,AXP.OPT/OPT
$ else	link/exe=xsokoban.exe -
 MAIN,DISPLAY,PLAY,RESOURCES,SAVE,SCORE,SCOREDISP,SCREEN,VMS_STRDUP,VMS_UNLINK,VMS.OPT/OPT
$ endif
