void error(void);
void jumpout(void);
void scanargs(void);
void initialize(void);
void openinput(void);
boolean inputln(textfile f);
void printid(namepointer p);
void newxref(namepointer p);
void newmodxref(namepointer p);
namepointer idlookup(eightbits t);
namepointer modlookup(sixteenbits l);
namepointer prefixlookup(sixteenbits l);
boolean linesdontmatch(void);
void primethechangebuffer(void);
void checkchange(void);
void resetinput(void);
void getline(void);
eightbits controlcode(ASCIIcode c);
void skiplimbo(void);
eightbits skipTeX(void);
eightbits skipcomment(eightbits bal);
eightbits getnext(void);
void Pascalxref(void);
void outerxref(void);
void modcheck(namepointer p);
void flushbuffer(eightbits b,boolean percent);
void finishline(void);
void breakout(void);
void outmod(integer m);
void outname(namepointer p);
void copylimbo(void);
eightbits copyTeX(void);
eightbits copycomment(eightbits bal);
void red(sixteenbits j,eightbits k,eightbits c,integer d);
void sq(sixteenbits j,eightbits k,eightbits c,integer d);
void fivecases(void);
void alphacases(void);
textpointer translate(void);
void appcomment(void);
void appoctal(void);
void apphex(void);
void easycases(void);
void subcases(namepointer p);
void Pascalparse(void);
textpointer Pascaltranslate(void);
void outerparse(void);
void pushlevel(textpointer p);
eightbits getoutput(void);
void outputPascal(void);
void makeoutput(void);
void finishPascal(void);
void footnote(sixteenbits flag);
void unbucket(eightbits d);
void modprint(namepointer p);
void PhaseI(void);
void PhaseII(void);
