/*  Taken from OpenVMS AXP FT4 SYS$LIBRARY:LIB.MLB  */
/*
**	.MACRO	$FCHDEF,$GBL
**	$DEFINI	FCH,$GBL
*/
#define	FCH$M_VCC_STATE	0x700
#define	FCH$M_ALM_STATE	0x1C0000
#define	FCH$M_WASCONTIG	0x1
#define	FCH$M_NOBACKUP	0x2
#define	FCH$M_WRITEBACK	0x4
#define	FCH$M_READCHECK	0x8
#define	FCH$M_WRITCHECK	0x10
#define	FCH$M_CONTIGB	0x20
#define	FCH$M_LOCKED	0x40
#define	FCH$M_CONTIG	0x80
#define	FCH$M_BADACL	0x800
#define	FCH$M_SPOOL	0x1000
#define	FCH$M_DIRECTORY	0x2000
#define	FCH$M_BADBLOCK	0x4000
#define	FCH$M_MARKDEL	0x8000
#define	FCH$M_NOCHARGE	0x10000
#define	FCH$M_ERASE	0x20000
#define	FCH$M_ALM_AIP	0x40000
#define	FCH$M_ALM_ARCHIVED	0x80000
#define	FCH$M_ALM_DELETED	0x100000
#define	FCH$S_FCHDEF	4
#define	FCH$S_VCC_STATE	3
#define	FCH$V_VCC_STATE	8
#define	FCH$S_ALM_STATE	3
#define	FCH$V_ALM_STATE	18
#define	FCH$V_WASCONTIG	0
#define	FCH$V_NOBACKUP	1
#define	FCH$V_WRITEBACK	2
#define	FCH$V_READCHECK	3
#define	FCH$V_WRITCHECK	4
#define	FCH$V_CONTIGB	5
#define	FCH$V_LOCKED	6
#define	FCH$V_CONTIG	7
#define	FCH$V_BADACL	11
#define	FCH$V_SPOOL	12
#define	FCH$V_DIRECTORY	13
#define	FCH$V_BADBLOCK	14
#define	FCH$V_MARKDEL	15
#define	FCH$V_NOCHARGE	16
#define	FCH$V_ERASE	17
#define	FCH$V_ALM_AIP	18
#define	FCH$V_ALM_ARCHIVED	19
#define	FCH$V_ALM_DELETED	20
/*
**	$DEFEND	FCH,$GBL,DEF
**	.ENDM
*/
