/*
 *				SMGDEF.H
 *
 * Definitions created by C_DEFS at 14-OCT-1991 16:49:46.80
 */
#define SMG$K_TRM_NULL_CHAR	0
#define SMG$K_TRM_CTRLA	1
#define SMG$K_TRM_CTRLB	2
#define SMG$K_TRM_CTRLC	3
#define SMG$K_TRM_CTRLD	4
#define SMG$K_TRM_CTRLE	5
#define SMG$K_TRM_CTRLF	6
#define SMG$K_TRM_CTRLG	7
#define SMG$K_TRM_CTRLH	8
#define SMG$K_TRM_CTRLI	9
#define SMG$K_TRM_CTRLJ	10
#define SMG$K_TRM_CTRLK	11
#define SMG$K_TRM_CTRLL	12
#define SMG$K_TRM_CTRLM	13
#define SMG$K_TRM_CTRLN	14
#define SMG$K_TRM_CTRLO	15
#define SMG$K_TRM_CTRLP	16
#define SMG$K_TRM_CTRLQ	17
#define SMG$K_TRM_CTRLR	18
#define SMG$K_TRM_CTRLS	19
#define SMG$K_TRM_CTRLT	20
#define SMG$K_TRM_CTRLU	21
#define SMG$K_TRM_CTRLV	22
#define SMG$K_TRM_CTRLW	23
#define SMG$K_TRM_CTRLX	24
#define SMG$K_TRM_CTRLY	25
#define SMG$K_TRM_CTRLZ	26
#define SMG$K_TRM_ESCAPE	27
#define SMG$K_TRM_FS	28
#define SMG$K_TRM_GS	29
#define SMG$K_TRM_RS	30
#define SMG$K_TRM_US	31
#define SMG$K_TRM_SPACE	32
#define SMG$K_TRM_EXCLAMATION_POINT	33
#define SMG$K_TRM_DOUBLE_QUOTE	34
#define SMG$K_TRM_NUMBER_SIGN	35
#define SMG$K_TRM_DOLLAR_SIGN	36
#define SMG$K_TRM_PERCENT_SIGN	37
#define SMG$K_TRM_AMPERSAND	38
#define SMG$K_TRM_QUOTE	39
#define SMG$K_TRM_LEFT_PAREN	40
#define SMG$K_TRM_RIGHT_PAREN	41
#define SMG$K_TRM_ASTERISK	42
#define SMG$K_TRM_PLUS_SIGN	43
#define SMG$K_TRM_COMMA_CHAR	44
#define SMG$K_TRM_DASH	45
#define SMG$K_TRM_DOT	46
#define SMG$K_TRM_SLASH	47
#define SMG$K_TRM_ZERO	48
#define SMG$K_TRM_ONE	49
#define SMG$K_TRM_TWO	50
#define SMG$K_TRM_THREE	51
#define SMG$K_TRM_FOUR	52
#define SMG$K_TRM_FIVE	53
#define SMG$K_TRM_SIX	54
#define SMG$K_TRM_SEVEN	55
#define SMG$K_TRM_EIGHT	56
#define SMG$K_TRM_NINE	57
#define SMG$K_TRM_COLON	58
#define SMG$K_TRM_SEMICOLON	59
#define SMG$K_TRM_LESS_THAN	60
#define SMG$K_TRM_EQUAL	61
#define SMG$K_TRM_GREATER_THAN	62
#define SMG$K_TRM_QUESTION_MARK	63
#define SMG$K_TRM_AT_SIGN	64
#define SMG$K_TRM_UPPERCASE_A	65
#define SMG$K_TRM_UPPERCASE_B	66
#define SMG$K_TRM_UPPERCASE_C	67
#define SMG$K_TRM_UPPERCASE_D	68
#define SMG$K_TRM_UPPERCASE_E	69
#define SMG$K_TRM_UPPERCASE_F	70
#define SMG$K_TRM_UPPERCASE_G	71
#define SMG$K_TRM_UPPERCASE_H	72
#define SMG$K_TRM_UPPERCASE_I	73
#define SMG$K_TRM_UPPERCASE_J	74
#define SMG$K_TRM_UPPERCASE_K	75
#define SMG$K_TRM_UPPERCASE_L	76
#define SMG$K_TRM_UPPERCASE_M	77
#define SMG$K_TRM_UPPERCASE_N	78
#define SMG$K_TRM_UPPERCASE_O	79
#define SMG$K_TRM_UPPERCASE_P	80
#define SMG$K_TRM_UPPERCASE_Q	81
#define SMG$K_TRM_UPPERCASE_R	82
#define SMG$K_TRM_UPPERCASE_S	83
#define SMG$K_TRM_UPPERCASE_T	84
#define SMG$K_TRM_UPPERCASE_U	85
#define SMG$K_TRM_UPPERCASE_V	86
#define SMG$K_TRM_UPPERCASE_W	87
#define SMG$K_TRM_UPPERCASE_X	88
#define SMG$K_TRM_UPPERCASE_Y	89
#define SMG$K_TRM_UPPERCASE_Z	90
#define SMG$K_TRM_LEFT_BRACKET	91
#define SMG$K_TRM_BACKSLASH	92
#define SMG$K_TRM_RIGHT_BRACKET	93
#define SMG$K_TRM_CARET	94
#define SMG$K_TRM_UNDERLINE	95
#define SMG$K_TRM_GRAVE_ACCENT	96
#define SMG$K_TRM_LOWERCASE_A	97
#define SMG$K_TRM_LOWERCASE_B	98
#define SMG$K_TRM_LOWERCASE_C	99
#define SMG$K_TRM_LOWERCASE_D	100
#define SMG$K_TRM_LOWERCASE_E	101
#define SMG$K_TRM_LOWERCASE_F	102
#define SMG$K_TRM_LOWERCASE_G	103
#define SMG$K_TRM_LOWERCASE_H	104
#define SMG$K_TRM_LOWERCASE_I	105
#define SMG$K_TRM_LOWERCASE_J	106
#define SMG$K_TRM_LOWERCASE_K	107
#define SMG$K_TRM_LOWERCASE_L	108
#define SMG$K_TRM_LOWERCASE_M	109
#define SMG$K_TRM_LOWERCASE_N	110
#define SMG$K_TRM_LOWERCASE_O	111
#define SMG$K_TRM_LOWERCASE_P	112
#define SMG$K_TRM_LOWERCASE_Q	113
#define SMG$K_TRM_LOWERCASE_R	114
#define SMG$K_TRM_LOWERCASE_S	115
#define SMG$K_TRM_LOWERCASE_T	116
#define SMG$K_TRM_LOWERCASE_U	117
#define SMG$K_TRM_LOWERCASE_V	118
#define SMG$K_TRM_LOWERCASE_W	119
#define SMG$K_TRM_LOWERCASE_X	120
#define SMG$K_TRM_LOWERCASE_Y	121
#define SMG$K_TRM_LOWERCASE_Z	122
#define SMG$K_TRM_LEFT_BRACE	123
#define SMG$K_TRM_VERTICAL_LINE	124
#define SMG$K_TRM_RIGHT_BRACE	125
#define SMG$K_TRM_TILDE	126
#define SMG$K_TRM_DELETE	127
#define SMG$K_TRM_BS	8
#define SMG$K_TRM_HT	9
#define SMG$K_TRM_LF	10
#define SMG$K_TRM_VT	11
#define SMG$K_TRM_FF	12
#define SMG$K_TRM_CR	13
#define SMG$K_TRM_PF1	256
#define SMG$K_TRM_PF2	257
#define SMG$K_TRM_PF3	258
#define SMG$K_TRM_PF4	259
#define SMG$K_TRM_KP0	260
#define SMG$K_TRM_KP1	261
#define SMG$K_TRM_KP2	262
#define SMG$K_TRM_KP3	263
#define SMG$K_TRM_KP4	264
#define SMG$K_TRM_KP5	265
#define SMG$K_TRM_KP6	266
#define SMG$K_TRM_KP7	267
#define SMG$K_TRM_KP8	268
#define SMG$K_TRM_KP9	269
#define SMG$K_TRM_ENTER	270
#define SMG$K_TRM_MINUS	271
#define SMG$K_TRM_COMMA	272
#define SMG$K_TRM_PERIOD	273
#define SMG$K_TRM_UP	274
#define SMG$K_TRM_DOWN	275
#define SMG$K_TRM_LEFT	276
#define SMG$K_TRM_RIGHT	277
#define SMG$K_TRM_F1	281
#define SMG$K_TRM_F2	282
#define SMG$K_TRM_F3	283
#define SMG$K_TRM_F4	284
#define SMG$K_TRM_F5	285
#define SMG$K_TRM_F6	286
#define SMG$K_TRM_F7	287
#define SMG$K_TRM_F8	288
#define SMG$K_TRM_F9	289
#define SMG$K_TRM_F10	290
#define SMG$K_TRM_F11	291
#define SMG$K_TRM_F12	292
#define SMG$K_TRM_F13	293
#define SMG$K_TRM_F14	294
#define SMG$K_TRM_F15	295
#define SMG$K_TRM_F16	296
#define SMG$K_TRM_F17	297
#define SMG$K_TRM_F18	298
#define SMG$K_TRM_F19	299
#define SMG$K_TRM_F20	300
#define SMG$K_TRM_HELP	295
#define SMG$K_TRM_DO	296
#define SMG$K_TRM_E1	311
#define SMG$K_TRM_E2	312
#define SMG$K_TRM_E3	313
#define SMG$K_TRM_E4	314
#define SMG$K_TRM_E5	315
#define SMG$K_TRM_E6	316
#define SMG$K_TRM_FIND	311
#define SMG$K_TRM_INSERT_HERE	312
#define SMG$K_TRM_REMOVE	313
#define SMG$K_TRM_SELECT	314
#define SMG$K_TRM_PREV_SCREEN	315
#define SMG$K_TRM_NEXT_SCREEN	316
#define SMG$K_TRM_FIRST_DOWN	321
#define SMG$K_TRM_SECOND_DOWN	322
#define SMG$K_TRM_THIRD_DOWN	323
#define SMG$K_TRM_FOURTH_DOWN	324
#define SMG$K_TRM_FIRST_UP	325
#define SMG$K_TRM_SECOND_UP	326
#define SMG$K_TRM_THIRD_UP	327
#define SMG$K_TRM_FOURTH_UP	328
#define SMG$K_TRM_CANCELLED	508
#define SMG$K_TRM_TIMEOUT	509
#define SMG$K_TRM_BUFFER_FULL	510
#define SMG$K_TRM_UNKNOWN	511
#define SMG$C_CHANGE_RENDITION	10
#define SMG$C_DELETE_CHARS	11
#define SMG$C_ERASE_DISPLAY	12
#define SMG$C_ERASE_LINE	13
#define SMG$C_HOME_CURSOR	14
#define SMG$C_INSERT_CHARS	15
#define SMG$C_INSERT_LINE	16
#define SMG$C_PUT_CHARS	17
#define SMG$C_PUT_LINE	18
#define SMG$C_PUT_DISPLAY_ENCODED	19
#define SMG$C_RETURN_CURSOR_POS	20
#define SMG$C_PUT_WITH_SCROLL	21
#define SMG$C_SET_CURSOR_ABS	22
#define SMG$C_SET_CURSOR_REL	23
#define SMG$C_DELETE_LINE	24
#define SMG$C_ERASE_CHARS	25
#define SMG$C_SCROLL_DISPLAY_AREA	26
#define SMG$C_CHANGE_VIRTUAL_DISPLAY	27
#define SMG$C_LABEL_BORDER	28
#define SMG$C_END_DISPLAY_UPDATE	29
#define SMG$C_MOVE_TEXT	30
#define SMG$C_UNITED_KINGDOM	0
#define SMG$C_ASCII	1
#define SMG$C_SPEC_GRAPHICS	2
#define SMG$C_ALT_CHAR	3
#define SMG$C_ALT_GRAPHICS	4
#define SMG$C_UNKNOWN	5
#define SMG$C_SUPPLEMENTAL	6
#define SMG$C_JIS_ROMAN	7
#define SMG$C_JIS_KANA	8
#define SMG$C_KANJI	9
#define SMG$C_HANZI	10
#define SMG$C_HANYU	11
#define SMG$C_HANGUL	12
#define SMG$C_KS_ROMAN	13
#define SMG$C_UPPER_LEFT	0
#define SMG$C_LOWER_LEFT	1
#define SMG$C_UPPER_RIGHT	2
#define SMG$C_LOWER_RIGHT	3
#define SMG$K_TOP	0
#define SMG$K_BOTTOM	1
#define SMG$K_LEFT	2
#define SMG$K_RIGHT	3
#define SMG$K_BLOCK	0
#define SMG$K_VERTICAL	1
#define SMG$K_HORIZONTAL	2
#define SMG$C_COLOR_UNKNOWN	0
#define SMG$C_COLOR_WHITE	1
#define SMG$C_COLOR_BLACK	2
#define SMG$C_COLOR_BLUE	3
#define SMG$C_COLOR_CYAN	4
#define SMG$C_COLOR_GREEN	5
#define SMG$C_COLOR_MAGENTA	6
#define SMG$C_COLOR_RED	7
#define SMG$C_COLOR_YELLOW	8
#define SMG$C_COLOR_LIGHT	9
#define SMG$C_COLOR_DARK	10
#define SMG$C_COLOR_USER1	11
#define SMG$C_COLOR_USER2	12
#define SMG$C_COLOR_USER3	13
#define SMG$C_COLOR_USER4	14
#define SMG$C_COLOR_USER5	15
#define SMG$C_COLOR_USER6	16
#define SMG$C_COLOR_USER7	17
#define SMG$C_COLOR_USER8	18
#define SMG$K_UNKNOWN	0
#define SMG$K_VT05	1
#define SMG$K_VT52	2
#define SMG$K_VT100	3
#define SMG$K_VTFOREIGN	4
#define SMG$K_HARDCOPY	5
#define SMG$K_VTTERMTABLE	6
#define SMG$K_FIRST_PRIV_TYPE	191
#define SMG$K_BUF_ENABLED	0
#define SMG$K_MINUPD	1
#define SMG$K_CLEAR_SCREEN	2
#define SMG$K_NOTABS	3
#define SMG$K_PROTECT	4
#define SMG$K_IGNORE	5
#define SMG$K_RELEASE_PBD	6
#define SMG$M_BUF_ENABLED	1
#define SMG$M_MINUPD	2
#define SMG$M_CLEAR_SCREEN	4
#define SMG$M_NOTABS	8
#define SMG$M_PROTECT	16
#define SMG$M_IGNORE	32
#define SMG$M_RELEASE_PBD	64
#define SMG$m_spare15	(-128)
#define SMG$V_BUF_ENABLED	0
#define SMG$V_MINUPD	1
#define SMG$V_CLEAR_SCREEN	2
#define SMG$V_NOTABS	3
#define SMG$V_PROTECT	4
#define SMG$V_IGNORE	5
#define SMG$V_RELEASE_PBD	6
#define SMG$S_spare15	25
#define SMG$v_spare15	7
#define SMG$M_KEY_NOECHO	1
#define SMG$M_KEY_TERMINATE	2
#define SMG$M_KEY_LOCK	4
#define SMG$M_KEY_PROTECTED	8
#define SMG$M_KEY_SETSTATE	16
#define SMG$m_spare18	(-32)
#define SMG$S_KEY_DEF_ATTR	4
#define SMG$V_KEY_NOECHO	0
#define SMG$V_KEY_TERMINATE	1
#define SMG$V_KEY_LOCK	2
#define SMG$V_KEY_PROTECTED	3
#define SMG$V_KEY_SETSTATE	4
#define SMG$S_spare18	27
#define SMG$v_spare18	5
#define SMG$M_BOLD	1
#define SMG$M_REVERSE	2
#define SMG$M_BLINK	4
#define SMG$M_UNDERLINE	8
#define SMG$M_INVISIBLE	16
#define SMG$M_USER1	256
#define SMG$M_USER2	512
#define SMG$M_USER3	1024
#define SMG$M_USER4	2048
#define SMG$M_USER5	4096
#define SMG$M_USER6	8192
#define SMG$M_USER7	16384
#define SMG$M_USER8	32768
#define SMG$m_spare14	(-65536)
#define SMG$V_BOLD	0
#define SMG$V_REVERSE	1
#define SMG$V_BLINK	2
#define SMG$V_UNDERLINE	3
#define SMG$V_INVISIBLE	4
#define SMG$V_USER1	8
#define SMG$V_USER2	9
#define SMG$V_USER3	10
#define SMG$V_USER4	11
#define SMG$V_USER5	12
#define SMG$V_USER6	13
#define SMG$V_USER7	14
#define SMG$V_USER8	15
#define SMG$S_spare14	16
#define SMG$v_spare14	16
#define SMG$M_NORMAL	0
#define SMG$M_BORDER	1
#define SMG$M_TRUNC_ICON	2
#define SMG$M_DISPLAY_CONTROLS	4
#define SMG$M_USER_DISPLAY	8
#define SMG$M_BLOCK_BORDER	16
#define SMG$M_PROTECT_DISPLAY	32
#define SMG$m_spare12	(-64)
#define SMG$S_DISPLAY_ATTRIBUTES	4
#define SMG$V_BORDER	0
#define SMG$V_TRUNC_ICON	1
#define SMG$V_DISPLAY_CONTROLS	2
#define SMG$V_USER_DISPLAY	3
#define SMG$V_BLOCK_BORDER	4
#define SMG$V_PROTECT_DISPLAY	5
#define SMG$S_spare12	26
#define SMG$v_spare12	6
#define SMG$M_DATA_FOLLOWS	1
#define SMG$M_SEND_EOF	2
#define SMG$m_spare11	(-4)
#define SMG$S_SUBPROCESS_FLAGS	4
#define SMG$V_DATA_FOLLOWS	0
#define SMG$V_SEND_EOF	1
#define SMG$S_spare11	30
#define SMG$v_spare11	2
#define SMG$M_ERASE_PBD	1
#define SMG$M_IGNORE_BATCHED	2
#define SMG$m_spare10	(-4)
#define SMG$S_DELETE_PBD_FLAGS	4
#define SMG$V_ERASE_PBD	0
#define SMG$V_IGNORE_BATCHED	1
#define SMG$S_spare10	30
#define SMG$v_spare10	2
#define SMG$M_KEEP_CONTENTS	1
#define SMG$M_WORKSTATION	2
#define SMG$m_spare9	(-4)
#define SMG$S_CREATE_PBD_FLAGS	4
#define SMG$V_KEEP_CONTENTS	0
#define SMG$V_WORKSTATION	1
#define SMG$S_spare9	30
#define SMG$v_spare9	2
#define SMG$M_FUNC_KEYS	1
#define SMG$M_NOKEEP	2
#define SMG$M_NORECALL	4
#define SMG$m_spare8	(-8)
#define SMG$S_READ_FLAGS	4
#define SMG$V_FUNC_KEYS	0
#define SMG$V_NOKEEP	1
#define SMG$V_NORECALL	2
#define SMG$S_spare8	29
#define SMG$v_spare8	3
#define SMG$M_CURSOR_OFF	1
#define SMG$M_CURSOR_ON	2
#define SMG$M_SCROLL_JUMP	4
#define SMG$M_SCROLL_SMOOTH	8
#define SMG$m_spare16	(-16)
#define SMG$S_SET_CURSOR_FLAGS	4
#define SMG$V_CURSOR_OFF	0
#define SMG$V_CURSOR_ON	1
#define SMG$V_SCROLL_JUMP	2
#define SMG$V_SCROLL_SMOOTH	3
#define SMG$S_spare16	28
#define SMG$v_spare16	4
#define SMG$M_VIEWPORT	1
#define SMG$M_SUBPROCESS	2
#define SMG$M_MENU	4
#define SMG$m_spare7	(-8)
#define SMG$S_GET_DISPLAY_FLAGS	4
#define SMG$V_VIEWPORT	0
#define SMG$V_SUBPROCESS	1
#define SMG$V_MENU	2
#define SMG$S_spare7	29
#define SMG$v_spare7	3
#define SMG$M_ERASE_LINE	1
#define SMG$M_ERASE_TO_EOL	2
#define SMG$m_spare6	(-4)
#define SMG$S_PUT_CHARS_FLAGS	4
#define SMG$V_ERASE_LINE	0
#define SMG$V_ERASE_TO_EOL	1
#define SMG$S_spare6	30
#define SMG$v_spare6	2
#define SMG$M_TEXT_SAVE	1
#define SMG$M_TEXT_ONLY	2
#define SMG$m_spare17	(-4)
#define SMG$S_MOVE_TEXT_FLAGS	4
#define SMG$V_TEXT_SAVE	0
#define SMG$V_TEXT_ONLY	1
#define SMG$S_spare17	30
#define SMG$v_spare17	2
#define SMG$M_FORM_FEED	1
#define SMG$m_spare5	(-2)
#define SMG$S_SNAPSHOT_FLAGS	4
#define SMG$V_FORM_FEED	0
#define SMG$S_spare5	31
#define SMG$v_spare5	1
#define SMG$M_WRAP_CHAR	1
#define SMG$M_WRAP_WORD	2
#define SMG$m_spare4	(-4)
#define SMG$S_PUT_LINE_FLAGS	4
#define SMG$V_WRAP_CHAR	0
#define SMG$V_WRAP_WORD	1
#define SMG$S_spare4	30
#define SMG$v_spare4	2
#define SMG$M_KEYPAD_APPLICATION	1
#define SMG$M_KEYPAD_NUMERIC	2
#define SMG$m_spare3	(-4)
#define SMG$S_KEYPAD_MODES	4
#define SMG$V_KEYPAD_APPLICATION	0
#define SMG$V_KEYPAD_NUMERIC	1
#define SMG$S_spare3	30
#define SMG$v_spare3	2
#define SMG$M_DISPLAY_PASTED	1
#define SMG$m_spare19	(-2)
#define SMG$S_PASTING_INFO_FLAGS	4
#define SMG$V_DISPLAY_PASTED	0
#define SMG$S_spare19	31
#define SMG$v_spare19	1
#define SMG$M_REMOVE_ITEM	1
#define SMG$M_FIXED_FORMAT	2
#define SMG$M_DOUBLE_SPACE	4
#define SMG$M_RETURN_IMMED	8
#define SMG$M_ERASE_MENU	16
#define SMG$M_WIDE_MENU	32
#define SMG$M_WRAP_MENU	64
#define SMG$M_FULL_FIELD	128
#define SMG$m_spare2	(-256)
#define SMG$S_MENU_FLAGS	4
#define SMG$V_REMOVE_ITEM	0
#define SMG$V_FIXED_FORMAT	1
#define SMG$V_DOUBLE_SPACE	2
#define SMG$V_RETURN_IMMED	3
#define SMG$V_ERASE_MENU	4
#define SMG$V_WIDE_MENU	5
#define SMG$V_WRAP_MENU	6
#define SMG$V_FULL_FIELD	7
#define SMG$S_spare2	24
#define SMG$v_spare2	8
#define SMG$M_UP	1
#define SMG$M_DOWN	2
#define SMG$M_RIGHT	4
#define SMG$M_LEFT	8
#define SMG$m_spare1	(-16)
#define SMG$S_SCROLL_DIRS	4
#define SMG$V_UP	0
#define SMG$V_DOWN	1
#define SMG$V_RIGHT	2
#define SMG$V_LEFT	3
#define SMG$S_spare1	28
#define SMG$v_spare1	4
#define SMG$C_BAND_INFORMATION_TABLE	12
#define SMG$C_PASTEBOARD_INFO_BLOCK	32
#define SMG$C_KEYBOARD_INFO_BLOCK	20
#define SMG$S_SMGDEF	32
#define SMG$S_BAND_INFORMATION_TABLE	12
#define SMG$R_BAND_INFORMATION_TABLE	0
#define SMG$L_PASTEBOARD_ID	0
#define SMG$L_ARG	4
#define SMG$R_CHARACTER_OVERLAY	8
#define SMG$B_CHARACTER	8
#define SMG$L_CHARACTER	8
#define SMG$S_PASTEBOARD_INFO_BLOCK	32
#define SMG$R_PASTEBOARD_INFO_BLOCK	0
#define SMG$L_DEVCHAR	0
#define SMG$L_DEVDEPEND	4
#define SMG$L_DEVDEPEND2	8
#define SMG$B_DEVCLASS	12
#define SMG$B_SMG_DEVTYPE	13
#define SMG$B_PHY_DEVTYPE	14
#define SMG$B_ROWS	15
#define SMG$W_WIDTH	16
#define SMG$B_COLOR	18
#define SMG$B_PARITY	19
#define SMG$W_SPEED	20
#define SMG$W_FILL	22
#define SMG$W_CURSOR_ROW	24
#define SMG$W_CURSOR_COL	26
#define SMG$L_CURSOR_DID	28
#define SMG$S_KEYBOARD_INFO_BLOCK	20
#define SMG$R_KEYBOARD_INFO_BLOCK	0
#define SMG$B_RECALL_SIZE	13
#define SMG$B_TYPEAHEAD_CHAR	15
#define SMG$W_TYPEAHEAD_COUNT	18
#define SMG$S_OUT_OF_BAND_TABLE	12
#define SMG$L_PBD_ID	0
#define SMG$L_USER_ARG	4
#define SMG$R_CHAR_OVERLAY	8
#define SMG$B_CHAR	8
#define SMG$L_CHAR	8
#define SMG$C_OUT_OF_BAND_TABLE	12
#define SMG$S_SUBPROCESS_INFO_TABLE	12
#define SMG$L_DISP_ID	0
#define SMG$L_USR_ARG	4
#define SMG$L_STATUS	8
#define SMG$C_SUBPROCESS_INFO_TABLE	12
#define SMG$S_ATTRIBUTE_INFO_BLOCK	32
#define SMG$L_DEV_CHAR	0
#define SMG$L_DEV_DEPEND	4
#define SMG$L_DEV_DEPEND2	8
#define SMG$B_DEV_CLASS	12
#define SMG$R_DEV_OVERLAY	13
#define SMG$B_PBD_TYPE	13
#define SMG$B_RECALL_NUM	13
#define SMG$B_DEV_TYPE	14
#define SMG$R_ROW_OVERLAY	15
#define SMG$B_NUM_ROWS	15
#define SMG$B_TYPEAHD_CHAR	15
#define SMG$W_NUM_COLUMNS	16
#define SMG$R_COUNT_OVERLAY	18
#define SMG$W_TYPEAHD_CNT	18
#define SMG$S_COUNT_STRUCT	2
#define SMG$R_COUNT_STRUCT	18
#define SMG$B_PBD_COLOR	18
#define SMG$B_DEV_PARITY	19
#define SMG$W_DEV_SPEED	20
#define SMG$W_DEV_FILL	22
#define SMG$W_PHYS_CURSOR_ROW	24
#define SMG$W_PHYS_CURSOR_COL	26
#define SMG$L_DISPLAY_ID	28
#define SMG$C_ATTRIBUTE_INFO_BLOCK	32
/*
 * End of C_DEFS definitions
 */
