$ SET NOON
$ SET DEFAULT [.SRC]
$ FORTRAN/NOCHECK ADVENT.F
$ FORTRAN/NOCHECK AMAIN.F
$ FORTRAN/NOCHECK AINIT.F
$ FORTRAN/NOCHECK ASUBR.F
$ SET DEFAULT [-]
$ LINK/EXEC=ADVENT [.SRC]ADVENT,AMAIN,AINIT,ASUBR
