.\"	@(#)et.man
.\"
.TH ET LOCAL "Feb 13, 1991"
.UC 4
.SH NAME
et \- translator for sendmail configuration files
.SH SYNOPSIS
.B Et
[
.B \-d
]
[
.B \-q
]
[
.B \-D
\fIname\fP[=\fIvalue\fP] ...
]
[inputfile [outputfile]]
.br
.SH DESCRIPTION
.I Et
compiles a high-level language into a form understood by
.I /usr/lib/sendmail.
It is fully documented by the documentation provided with the program source.
.PP
.I Et
optionally passes the source file through
.I cpp
before parsing it.  This allows all the power of
.I cpp
to be applied to the input file.
.PP
If no inputfile is specified, STDIN is used.
If no outputfile is specified, STDOUT is used.
The distinguished name "-" is synonymous with STDIN or STDOUT, as appropriate.
.PP
By default,
.I Et
passes input lines along into the output stream as comments.
.SH OPTIONS
.IP -d
turns on the yydebug flag for the curious or desperate.
.IP -q
turns off the feature which passes input lines along into the output
stream as comments.
.PP
.I Et
accepts the options of
.B cpp,
and passes them along to the C pre-processor when it is invoked.
.B N.B 
If no such options are specified,
.B cpp
is not invoked.
.SH "SEE ALSO"
cpp(1), ease(local), sendmail(8), cfc(local)
.SH BUGS
.SH THIS MANUAL PAGE WRITTEN BY
jeff@tc.fluke.com, from inspection of the source code.
