$ LIBRARY = "SYS$LIBRARY:PIPE_MAILSHR.EXE"
$ IF .NOT. F$FILE (LIBRARY,"KNOWN")
$ THEN
$   INSTALL CREATE 'LIBRARY'
$ ELSE
$   INSTALL REMOVE 'LIBRARY'
$   INSTALL CREATE 'LIBRARY'
$ ENDIF
$
$ INSTALL LIST 'LIBRARY'/FULL
$ EXIT
