void initialize(void);
void readtfmword(void);
integer vfread(integer k);
integer tfmwidth(byte c);
void outdigs(integer j);
void printdigs(integer j);
void printoctal(byte c);
void outln(void);
void left(void);
void right(void);
void outBCPL(index k);
void outoctal(index k,index l);
void outchar(byte c);
void outface(index k);
void outfix(index k);
void checkBCPL(index k,index l);
void hashinput(void);
index ligf(index h,index x,index y);
index eval(index x,index y);
index ligf(index h,index x,index y);
boolean stringbalance(integer k,integer l);
void outasfix(integer x);
integer getbytes(integer k,boolean issigned);
boolean vfinput(void);
boolean organize(void);
void dosimplethings(void);
boolean domap(byte c);
boolean docharacters(void);
