void initialize(void);
void showerrorcontext(void);
void fillbuffer(void);
void getkeywordchar(void);
void getnext(void);
byte gethex(void);
void skiptoendofitem(void);
void copytoendofitem(void);
void finishtheproperty(void);
void lookup(void);
void entername(byte v);
void getname(void);
byte getbyte(void);
void getfourbytes(void);
fixword getfix(void);
pointer sortin(pointer h,fixword d);
integer mincover(pointer h,fixword d);
fixword shorten(pointer h,integer m);
void setindices(pointer h,fixword d);
void junkerror(void);
void readfourbytes(headerindex l);
void readBCPL(headerindex l,byte n);
void checktag(byte c);
void vffix(byte opcode,fixword x);
void readpacket(byte c);
void printoctal(byte c);
boolean hashinput(indx p,indx c);
indx f(indx h,indx x,indx y);
indx eval(indx x,indx y);
indx f(indx h,indx x,indx y);
void outscaled(fixword x);
void voutint(integer x);
void paramenter(void);
void vplenter(void);
void nameenter(void);
void readligkern(void);
void readcharinfo(void);
void readinput(void);
void corrandcheck(void);
void vfoutput(void);
