	.TITLE	BAT_MSG
	.IDENT	/01-001/
!++
!
!  File:	BAT_MSG.MSG
!
!  Author:	Hunter Goatley
!
!  Date:	June 6, 1991
!
!  Description:
!
!	Message file for BAT.B32.
!
!
!  Modification history:
!
!	01-000		Hunter Goatley		 6-JUN-1991 15:45
!		Genesis.
!
!--
	.FACILITY	BAT,1/PREFIX=BAT_

	.SEVERITY	INFORMATIONAL
ABORT		<aborted via ^Y....>
NOCMDS		<no commands entered - no job submitted>

	.SEVERITY	ERROR
INVQUAVAL	<value '!AS' invalid for /!AS qualifier>/FAO_COUNT=2

	.END
