!include <ntwin32.mak>

C_DEFINES=-DWIN_NT -DSTDC_HEADERS -D_POSIX_SOURCE -DDIRENT -DSTACK_DIRECTION=-1 -D__STDC__ -DDF_POSIX -D_POSIX_ -DCONVERT_TO_SLASHES -UCONVERT_TO_BACKSLASHES
C_INCLUDES=-I..\include\bsd -I..\include\df

all: mkdir.exe

..\bsdpsx\bsdpsx.lib:
	cd ..\bsdpsx
	nmake
	cd ..\mkdir

mkdir.obj: mkdir.c *.h

mkdiglob.obj: mkdiglob.c *.h

glob.obj: glob.c *.h

mkdir.exe: mkdir.obj mkdiglob.obj glob.obj ..\bsdpsx\bsdpsx.lib
	$(link) $(linkdebug) $(psxflags) -out:$*.exe $** $(psxlibs) ..\bsdpsx\bsdpsx.lib

.c.obj:
	$(cc) $(cflags) $(psxvars) $(cvars) $(cdebug) $(C_DEFINES) $(C_INCLUDES) $*.c
