void initialize(void);
void jumpout(void);
void inputln(void);
void opengffile(void);
void opentfmfile(void);
void opendvifile(void);
void readtfmword(void);
integer getbyte(void);
integer gettwobytes(void);
integer getthreebytes(void);
integer signedquad(void);
void readfontinfo(integer f,scaled s);
strnumber makestring(void);
void firststring(integer c);
keywordcode interpretxxx(void);
scaled getyyy(void);
void skipnop(void);
void beginname(void);
boolean morename(ASCIIcode c);
void endname(void);
void packfilename(strnumber n,strnumber a,strnumber e);
void startgf(void);
void writedvi(dviindex a,dviindex b);
void dviswap(void);
void dvifour(integer x);
void dvifontdef(internalfontnumber f);
void loadfonts(void);
void typeset(eightbits c);
void dviscaled(real x);
void hbox(strnumber s,internalfontnumber f,boolean sendit);
void slantcomplaint(real r);
nodepointer getavail(void);
void nodeins(nodepointer p,nodepointer q);
boolean overlap(nodepointer p,nodepointer q);
nodepointer nearestdot(nodepointer p,scaled d0);
void convert(scaled x,scaled y);
void dvigoto(scaled x,scaled y);
void topcoords(nodepointer p);
void botcoords(nodepointer p);
void rightcoords(nodepointer p);
void leftcoords(nodepointer p);
boolean placelabel(nodepointer p);
void dopixels(void);
