void error(void);
void jumpout(void);
void scanargs(void);
void initialize(void);
void openinput(void);
boolean inputln(textfile f);
boolean linesdontmatch(void);
void primethechangebuffer(void);
void checkchange(void);
void getline(void);
namepointer lookup(void);
void getnext(void);
void flushbuffer(eightbits b,boolean percent);
void breakout(void);
void outstr(namepointer p);
void outname(namepointer p);
void outmacandname(ASCIIcode n,namepointer p);
void copy(integer firstloc);
void dothetranslation(void);
