$! Compile under VMS
$ CC/DECC/STAND=VAXC/define=VMS CLOCK
$ CC/DECC/STAND=VAXC/define=VMS DTIME
$ CC/DECC/STAND=VAXC/define=VMS MOON
$ CC/DECC/STAND=VAXC/define=VMS OCLOCK
$ CC/DECC/STAND=VAXC/define=VMS PHASE
$ CC/DECC/STAND=VAXC/define=VMS TRANSFORM
