
ALL :   DCLCOMPLETE.EXE, PIPE.EXE
        !DCLCOMPLETE and PIPE built

DCLCOMPLETE.EXE :       DCLCOMPLETE.OBJ
        $(LINK)$(LINKFLAGS)/NOTRACE $(MMS$SOURCE)

PIPE.EXE :      PIPE.OBJ
        $(LINK)$(LINKFLAGS)/NOTRACE $(MMS$SOURCE)
