.\"	@(#)ease.l	(FLUKE) 25-feb-87
.\"
.TH EASE LOCAL "Feb 13, 1991"
.UC 4
.SH NAME
ease \- precompiler for sendmail configuration files
.SH SYNOPSIS
.B ease
[
.B \-D
\fIname\fP[=\fIvalue\fP] ...
]
file ...
.br
.SH DESCRIPTION
.I Ease
compiles a high-level language into a form understood by
.I /usr/lib/sendmail.
It is fully documented in the files which reside in the source directory.
.PP
.I Ease
is actually a shell script which passes the source file through
.I cpp
and thence into the actual ease translator
.I et.
Output is printed to the standard output.
.SH "SEE ALSO"
cpp(1), et(local), sendmail(8), cfc(local)
.SH BUGS
.SH BROUGHT TO YOU BY
jeff@tc.fluke.COM
