@c Copyright (C) 1992 Free Software Foundation.
@c This is part of the GNU font utilities manual.
@c For copying conditions, see the file fontutil.texi.

@node Introduction, Installation, Top, Top
@chapter Introduction

@cindex introduction

This manual corresponds to version 0.6 of the GNU font
utilities.

You can manipulate fonts in various ways using the utilities: conversion
of a scanned image to a bitmap font, hand-editing of bitmaps, conversion
of a bitmap font to an outline font, and more.  More generally, you can
start with a scanned image of artwork and work your way through to a
finished font with side bearings, accented characters, ligatures, and so
on.

@cindex Knuth, Donald E.
The font formats recognized by these programs are primarily those used
by the (freely available) @TeX{} typesetting system developed by
@w{Donald E.} Knuth from 1977--1990.  The filenames, font searching, and
other aspects of their usage are also based on @TeX{}.  They also
support output of PostScript Type 1 fonts.

@cindex Morris, Robert A.
@cindex Martin, Rick
Some of this software was originally written as part of the research
program in digital typography at the University of Massachusetts at
Boston, directed by @w{Robert A.} Morris.  The staff at UMB, Rick Martin in
particular, has been kind enough to let us to continue to use their
computers, despite our completing the Master's program there in 1989.
