/******************************************************************************
 * Copyright 1984 by Thomas E. Dickey.  All Rights Reserved.                  *
 *                                                                            *
 * You may freely copy or redistribute this software, so long as there is no  *
 * profit made from its use, sale trade or reproduction. You may not change   *
 * this copyright notice, and it must be included in any copy made.           *
 ******************************************************************************/
/* $Id: fibdef.h,v 1.2 1984/11/03 01:43:50 tom Exp $ */

#define	FIB$C_ADD_QUOTA	0xb
#define	FIB$C_CYL	0x1
#define	FIB$C_DSA_QUOTA	0xa
#define	FIB$C_ENA_QUOTA	0x9
#define	FIB$C_EXA_QUOTA	0xc
#define	FIB$C_ILLEGAL	0x5
#define	FIB$C_LBN	0x2
#define	FIB$C_LOCK_VOL	0x7
#define	FIB$C_MOD_QUOTA	0xd
#define	FIB$C_NEXTVOL	0x3
#define	FIB$C_POSEND	0x2
#define	FIB$C_REMAP	0x10
#define	FIB$C_REM_QUOTA	0xe
#define	FIB$C_REWINDFIL	0x6
#define	FIB$C_REWINDVOL	0x1
#define	FIB$C_RFI	0x4
#define	FIB$C_SPACE	0x4
#define	FIB$C_UNLK_VOL	0x8
#define	FIB$C_USEREOT	0xf
#define	FIB$C_VBN	0x3
#define	FIB$M_ALCON	0x1
#define	FIB$M_ALCONB	0x2
#define	FIB$M_ALDEF	0x8
#define	FIB$M_ALLNAM	0x20
#define	FIB$M_ALLOCATR	0x10
#define	FIB$M_ALLTYP	0x10
#define	FIB$M_ALLVER	0x8
#define	FIB$M_ALL_GRP	0x2
#define	FIB$M_ALL_MEM	0x1
#define	FIB$M_BLK_LOCK	0x4
#define	FIB$M_CURPOS	0x10
#define	FIB$M_DLOCK	0x2
#define	FIB$M_EXACT	0x1
#define	FIB$M_EXECUTE	0x10000
#define	FIB$M_EXTEND	0x80
#define	FIB$M_FILCON	0x4
#define	FIB$M_FINDFID	0x800
#define	FIB$M_HIGHVER	0x8000
#define	FIB$M_LOWVER	0x4000
#define	FIB$M_MARKBAD	0x400
#define	FIB$M_MOD_OVER	0x10
#define	FIB$M_MOD_PERM	0x8
#define	FIB$M_MOD_USE	0x4
#define	FIB$M_NEWVER	0x200
#define	FIB$M_NOCHARGE	0x8000
#define	FIB$M_NOHDREXT	0x200
#define	FIB$M_NOLOCK	0x100000
#define	FIB$M_NOREAD	0x400
#define	FIB$M_NORECORD	0x200000
#define	FIB$M_NOTRUNC	0x800
#define	FIB$M_NOWRITE	0x1
#define	FIB$M_ONCYL	0x2
#define	FIB$M_PRSRV_ATR	0x20000
#define	FIB$M_READCK	0x200
#define	FIB$M_REWIND	0x8
#define	FIB$M_RMSLOCK	0x40000
#define	FIB$M_SEQONLY	0x40
#define	FIB$M_SPOOL	0x10
#define	FIB$M_SUPERSEDE	0x400
#define	FIB$M_TRUNC	0x100
#define	FIB$M_UPDATE	0x40
#define	FIB$M_WILD	0x100
#define	FIB$M_WRITE	0x100
#define	FIB$M_WRITECK	0x20
#define	FIB$M_WRITETHRU	0x80000
#define	FIB$S_ALLOC	0xa
#define	FIB$S_DID	0x6
#define	FIB$S_FID	0x6
#define	FIB$S_LOC_FID	0x6
#define	FIB$V_ALCON	0x0
#define	FIB$V_ALCONB	0x1
#define	FIB$V_ALDEF	0x3
#define	FIB$V_ALLNAM	0x5
#define	FIB$V_ALLOCATR	0x4
#define	FIB$V_ALLTYP	0x4
#define	FIB$V_ALLVER	0x3
#define	FIB$V_ALL_GRP	0x1
#define	FIB$V_ALL_MEM	0x0
#define	FIB$V_BLK_LOCK	0x2
#define	FIB$V_CURPOS	0x4
#define	FIB$V_DLOCK	0x1
#define	FIB$V_EXACT	0x0
#define	FIB$V_EXECUTE	0x10
#define	FIB$V_EXTEND	0x7
#define	FIB$V_FILCON	0x2
#define	FIB$V_FINDFID	0xb
#define	FIB$V_HIGHVER	0xf
#define	FIB$V_LOWVER	0xe
#define	FIB$V_MARKBAD	0xa
#define	FIB$V_MOD_OVER	0x4
#define	FIB$V_MOD_PERM	0x3
#define	FIB$V_MOD_USE	0x2
#define	FIB$V_NEWVER	0x9
#define	FIB$V_NOCHARGE	0xf
#define	FIB$V_NOHDREXT	0x9
#define	FIB$V_NOLOCK	0x14
#define	FIB$V_NOREAD	0xa
#define	FIB$V_NORECORD	0x15
#define	FIB$V_NOTRUNC	0xb
#define	FIB$V_NOWRITE	0x0
#define	FIB$V_ONCYL	0x1
#define	FIB$V_PRSRV_ATR	0x11
#define	FIB$V_READCK	0x9
#define	FIB$V_REWIND	0x3
#define	FIB$V_RMSLOCK	0x12
#define	FIB$V_SEQONLY	0x6
#define	FIB$V_SPOOL	0x4
#define	FIB$V_SUPERSEDE	0xa
#define	FIB$V_TRUNC	0x8
#define	FIB$V_UPDATE	0x6
#define	FIB$V_WILD	0x8
#define	FIB$V_WRITE	0x8
#define	FIB$V_WRITECK	0x5
#define	FIB$V_WRITETHRU	0x13
