$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] FLIP.C
$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] GENERAL.C
$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] IMAGE.C
$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] MAIN.C
$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] SHRINK.C
$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] UI.C
