"GV.gsInterpreter:	gs",
"GV.gsCmdScanPDF:	gs \"-dNODISPLAY\" \"-dQUIET\" \"-sPDFname\"=%s \"-sDSCname\"=%s pdf2dsc.ps -c quit",
"GV.gsCmdConvPDF:	gs \"-dNODISPLAY\" \"-dQUIET\"  \"-dNOPAUSE\" \"-sPSFile\"=%s %s -c quit",
"GV.gsX11Device:	\"-sDEVICE=x11\"",
"GV.gsX11AlphaDevice:\"-dNOPLATFONTS\" \"-sDEVICE=x11alpha\"",
"GV.gsSafer:	True",
"GV.gsQuiet:	True",
"GV.gsArguments:",
"GV.printCommand:	Print /NoIdent /Delete /Queue = HP_417",
"GV.uncompressCommand:gzip -d -c %s > %s",
"GV.uncompressCommand:gzip -d -c %s > %s",
