.TH GLCHECK 1L "12th Mar 1991"
.SH NAME
glcheck \- check the content and size of a grasp library
.SH SYNTAX
.B glcheck <library-file>
.SH DESCRIPTION

This command will examine the specified library file, list its contents and
their sizes, then list any places where there is a gap between two files, or
where two files overlap one another.

.SH AUTHOR
Brad Daniels
.I <daniels@bigred.enet.dec.com>
