.TH PSSELECT 1
.SH NAME
psselect \- select pages from a PostScript file
.SH SYNOPSIS
.B psselect
[
.B \-q
] [
.B \-e
] [
.B \-o
] [
.B \-r
] [
.B \-p\fIpages\fR
] [
.I infile
[
.I outfile
] ]
.SH DESCRIPTION
.I Psselect
selects pages from a PostScript document, creating a new PostScript file. The
input PostScript file should follow the Adobe Document Structuring
Conventions.
.PP
The 
.I \-e
option selects all of the even pages; it may be used in conjunction with the
other page selection options.
.PP
The 
.I \-o
option selects all of the odd pages; it may be used in conjunction with the
other page selection options.
.PP
The 
.I \-p\fIpages\fR
option specifies the pages which are to be selected.
.I Pages
is a comma separated list of page ranges, each of which may be a page number,
or a page range of the form \fIfirst\fR-\fIlast\fR. If \fIfirst\fR is omitted,
the
first page is assumed, and if \fIlast\fR is omitted, the last page is assumed.
.PP
The 
.I \-r
option causes
.I psselect
to output the selected pages in reverse order.
.PP
Psselect normally prints the page numbers of the pages rearranged; the
.I \-q
option suppresses this.
.SH NOTES
.I Psselect
selects pages in the order that they appear in the file, starting from one. The
actual page number in the document may be different.
.SH AUTHOR
Angus Duggan
.SH "SEE ALSO"
psbook(1), pstops(1)
.SH TRADEMARKS
.B PostScript
is a trademark of Adobe Systems Incorporated.
.SH BUGS
.I Psselect
cannot cope with documents longer than 5000 pages.
