{************************************************************************
*									*
*  TPUDEF								*
*									*
*  Declarations for TPU$ (VAXTPU interface) Utility routines.		*
*									*
************************************************************************}


[ASYNCHRONOUS] FUNCTION TPU$CLEANUP (
	Flags : Mask_Longword )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION TPU$CLIPARSE (
	String : [CLASS_S] PACKED ARRAY [$L1..$U1:INTEGER] OF CHAR ;
	[ASYNCHRONOUS] FUNCTION Fileio   : UNSIGNED ;
	[ASYNCHRONOUS] FUNCTION Call_User : UNSIGNED )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION TPU$CLOSE_TERMINAL : UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION TPU$CONTROL : UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION TPU$EDIT (
	INPUT  : [CLASS_S] PACKED ARRAY [$L1..$U1:INTEGER] OF CHAR ;
	OUTPUT : [CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION TPU$EXECUTE_COMMAND (		{ ### ??????? ### }
	String : [CLASS_S] PACKED ARRAY [$L1..$U1:INTEGER] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION TPU$EXECUTE_INIFILE : UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION TPU$FILEIO (
	Code : UNSIGNED ;
	%REF Stream : ARRAY [$L2..$U2:INTEGER] OF [UNSAFE] UNSIGNED ;
	%REF Data : [UNSAFE] PACKED ARRAY [$L3..$U3:INTEGER] OF $UBYTE )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION TPU$HANDLER (
	%REF Signal_Vector    : PACKED ARRAY [$L1..$U1:INTEGER] OF UNSIGNED ;
	%REF Mechanism_Vector : PACKED ARRAY [$L2..$U2:INTEGER] OF UNSIGNED )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION TPU$INITIALIZE (
	[ASYNCHRONOUS] FUNCTION Callback : [UNSAFE] UNSIGNED ;
	User_Arg : [UNSAFE] UNSIGNED := %IMMED 0 )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION TPU$MESSAGE (
	String : [CLASS_S] PACKED ARRAY [$L1..$U1:INTEGER] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION TPU$PARSEINFO (
	[ASYNCHRONOUS] FUNCTION Fileio   : UNSIGNED ;
	[ASYNCHRONOUS] FUNCTION Call_User : UNSIGNED )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION TPU$TPU (
	Command : [CLASS_S] PACKED ARRAY [$L1..$U1:INTEGER] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

