$ def sys sys$library
$ CC/DEFINE=VMS/INCLUDE=[] ALGEBRA.C
$ CC/DEFINE=VMS/INCLUDE=[] GETOPT.C
$ CC/DEFINE=VMS/INCLUDE=[] ROTATION.C
$ CC/DEFINE=VMS/INCLUDE=[] VGP.C
$ CC/DEFINE=VMS/INCLUDE=[] WC.C
$ CC/DEFINE=VMS/INCLUDE=[] XSTUFF.C
