$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] ALGEBRA.C
$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] GETOPT.C
$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] ROTATION.C
$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] VGP.C
$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] WC.C
$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] XSTUFF.C
