void initialize(void);
void opendvifile(void);
void opentfmfile(void);
void readtfmword(void);
integer getbyte(void);
integer signedbyte(void);
integer gettwobytes(void);
integer signedpair(void);
integer getthreebytes(void);
integer signedtrio(void);
integer signedquad(void);
integer dvilength(void);
void movetobyte(integer n);
void printfont(integer f);
boolean inTFM(integer z);
boolean startmatch(void);
void inputln(void);
integer getinteger(void);
void dialog(void);
void definefont(integer e);
void flushtext(void);
void outtext(ASCIIcode c);
integer firstpar(eightbits o);
integer rulepixels(integer x);
boolean specialcases(eightbits o,integer p,integer a);
boolean dopage(void);
void skippages(void);
void readpostamble(void);
