void initialize(void);
void initpatterntrie(void);
triepointer firstfit(void);
void unpack(triepointer s);
optype newtrieop(valtype v,dottype d,optype n);
void insertpattern(valtype val,dottype dot);
void initcounttrie(void);
triecpointer firstcfit(void);
void unpackc(triecpointer b);
triecpointer insertcpat(wordindex fpos);
void traversecounttrie(triecpointer b,dottype i);
void collectcounttrie(void);
triepointer deletepatterns(triepointer s);
void deletebadpatterns(void);
void outputpatterns(triepointer s,dottype patlen);
void readword(void);
void hyphenate(void);
void changedots(void);
void outputhyphenatedword(void);
void doword(void);
void dodictionary(void);
void readpatterns(void);
