void initialize(void);
void outdigs(integer j);
void printdigs(integer j);
void printoctal(byte c);
void outln(void);
void left(void);
void right(void);
void outBCPL(index k);
void outoctal(index k,index l);
void outchar(byte c);
void outface(index k);
void outfix(index k);
void checkBCPL(index k,index l);
void hashinput(void);
index ffn(index h,index x,index y);
index eval(index x,index y);
index ffn(index h,index x,index y);
boolean organize(void);
void dosimplethings(void);
void docharacters(void);
