.\" Copyright 1998 Derek B. Noonburg
.TH pdftopbm 1 "14 Aug 2000"
.SH NAME
pdftopbm \- Portable Document Format (PDF) to Portable Bitmap (PBM)
converter (version 0.91)
.SH SYNOPSIS
.B pdftopbm
[options]
.I PDF-file PBM-root
.SH DESCRIPTION
.B Pdftopbm
converts Portable Document Format (PDF) files to black-and-white image
files in Portable Bitmap (PBM) format.
.PP
Pdftopbm reads the PDF file,
.IR PDF-file ,
and writes one PBM file for each page,
.IR PBM-root - nnnnnn .pbm,
where
.I nnnnnn
is the page number.
.SH OPTIONS
.TP
.BI \-f " number"
Specifies the first page to convert.
.TP
.BI \-l " number"
Specifies the last page to convert.
.TP
.BI \-r " number"
Specifies the resolution, in DPI.  The default is 150 DPI.
.TP
.BI \-upw " password"
Specify the user password for the PDF file.
.TP
.B \-q
Don't print any messages or errors.
.TP
.B \-v
Print copyright and version information.
.TP
.B \-h
Print usage information.
.RB ( \-help
is equivalent.)
.SH BUGS
Pdftopbm uses X to do the rendering, so it is limited by the
capabilities and performance of the X server.  In particular,
high-resolution output requires lots of memory.  Also, non-scalable
fonts will not look great.
.SH AUTHOR
The pdftopbm software and documentation are copyright 1996-2000 Derek
B. Noonburg (derekn@foolabs.com).
.SH "SEE ALSO"
.BR xpdf (1),
.BR pdftops (1),
.BR pdftotext (1),
.BR pdfinfo (1),
.BR pdfimages (1)
.br
.B http://www.foolabs.com/xpdf/
