{************************************************************************
*									*
*  STRDEF								*
*									*
*  Declarations for STR$ (String Handling) RTL routines.		*
*									*
************************************************************************}


[ASYNCHRONOUS] FUNCTION STR$ADD (
	Asign : UNSIGNED ;
	Aexp : INTEGER ;
	Adigits : [CLASS_S] PACKED ARRAY [$L3..$U3:INTEGER] OF CHAR ;
	Bsign : UNSIGNED ;
	Bexp : INTEGER ;
	Bdigits : [CLASS_S] PACKED ARRAY [$L6..$U6:INTEGER] OF CHAR ;
	VAR Csign : [VOLATILE] INTEGER ;
	VAR Cexp  : [VOLATILE] INTEGER ;
	%DESCR Cdigits : VARYING [$L9] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$ANALYZE_SDESC (
	Input_Descriptor : [CLASS_S] PACKED ARRAY [$L1..$U1:INTEGER] OF CHAR ;
	VAR Word_Integer_Length : [VOLATILE] $UWORD ;
	VAR Data_Address : [VOLATILE,UNSAFE] UNSIGNED )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$APPEND (
	%DESCR Destination_String : VARYING [$L1] OF CHAR ;
	Source_String : [CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$CASE_BLIND_COMPARE (
	First_Source_String :
		[CLASS_S] PACKED ARRAY [$L1..$U1:INTEGER] OF CHAR ;
	Second_Source_String :
		[CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR )
		: INTEGER ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$COMPARE (
	First_Source_String :
		[CLASS_S] PACKED ARRAY [$L1..$U1:INTEGER] OF CHAR ;
	Second_Source_String :
		[CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR )
		: INTEGER ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$COMPARE_EQL (
	First_Source_String :
		[CLASS_S] PACKED ARRAY [$L1..$U1:INTEGER] OF CHAR ;
	Second_Source_String :
		[CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$COMPARE_MULTI (
	First_Source_String :
		[CLASS_S] PACKED ARRAY [$L1..$U1:INTEGER] OF CHAR ;
	Second_Source_String :
		[CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR ;
	%IMMED Flags_Value : Mask_Longword := %IMMED 0 ;
	%IMMED Foreign_Language : UNSIGNED := %IMMED 1 )
		: INTEGER ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$CONCAT (
	%DESCR Destination_String : VARYING [$L1] OF CHAR ;
	Source_String  : [CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR ;
	Source_Strings : [CLASS_S,LIST]		{ Name differs from RTL manual }
			PACKED ARRAY [$L3..$U3:INTEGER] OF CHAR := %IMMED 0 )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$COPY_DX (
	%DESCR Destination_String : VARYING [$L1] OF CHAR ;
	Source_String  : [CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$COPY_R (
	%DESCR Destination_String : VARYING [$L1] OF CHAR ;
	Word_Integer_Source_Length : $UWORD ;
	%REF Source_String_Address : PACKED ARRAY [$L3..$U3:INTEGER] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$DIVIDE (
	Asign : UNSIGNED ;
	Aexp : INTEGER ;
	Adigits : [CLASS_S] PACKED ARRAY [$L3..$U3:INTEGER] OF CHAR ;
	Bsign : UNSIGNED ;
	Bexp : INTEGER ;
	Bdigits : [CLASS_S] PACKED ARRAY [$L6..$U6:INTEGER] OF CHAR ;
	Total_Digits : INTEGER ;
	Round_Truncate_Indicator : [UNSAFE] UNSIGNED ;
	VAR Csign : [VOLATILE] INTEGER ;
	VAR Cexp  : [VOLATILE] INTEGER ;
	%DESCR Cdigits : VARYING [$L11] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$DUPL_CHAR (
	%DESCR Destination_String : VARYING [$L1] OF CHAR ;
	Repetition_Count : INTEGER := %IMMED 0 ;
	Ascii_Character : [UNSAFE] $UBYTE := %IMMED 0 )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$ELEMENT (
	%DESCR Destination_String : VARYING [$L1] OF CHAR ;
	Element_Number : INTEGER ;
	Delimiter_String :	{ RTL manual differs }
		[CLASS_S] PACKED ARRAY [$L3..$U3:INTEGER] OF CHAR ;
	Source_String :		{ RTL manual differs }
		[CLASS_S] PACKED ARRAY [$L4..$U4:INTEGER] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$FIND_FIRST_IN_SET (
	Source_String : [CLASS_S] PACKED ARRAY [$L1..$U1:INTEGER] OF CHAR ;
	Set_Of_Characters : [CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR )
		: INTEGER ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$FIND_FIRST_NOT_IN_SET (
	Source_String : [CLASS_S] PACKED ARRAY [$L1..$U1:INTEGER] OF CHAR ;
	Set_Of_Characters : [CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR )
		: INTEGER ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$FIND_FIRST_SUBSTRING (
	Source_String : [CLASS_S] PACKED ARRAY [$L1..$U1:INTEGER] OF CHAR ;
	VAR INDEX : [VOLATILE] INTEGER ;
	VAR Substring_Index : [VOLATILE] INTEGER ;
	Substring  : [CLASS_S] PACKED ARRAY [$L4..$U4:INTEGER] OF CHAR ;
	Substrings : [CLASS_S,LIST]
			PACKED ARRAY [$L5..$U5:INTEGER] OF CHAR := %IMMED 0 )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$FREE1_DX (
	%STDESCR String_Descriptor : PACKED ARRAY [$L1..$U1:INTEGER] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$GET1_DX (
	Word_Integer_Length : $UWORD ;
	%STDESCR Character_String : PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$LEFT (
	%DESCR Destination_String : VARYING [$L1] OF CHAR ;
	Source_String : [CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR ;
	End_Position : INTEGER )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$LEN_EXTR (
	%DESCR Destination_String : VARYING [$L1] OF CHAR ;
	Source_String : [CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR ;
	Start_Position : INTEGER ;
	Longword_Integer_Length : INTEGER )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$MATCH_WILD (
	Candidate_String : [CLASS_S] PACKED ARRAY [$L1..$U1:INTEGER] OF CHAR ;
	Pattern_String   : [CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$MUL (
	Asign : UNSIGNED ;
	Aexp : INTEGER ;
	Adigits : [CLASS_S] PACKED ARRAY [$L3..$U3:INTEGER] OF CHAR ;
	Bsign : UNSIGNED ;
	Bexp : INTEGER ;
	Bdigits : [CLASS_S] PACKED ARRAY [$L6..$U6:INTEGER] OF CHAR ;
	VAR Csign : [VOLATILE] INTEGER ;
	VAR Cexp  : [VOLATILE] INTEGER ;
	%DESCR Cdigits : VARYING [$L9] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$POSITION (
	Source_String : [CLASS_S] PACKED ARRAY [$L1..$U1:INTEGER] OF CHAR ;
	Substring : [CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR ;
	Start_Position : INTEGER := %IMMED 0 )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$POS_EXTR (
	%DESCR Destination_String : VARYING [$L1] OF CHAR ;
	Source_String : [CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR ;
	Start_Position : INTEGER ;
	End_Position : INTEGER )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$PREFIX (
	%DESCR Destination_String : VARYING [$L1] OF CHAR ;
	Source_String : [CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$RECIP (
	Asign : UNSIGNED ;
	Aexp : INTEGER ;
	Adigits : [CLASS_S] PACKED ARRAY [$L3..$U3:INTEGER] OF CHAR ;
	Bsign : UNSIGNED ;
	Bexp : INTEGER ;
	Bdigits : [CLASS_S] PACKED ARRAY [$L6..$U6:INTEGER] OF CHAR ;
	VAR Csign : [VOLATILE] INTEGER ;
	VAR Cexp  : [VOLATILE] INTEGER ;
	%DESCR Cdigits : VARYING [$L9] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$REPLACE (
	%DESCR Destination_String : VARYING [$L1] OF CHAR ;
	Source_String : [CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR ;
	Start_Position : INTEGER ;
	End_Position : INTEGER ;
	Replacement_String : [CLASS_S] PACKED ARRAY [$L5..$U5:INTEGER] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$RIGHT (
	%DESCR Destination_String : VARYING [$L1] OF CHAR ;
	Source_String : [CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR ;
	Start_Position : INTEGER )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$ROUND (
	Places : INTEGER ;
	Flags : Mask_Longword ;
	Asign : UNSIGNED ;
	Aexp : INTEGER ;
	Adigits : [CLASS_S] PACKED ARRAY [$L5..$U5:INTEGER] OF CHAR ;
	VAR Csign : [VOLATILE] INTEGER ;
	VAR Cexp  : [VOLATILE] INTEGER ;
	%DESCR Cdigits : VARYING [$L8] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$TRANSLATE (
	%DESCR Destination_String : VARYING [$L1] OF CHAR ;
	Source_String      : [CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR ;
	Translation_String : [CLASS_S] PACKED ARRAY [$L3..$U3:INTEGER] OF CHAR ;
	Match_String       : [CLASS_S] PACKED ARRAY [$L4..$U4:INTEGER] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$TRIM (
	%DESCR Destination_String : VARYING [$L1] OF CHAR ;
	Source_String : [CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR ;
	VAR Resultant_Length : [VOLATILE] $UWORD := %IMMED 0 )
		: UNSIGNED ; EXTERNAL ;

[ASYNCHRONOUS] FUNCTION STR$UPCASE (
	%DESCR Destination_String : VARYING [$L1] OF CHAR ;
	Source_String : [CLASS_S] PACKED ARRAY [$L2..$U2:INTEGER] OF CHAR )
		: UNSIGNED ; EXTERNAL ;

