.\" $Id: psfmbox.1,v 3.1 1991/11/27 06:10:44 ajf Exp ajf $
.TH psfmbox 1 ""
.SH NAME
psfmbox \- print one or more mail boxes with psf filters
.SH SYNOPSIS

.B psfmbox
.I box box ...
.nf

where box      is the mail box file to be printed
.fi

.SH DESCRIPTION

Each mail box file is printed
4-up on a physical page. Each mail box becomes a separate
print job.  The mailbox is identified by file name on a header
line on each page.

Selected mail header lines are printed.  Some portions of various
header lines are highlighted in either bold or italic print.

.SH EXAMPLE

Typically, psfmbox is used in the following form:
.nf

       psfmbox /usr/mail/myloginid
.fi

.SH SEE ALSO

psf psfman psfmail psfbs psfnroff
