.\" $Id: psfman.1,v 3.1 1991/11/27 06:10:44 ajf Exp ajf $
.TH PSFMAN 1 ""
.SH NAME
psfman \- print man pages with psf filters
.SH SYNOPSIS

.B psfman
[
.B chapter
]
.I page page ...
.nf

 where  chapter is the option man chapter
        page    is the man page to be printed
.fi

.SH DESCRIPTION

.I psfman 
prints one or more man pages
2-up on a physical page. Each man page becomes a separate
print job.

The resulting paper may be filed in an 5.5x8.5 inch binder.

.SH EXAMPLE

The vi man pages may be printed with:

       psfman vi

or the stty page from chapter 1:

       psfman 1 stty

.SH OPTIONS
.TP
.B chapter
specifies an optional man chapter.  This may be a single
digit (1..9) or a Xenix chapter designation.

.SH BUGS
If 
.B man
uses 
.B more -s
as a pager (i.e. if more sqeezes multiple blank lines into
a single line), then page breaks are not always handled correctly
by psfman.  This can usually be corrected with the man option -Tlp.

.SH SEE ALSO

psf psfmail psfbs psfnroff psfmbox
