.\" $Id: psfnroff.1,v 3.1 1991/11/27 06:10:44 ajf Exp ajf $
.TH PSFNROFF 1 ""
.SH NAME
psfnroff \- print nroff'ed pages with psf
.SH SYNOPSIS

.B psfnroff
[
.B options
]
.I doc.nr doc.nr ...
.nf

 where   options    are options passed to nroff
         doc.nr     is the document to be printed
.fi

.SH DESCRIPTION

.I psfnroff
generates one or more document files with 
.I nroff
and
passes the output through
.I psf
to the
.I lp
spooler.  Printing is
2-up on a physical page. Each document becomes a separate
print job.

The resulting paper may be filed in an 5.5x8.5 inch binder.

.SH EXAMPLE

If a document is to be printed with the "ms"
macro's, the following command might be used:

        psfnroff -ms document.ms

.SH OPTIONS
.TP
.B options
are any options to be passed to 
.I nroff.
Typically, a single
option specifying the
.I nroff
macro is used.

.SH SEE ALSO

psf psfmbox psfmbox psfbs psfman
