    EXTERNAL LONG FUNCTION MAIL$MAILFILE_BEGIN ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$MAILFILE_CLOSE ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$MAILFILE_COMPRESS ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$MAILFILE_END ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$MAILFILE_INFO_FILE ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$MAILFILE_MODIFY ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$MAILFILE_OPEN ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$MAILFILE_PURGE_WASTE ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$MESSAGE_BEGIN ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$MESSAGE_COPY ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$MESSAGE_DELETE ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$MESSAGE_END ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$MESSAGE_GET ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$MESSAGE_INFO ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$MESSAGE_MODIFY ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$MESSAGE_SELECT ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$SEND_ABORT ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$SEND_ADD_ADDRESS ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$SEND_ADD_ATTRIBUTE ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$SEND_ADD_BODYPART ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$SEND_BEGIN ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$SEND_END ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$SEND_MESSAGE ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$USER_BEGIN ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$USER_DELETE_INFO ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$USER_END ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$USER_GET_INFO ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
    EXTERNAL LONG FUNCTION MAIL$USER_SET_INFO ( &
				LONG BY REF, &
				ANY BY REF, &
				ANY BY REF)
 
