C*
C*    CLOSE THE OPERATOR'S LOG AND OPEN A NEW ONE SO THAT SECURITY
C*    AUDIT PROGRAM CAN BE RUN
C*
      INCLUDE '($OPCDEF)'
      CHARACTER *24 FIELD
      DIMENSION INT(6)
      EQUIVALENCE (INT(1),FIELD)
      INTEGER SYS$SNDOPR
C
      INT(1) = OPC$_RQ_LOGI
      INT(2) = 0
      INT(3) = 0
      FIELD(11:) = CHAR(3) // '_OP'
      ISTAT = SYS$SNDOPR ( FIELD, )
      CALL EXIT(ISTAT)
      END
