/********************************************************************************************************************************/
/* Created  1-NOV-1993 13:00:48 by VAX SDL T3.2-8      Source:  1-NOV-1993 12:04:16 UAF_MESSAGES.SDL;12 */
/********************************************************************************************************************************/
 
/*** MODULE UAF ***/
/*                                                                          */
/* This SDL File Generated by VAX-11 Message V04-00 on  1-NOV-1993 12:04:16.69 */
/*                                                                          */
/***************************************************************************** */
/**									    * */
/**  COPYRIGHT (C) 1986 BY						    * */
/**  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    * */
/**  ALL RIGHTS RESERVED.						    * */
/**									    * */
/**  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   * */
/**  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   * */
/**  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   * */
/**  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   * */
/**  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   * */
/**  TRANSFERRED.							    * */
/**									    * */
/**  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   * */
/**  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   * */
/**  CORPORATION.							    * */
/**									    * */
/**  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   * */
/**  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    * */
/**									    * */
/**									    * */
/***************************************************************************** */
/*++                                                                        */
/*                                                                          */
/* FACILITY:	AUTHORIZATION RECORD MAINTENANCE UTILITY                    */
/*                                                                          */
/* ABSTRACT:                                                                */
/*                                                                          */
/*	THIS MODULE DEFINES THE MESSAGES USED BY THE DECWINDOWS AUTHORIZE   */
/*	UTILITY.                                                            */
/*                                                                          */
/* AUTHOR:	L. MARK PILANT		CREATION DATE:  17-JUN-1993         */
/*                                                                          */
/* MODIFICATION HISTORY:                                                    */
/*                                                                          */
/*--                                                                        */
#define UAF$_FACILITY 1009
/* TO AVOID A CONFLICT WITH THE EXISTING AUTHORIZE UTILITY, SET THE BASE    */
/* MESSAGE CODE.                                                            */
#define UAF$_NOUAIPRIVS 66190592
#define UAF$_NOWILDCARDS 66190602
#define UAF$_UAFOPENERR 66190610
#define UAF$_UAFREADERR 66190618
#define UAF$_UAFWRITERR 66190626
#define UAF$_NOSUCHUSER 66190634
#define UAF$_USEREXISTS 66190642
#define UAF$_TIMECVTERR 66190650
#define UAF$_NOPROCMEM 66190660
#define UAF$_INITDISPLAY 66190668
#define UAF$_MODTEMPLATE 66190676
#define UAF$_INTERNAL1 66190684
#define UAF$_INTERNAL2 66190692
