$ define GL sys$library
$ CC/DECC/PREFIX=ALL AUDIO.C
$ CC/DECC/PREFIX=ALL BATTALION.C
$ CC/DECC/PREFIX=ALL FONT.C
$ CC/DECC/PREFIX=ALL GPRIM.C
$ CC/DECC/PREFIX=ALL GRAPHICS.C
$ CC/DECC/PREFIX=ALL NET.C
$ CC/DECC/PREFIX=ALL OBJECTS.C
$ CC/DECC/PREFIX=ALL TEXT.C
$ CC/DECC/PREFIX=ALL TK.C
$ CC/DECC/PREFIX=ALL UPDATE.C
$ CC/DECC/PREFIX=ALL VMS_STRINGS.C
