void printpacket(pcktpointer p);
void printfont(fontnumber f);
void jumpout(void);
void confusion(pcktpointer p);
void overflow(pcktpointer p,int16u n);
void badtfm(void);
void badfont(void);
void baddvi(void);
void initialize(void);
pcktpointer makepacket(void);
pcktpointer newpacket(void);
void flushpacket(void);
int8 pcktsbyte(void);
int8u pcktubyte(void);
int16 pcktspair(void);
int16u pcktupair(void);
int24 pcktstrio(void);
int24u pcktutrio(void);
integer pcktsquad(void);
void pcktfour(integer x);
void pcktchar(boolean upd,integer ext,eightbits res);
void pcktunsigned(eightbits o,integer x);
void pcktsigned(eightbits o,integer x);
void makename(pcktpointer e);
widthpointer makewidth(integer w);
boolean findpacket(void);
void startpacket(typeflag t);
void buildpacket(void);
void readtfmword(void);
void checkchecksum(integer c,boolean u);
void checkdesignsize(integer d);
widthpointer checkwidth(integer w);
fontnumber makefont(void);
integer dvilength(void);
void dvimove(integer n);
int8 dvisbyte(void);
int8u dviubyte(void);
int16 dvispair(void);
int16u dviupair(void);
int24 dvistrio(void);
int24u dviutrio(void);
integer dvisquad(void);
int31 dviuquad(void);
int31 dvipquad(void);
integer dvipointer(void);
void dvifirstpar(void);
void dvifont(void);
void dvidofont(boolean second);
int8u vfubyte(void);
int16u vfupair(void);
int24 vfstrio(void);
int24u vfutrio(void);
integer vfsquad(void);
integer vffix1(void);
integer vffix2(void);
integer vffix3(void);
integer vffix3u(void);
integer vffix4(void);
int31 vfuquad(void);
int31 vfpquad(void);
int31 vffixp(void);
void vffirstpar(void);
void vffont(void);
void vfdofont(void);
boolean dovf(void);
void inputln(void);
boolean scankeyword(pcktpointer p,int7 l);
integer scanint(void);
void scancount(void);
void dialog(void);
void outpacket(pcktpointer p);
void outfour(integer x);
void outchar(boolean upd,integer ext,eightbits res);
void outunsigned(eightbits o,integer x);
void outsigned(eightbits o,integer x);
void outfntdef(fontnumber f);
boolean startmatch(void);
void dopre(void);
void dobop(void);
void doeop(void);
void dopush(void);
void dopop(void);
void doxxx(void);
void doright(void);
void dodown(void);
void dowidth(void);
void dorule(void);
void dochar(void);
void dofont(void);
void pcktfirstpar(void);
void dovfpacket(void);
void dodvi(void);
void closefilesandterminate(void);
