.TH CPUS 1 "4 May 1993"
.SH NAME
cpus \- popup a window showing system\-wide CPU usage by user.
.SH SYNOPSIS
.B cpus [machines]
.SH DESCRIPTION
.B Cpus
pops up an X window showing details of CPU usage on the machines
given as arguments. If no arguments are given, a default set of
machines is used. A 
.B ps
is launched on each machine via
.B rsh
and the results are displayed. This is useful if you want to get a
quick idea of the state of the machines on your network.
Each machine's CPU usage is represented as a series of vertical bars,
each contains a user name and they are sized in proportion to the
amount of CPU they are consuming.

The display
is static i.e. it does not update after a certain time. This is
intended to give a quick picture of what's going on, not to be a CPU
hog itself.
.SH RESOURCES
Your resource file can specify the color to use for a given user.
If you have a user called 
.B jkh
then you can put something like the following in your ~/.Xdefaults (or
wherever you keep your application's defaults).
.sp
    cpus*jkh.background: red
.br
    cpus*jkh.foreground: white
.sp
Colors for the various machine names may be given in the same fashion. If
you have a conflict with machine and user names, tough cookies!
.SH BUGS
Doesn't attempt to make sure that a slice showing a proportion of CPU
usage is actually big enough to hold the name of that user.
.SH AUTHOR
Terry Jones (terry@santafe.edu)
.br
Santa Fe Institute
.br
May 4, 1993
