	.title DFUMSG Error messages

	.facility DFU,1/prefix=DFU_

	.severity informational

	.severity warning

	.severity error

ASSIGN		<Error assigning channel to disk,>
EXHFAIL		<Failed to setup exit handler,>
EXPREG		<Error creating dynamic memory,>
IOERR		<Error reading INDEXF.SYS,>
INDEXERR	<Error opening INDEXF.SYS,>
NOPRIV		<No privilege to perform this function (DFU_ALLPRIV not granted)>
	.end
