$ DEFINE/JOB X11 DECW$INCLUDE
$ DEFINE/JOB GS_LIB DISK$LAF:[DYSON.GS.GS6_01]
$ DEFINE/JOB GS_DOC DISK$LAF:[DYSON.GS.GS6_01]
$ DEFINE/JOB DECC$USER_INCLUDE DISK$LAF:[DYSON.GS.GS6_01], DECW$INCLUDE, DECC$LIBRARY_INCLUDE, SYS$LIBRARY
$ DEFINE/JOB DECC$SYSTEM_INCLUDE DISK$LAF:[DYSON.GS.GS6_01], DECW$INCLUDE, DECC$LIBRARY_INCLUDE, SYS$LIBRARY
$ DEFINE/JOB SYS DECC$LIBRARY_INCLUDE,SYS$LIBRARY
