$!
$ CC DEVICE_SCAN/NODEBUG/OPTI
$ LINK DEVICE_SCAN/NODEBUG,SYS$INPUT/OPT
SYS$SHARE:VAXCRTL/SHARE
$!
$ If F$Search("DEVICE_SCAN.*;-1") .nes. "" Then Purge DEVICE_SCAN.*
$ If F$Search("DEVICE_SCAN.OBJ") .nes. "" Then Delete DEVICE_SCAN.OBJ;*
$!
$ Exit
$!
$ CC DEVICE_SCAN/DEBUG/NOOPT
$ LINK DEVICE_SCAN/DEBUG,SYS$INPUT/OPT
SYS$SHARE:VAXCRTL/SHARE
$!
$ If F$Search("DEVICE_SCAN.*;-1") .nes. "" Then Purge DEVICE_SCAN.*
$ If F$Search("DEVICE_SCAN.OBJ") .nes. "" Then Delete DEVICE_SCAN.OBJ;*
$!
