$ DEF SYS SYS$LIBRARY:
$ CC/DEFINE=VMS BITS.C
$ CC/DEFINE=VMS BOARD.C
$ CC/DEFINE=VMS COLBITS.C
$ CC/DEFINE=VMS DEMO.C
$ CC/DEFINE=VMS DISPLAY.C
$ CC/DEFINE=VMS MAIN.C
$ CC/DEFINE=VMS NUBOT.C
$ CC/DEFINE=VMS PARSE.C
$ CC/DEFINE=VMS ZOT.C
