!include <ntwin32.mak>

ELVIS_DEFS=-DCS_IBMPC -DCS_SPECIAL -DNO_CURSORSHAPE -DWIN_NT -DSETJMP_KLUDGE
C_DEFINES=-DSTDC_HEADERS -D_POSIX_SOURCE -DDIRENT -DSTACK_DIRECTION=-1 -D__STDC__ -DDF_POSIX -D_POSIX_ -Dmajor $(ELVIS_DEFS)
C_INCLUDES=-I..\include\bsd -I..\include\df -I.

all: vi.exe

..\term\term.lib:
	cd ..\term
	nmake
	cd ..\elvis

..\bsdpsx\bsdpsx.lib:
	cd ..\bsdpsx
	nmake
	cd ..\elvis

vi.obj: vi.c *.h

blk.obj: blk.c *.h

cmd1.obj: cmd1.c *.h

cmd2.obj: cmd2.c *.h

curses.obj: curses.c *.h

cut.obj: cut.c *.h

ex.obj: ex.c *.h

input.obj: input.c *.h

main.obj: main.c *.h

misc.obj: misc.c *.h

modify.obj: modify.c *.h

move1.obj: move1.c *.h

move2.obj: move2.c *.h

move3.obj: move3.c *.h

move4.obj: move4.c *.h

move5.obj: move5.c *.h

opts.obj: opts.c *.h

recycle.obj: recycle.c *.h

redraw.obj: redraw.c *.h

regexp.obj: regexp.c *.h

regsub.obj: regsub.c *.h

system.obj: system.c *.h

tio.obj: tio.c *.h

tmp.obj: tmp.c *.h

vars.obj: vars.c *.h

vcmd.obj: vcmd.c *.h

vi.exe: vi.obj blk.obj cmd1.obj cmd2.obj curses.obj cut.obj ex.obj input.obj main.obj misc.obj modify.obj move1.obj move2.obj move3.obj move4.obj move5.obj opts.obj recycle.obj redraw.obj regexp.obj regsub.obj system.obj tio.obj tmp.obj vars.obj vcmd.obj ..\term\term.lib ..\bsdpsx\bsdpsx.lib
	$(link) $(linkdebug) $(psxflags) -out:$*.exe $** $(psxlibs) ..\term\term.lib ..\bsdpsx\bsdpsx.lib

.c.obj:
	$(cc) $(cflags) $(psxvars) $(cvars) $(cdebug) $(C_DEFINES) $(C_INCLUDES) $*.c
