#ifndef __LATDEF_LOADED
#define __LATDEF_LOADED	1

/*** MODULE $latdef ***/
/*                                                                          */
/* This SDL File Generated by VAX-11 Message V04-00 on  8-APR-1988 00:43:09.31 */
/*                                                                          */
/*                                                                          */
/* MODULE:  LATMSG.MSG                                                      */
/*                                                                          */
/***************************************************************************** */
/**									    * */
/**  COPYRIGHT (C) 1978, 1980, 1982, 1984, 1985, 1987 BY			    * */
/**  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    * */
/**  ALL RIGHTS RESERVED.						    * */
/** 									    * */
/**  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   * */
/**  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   * */
/**  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   * */
/**  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   * */
/**  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   * */
/**  TRANSFERRED.							    * */
/** 									    * */
/**  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   * */
/**  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   * */
/**  CORPORATION.							    * */
/** 									    * */
/**  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   * */
/**  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    * */
/** 									    * */
/**									    * */
/***************************************************************************** */
/*                                                                          */
/* VERSION:	'V05-002'                                                   */
/*                                                                          */
/*	V05-002	JFC0015		JAMES F. CAHILL			10-AUG-1987 */
/*		FIX CAPITALIZATION PROBLEMS                                 */
/*                                                                          */
/*	V05-001			(VARIOUS AUTHORS)                           */
/*		INITIAL VERSION                                             */
/*                                                                          */
/* THIS FILE REPRESENTS THE MERGE OF ERROR MESSAGES FOR LATCP, LAT, AND LGU */
/* LATCP MESSAGES APPEAR FIRST AS THIS FACILITY HAS BEEN SHIPPED. WHILE THE */
/* ERROR NAMES ARE CHANGED WITH THE ASSIGNMENT OF A LAT FACILITY CODE, THE  */
/* ERROR MESSAGE NUMBERS/MEANINGS ARE NOT. NEW ERROR MESSAGES ARE ADDED     */
/* AT THE SECTION BELOW WHERE .BASE VALUES HAVE BEEN ASSIGNED.              */
/*                                                                          */
#define LAT$_FACILITY 374
#define LAT$_CMDBUFOVFLW 24543244
#define LAT$_CANTBIND 24543250
#define LAT$_IVCMD 24543258
#define LAT$_IVDEV 24543266
#define LAT$_IVQUAL 24543274
#define LAT$_MAXSERV 24543282
#define LAT$_NOTERMS 24543290
#define LAT$_NONODE 24543298
#define LAT$_NOTLOADED 24543306
#define LAT$_NOTINITED 24543314
#define LAT$_NOTSTARTED 24543322
#define LAT$_NOTSTOPPED 24543330
#define LAT$_NOTSET 24543338
#define LAT$_NOHISTORY 24543346
#define LAT$_NOSTARTHIST 24543354
#define LAT$_NOSUCHSERV 24543362
#define LAT$_NOTFROMLAT 24543370
#define LAT$_INTERNAL 24543378
#define LAT$_SERVEXISTS 24543386
#define LAT$_LOCKED 24543394
#define LAT$_UNDEFLINK 24543402
#define LAT$_LINKEXISTS 24543410
#define LAT$_LINKACTIVE 24543418
#define LAT$_MAXLINKS 24543426
#define LAT$_NOLINK 24543432
#define LAT$_STARTED 24543443
#define LAT$_STOPPED 24543451
#define LAT$_SET 24543459
#define LAT$_NOSERVERS 24543467
/*                                                                          */
/* NEW MESSAGES ARE ADDED ONLY IN THE SECTIONS BELOW                        */
/*                                                                          */
#define LAT$_ALREADYDEF 24544835
#define LAT$_NOTDEF 24544843
#define LAT$_NOCONTEXT 24544851
#define LAT$_LOGSTOPPED 24546434
#define LAT$_CONTEXTINIT 24546442
#define LAT$_ILLSTRUCT 24546450
#define LAT$_CONSISTANCY 24546458
/*                                                                          */
/* LAT CONNECTION REJECTION REASON CODES. THESE MESSAGES CORRESPOND TO      */
/* THE REJECTION REASON CODES GENERATED BY LTDRIVER WHEN A CONNECTION       */
/* REQUEST IS ABORTED (IE. FAILS). THE REASON CODE IS RETURNED IN PART      */
/* OF THE IOSB AND MAY BE TRANSLATED TO THE CORRESPONDING CODE BELOW        */
/* WITH A SIMPLE TRANSLATION VECTOR.                                        */
/*                                                                          */
#define LAT$_LRJUNKNOWN 24551236
#define LAT$_LRJSHUTDOWN 24551244
#define LAT$_LRJRESOURCE 24551252
#define LAT$_LRJINUSE 24551260
#define LAT$_LRJNOSERVICE 24551268
#define LAT$_LRJDISABLE 24551276
#define LAT$_LRJNOTOFFERED 24551284
#define LAT$_LRJNAMEUNKNOWN 24551292
#define LAT$_LRJACCESSREJECT 24551300
#define LAT$_LRJACCESSDENIED 24551308
#define LAT$_LRJCORRUPT 24551316
#define LAT$_LRJNOTSUPPORT 24551324
#define LAT$_LRJNOSTART 24551332
#define LAT$_LRJDELETED 24551340
#define LAT$_LRJILLEGAL 24551348
#define LAT$_CONTIMEOUT 24551356
#define LAT$_CONAPPLICATION 24551364

#endif					/* __LATDEF_LOADED */
