$ CC /STANDARD=VAXC ANNOUNCE
$
$ if f$getsyi("ARCH_NAME") .nes. "VAX" then $ goto LINK_ALPHA
$
$ LINK ANNOUNCE, -
       SYS$SYSTEM:SYS.STB /SELECTIVE_SEARCH, -
       SYS$INPUT /OPTIONS
SYS$SHARE:VAXCRTL /SHARE
$
$ EXIT
$
$LINK_ALPHA:
$ LINK /SYSEXE ANNOUNCE
$
$ EXIT
