$! File: SYS$MANAGER:START_ANNOUNCE.COM
$
$ RUN /DETACHED -
      /PROCESS_NAME=SYS$ANNOUNCE -
      /PRIVILEGES=(PRMMBX) -
      /PRIORITY=15 -
      /NOSWAPPING -
      /UIC=[SYSTEM] -
      /INPUT=SYS$MANAGER:ANNOUNCE.COM -
      /OUTPUT=SYS$MANAGER:ANNOUNCE.LOG -
      SYS$SYSTEM:LOGINOUT
$
$ WAIT 00:00:10
$
$ DEFINE /SYSTEM SYS$ANNOUNCE "@''F$TRNLNM(""SYS$ANNOUNCE_MBX"")'"
$
$ EXIT
