$ FORTRAN CLASS_SCHEDULER.FOR
$ FORTRAN OPERATOR.FOR
$ FORTRAN SHUTDOWN.FOR
$
$ MESSAGE CLASS_SCHEDULER.MSG /OBJECT=MSG.OBJ
$
$ LINK /TRACEBACK CLASS_SCHEDULER.OBJ, -
		  OPERATOR.OBJ, -
		  SHUTDOWN.OBJ, - 
                  MSG.OBJ, -
                  SYS$INPUT /OPTIONS
IDENT="SCHED V1.0"
$
$ EXIT
