!=======================================================================
! CLASS_SCHEDULER version 1.0, Curtis Rempel
! 
! File: CLASS_SCHEDULER.MSG
!
! This file contains the messages for CLASS_SCHEDULER.
!=======================================================================

.title  CLASS_SCHEDULER messages
.ident  'Version 1.0'

.facility SCHED, 1 /prefix=SCHED_

.severity INFORMATIONAL
!-----------------------------------------------------------------------
OPRSHUTDWN      <Shutdown was requested by the operator>/FAO=0

.severity WARNING
!-----------------------------------------------------------------------

.severity ERROR
!-----------------------------------------------------------------------

.severity FATAL
!-----------------------------------------------------------------------

.end
