.\"
.\"	xkal2xremind : Convert xkal files to xremind format
.\"
.\"	George Ferguson, ferguson@cs.rochester.edu,  20 Feb 1991.
.\"
.\"	$Id: xkal2xremind.man,v 1.1 91/02/28 11:22:05 ferguson Exp $
.\"
.TH XKAL2XREMIND 1 "20/2/91"
.ds ]W U of Rochester
.SH NAME
xkal2xremind \- convert xkal files to xremind format
.SH SYNOPSIS
.B xkal2xremind
[-a appoints]
[output file]
.SH DESCRIPTION
.PP
Xkal2xremind converts
.BR xkal (1)
reminder files to
.BR xremind (1)
format and writes them to either the filename given on the command line, or
to ~/.xremind by default. Only weekly or one-shot reminders are written
since these are the only type of date specifiers
.B xremind
understands. Both the system and personal reminder files are used for the
conversion.
.PP
The
.B xkal
"\c
.B -a
appoints"
option can be given on the command line to change the personal reminders
file. The filename "-" can be given to force output to stdout.
.SH FILES
.PP
.nf
.na
~/.appoints			- default appointment file
$LIBDIR/xkal.appoints	- default system appintment file
~/.xremind			- default output file
.ad
.fi
.SH "SEE ALSO"
.PP
X(1),
xremind(1).
xkal(1).
.SH AUTHOR
.PP
George Ferguson, University of Rochester
.br
(ferguson@cs.rochester.edu)
