.\"
.\"
.\"	xkal-mail : Mails today's reminders if there are any that are above
.\"		criticality level 0.
.\"
.\"	George Ferguson, ferguson@cs.rochester.edu, 19 Feb 1991.
.\"
.\"	$Id: xkal-mail.man,v 1.1 91/02/28 11:21:56 ferguson Exp $
.\"
.TH XKAL-MAIL 1 "19/2/91"
.ds ]W U of Rochester
.SH NAME
xkal-mail \- mail reminders using xkal
.SH SYNOPSIS
.B xkal-mail
[recipient]
.SH DESCRIPTION
.PP
Xkal-mail mails today's reminders if there are any that are above
criticality level 0.
If no argument is given,
the mail message is sent to the value of the
environment variable
.BR $USER ,
which ought to be set automatically.
.SH ENVIRONMENT
USER					- default recipient for mail
.SH FILES
.PP
.nf
.na
~/.appoints			- default appointment file
$LIBDIR/xkal.appoints	- default system appintment file
.ad
.fi
.SH "SEE ALSO"
.PP
X(1),
xkal(1),
xkal-automail(1).
.SH AUTHOR
.PP
George Ferguson, University of Rochester
.br
(ferguson@cs.rochester.edu)
