.\" Copyright (c) 1994-6 Michael J. Gourlay
.TH XMORPH 1
.SH NAME
xmorph \- digital image warping (morphing) for X window system
.SH SYNOPSIS
.B xmorph
.RB "[\|" \-start
.I imagefile
.RB "[\|" \-finish
.IR imagefile "\|]\|]"
.SH DESCRIPTION
.B xmorph
is a digital image warping program, also known as a "morphing"
program.  It runs under the X Window System.  If
.I imagefile
names are provided on the command line, then those images are loaded
in.  Otherwise,
.B xmorph
generates images to be used in lieu of images
provided by the user.  Images may be loaded from menus within
.BR xmorph .
.B xmorph
has built-in help pages that answer questions about the details
of its use.  Run
.B xmorph
for more information.
.SH OPTIONS
.TP
.B \-start \fIimagefile\fP
Load the
.I imagefile
as the "source" image.
.TP
.B \-finish \fIimagefile\fP
Load the
.I imagefile
as the "destination" image.
.SH "SEE ALSO"
.BR X (1),
.BR ppmtotga (1),
.BR tgatoppm (1),
(netpbm or PBMplus),
.BR djpeg (1),
.BR cjpeg (1),
.BR mpeg_encode (1)
from Berkeley,
ImageMagick
.SH BUGS
The only image file type currently supported is Targa, but it will
load any type of Targa.

.LP
The program "xv" can not read xmorph's TGA files.

.LP
The digital image warp algorithm is compute intensive, and runs slowly
on slow machine.

.LP
As of 30 May 1996,
.B xmorph
is in beta release.  Report bugs to michael.gourlay@colorado.edu
