	.TITLE		CVTLIS_MSG
	.IDENT		"V1.0"
!+
!  Facility:	CVTLIS messages
!
!  Author:	Hunter Goatley
!		Copyright © 1994, MadGoat Software.  All rights reserved.
!
!  Date:	December 6, 1994
!
!  Modified by:
!
!	V1.0		Hunter Goatley		 6-DEC-1994 07:34
!		Original version.
!-
	.FACILITY	CVTLIS,1/PREFIX=CVTLIS__

.SEVERITY	INFO
CREATING	<creating !AS file !AS....>/FAO_COUNT=2
CONVERTED	<file !AS converted to file !AS>/FAO_COUNT=2

.SEVERITY	ERROR
UNKNOWN		<listing file created by unsupported compiler>

.END
