.TITLE		FINGER_MSG
.FACILITY	FINGER,1062/PREFIX=FINGER__
.IDENT		"V1.0"
!++
!
! DESCRIPTION:
!
!   These are the message codes used by the FINGER utility.
!
! AUTHOR:   M. Madison
!   	    COPYRIGHT © 1990, RENSSELAER POLYTECHNIC INSTITUTE.
!   	    ALL RIGHTS RESERVED.
!
! CREATION DATE: 30-APR-1990
!
! MODIFICATION HISTORY:
!
!   30-APR-1990 V1.0	Madison	    Initial coding.
!--

.SEVERITY   	FATAL
NOCONNECT   	<could not connect to remote host>

.END
