$! @disk:[X11R4]x11R4_setup.com   ! Decus X11R4 XAW/XMU libraries needed
$ CC/DEFINE=VMS CHAMBER.C
$ CC/DEFINE=VMS DOC.C
$ CC/DEFINE=VMS DYNAMICS.C
$ CC/DEFINE=VMS HELP.C
$ CC/DEFINE=VMS MAIN.C
$ CC/DEFINE=VMS MAN.C
$ CC/DEFINE=VMS MOLECULE.C
$ CC/DEFINE=VMS QUICK.C
$ CC/DEFINE=VMS TIMESTEP.C
$ CC/DEFINE=VMS UTIL.C
$ CC/DEFINE=VMS XGAS.C
