	.TITLE	NOTICE_MSG
	.FACILITY	NOTICE,101/prefix=NOTICE$_
!
!  Copyright © 1992--1994, MadGoat Software.  All rights reserved.
!
!++
!
!  Facility:	NOTICE
!
!  Module:	NOTICE_MSG.MSG
!
!  Author:	Hunter Goatley, goathunter@WKUVX1.WKU.EDU
!		Western Kentucky University
!
!  Date:	May 6, 1992
!
!  Modified by:
!
!	01-000		Hunter Goatley		 6-MAY-1992 08:11
!		Genesis.
!--
	.SEVERITY	ERROR
NOSUCHTOPIC	<no such topic in library>
LBRFNF		<NOTICE library file not found>

	.SEVERITY	INFORMATIONAL
NEWNOTICE	<there are unread system notices; type NOTICE for a list>

	.END
