$	INQ INP "Symbol file to get "
$	IF INP .EQS. "" THEN EXIT
$	OPEN /WRITE OUTP TEMPGET.MAR
$	WRITE OUTP "	.TITLE TEMPGET"
$	WRITE OUTP "	",INP," GLOBAL"
$	WRITE OUTP "	.END"
$	CLOSE OUTP
$	MAC TEMPGET+SYS$LIBRARY:LIB.MLB/LIB
$	LINK/NOEXE/MAP/FULL TEMPGET
$	TYPE /PAG TEMPGET.MAP
