***************
*** 2,11 ****
  
  SITEDIR=..
  CC=gcc
! OPT=-g -O -D_POSIX_SOURCE -DBSD386
  CFLAGS=$(OPT) -I$(SITEDIR)
  LDFLAGS=
! LOADLIBES=
  SHELL=/bin/sh
  
  .SUFFIXES:
--- 2,11 ----
  
  SITEDIR=..
  CC=gcc
! OPT=-g
  CFLAGS=$(OPT) -I$(SITEDIR)
  LDFLAGS=
! LOADLIBES=-lcposix
  SHELL=/bin/sh
  
  .SUFFIXES:
