\input texinfo	@c -*-texinfo-*-
@comment %**start of header
@setfilename guide.info
@settitle Zen and the Art of the Internet
@comment %**end of header

@smallbook

@iftex
@finalout
@end iftex

@ifinfo
Copyright @copyright{} 1992 Brendan P. Kehoe

Permission is granted to make and distribute verbatim copies of
this guide provided the copyright notice and this permission notice
are preserved on all copies.

@ignore
Permission is granted to process this file through TeX and print the
results, provided the printed document carries copying permission
notice identical to this one except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).

@end ignore
Permission is granted to copy and distribute modified versions of this
booklet under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this booklet
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by the author.
@end ifinfo

@setchapternewpage odd
@titlepage
@title Zen and the Art of the Internet
@subtitle A Beginner's Guide to the Internet
@subtitle First Edition
@subtitle January 1992

@author by Brendan P. Kehoe

@page
@vskip 0pt plus 1filll
This is revision 1.0 of February 2, 1992.
@vskip .75truein
Copyright @copyright{} 1992 Brendan P. Kehoe

Permission is granted to make and distribute verbatim copies of
this guide provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
booklet under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this booklet
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by the author.
@end titlepage

@node Top, Basics, (dir), (dir)
@ifinfo
@node Top
@top Guide

Zen and the Art of the Internet is a booklet intended to introduce a
user to the benefits and facilities available through the Internet.
@end ifinfo

@menu
@end menu

@c Chapters...
@include preface.texi
@include acks.texi
@include net-basics.texi
@include email.texi
@include ftp.texi
@include usenet.texi
@include telnet.texi
@include tools.texi
@include commercial.texi
@include hear.texi
@include finding.texi
@include concl.texi
@include appendixes.texi
@include gloss.texi
@iftex
@include biblio.texi
@include indices.texi
@end iftex

@contents
@bye
