$ CC/DECC/PREFIX=ALL/INCLUDE=[] MAIN.C
$ CC/DECC/PREFIX=ALL/INCLUDE=[] RESOURCE.C
$ CC/DECC/PREFIX=ALL/INCLUDE=[] WINTYPE.C
$ CC/DECC/PREFIX=ALL/INCLUDE=[] XPM2PIXMAP.C
$ CC/DECC/PREFIX=ALL/INCLUDE=[] XTRON.C
