$ V = 'F$VERIFY(0)
$!
$! LINK.COM
$!   Creates MMK.EXE from object code.
$!
$ OPT = "OPT"
$ BINDIR = "[.BIN-VAX]"
$ IF F$GETSYI("HW_MODEL") .GE. 1024
$ THEN
$   OPT = "ALPHA_OPT"
$   BINDIR = "[.BIN-AXP]"
$ ENDIF
$ DEFINE/NOLOG BIN_DIR 'BINDIR
$!
$ SET VERIFY
$ LINK/EXEC=MMK.EXE/NOTRACE MMK.'OPT'/OPT
$!'F$VERIFY(0)
$ DEASSIGN BIN_DIR
$ EXIT 1+0*F$VERIFY(V)
