$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] PLAYING.C
$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] RNGS.C
$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] TERTRIS.C
$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] UTILS.C
$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] UNIX_TIMES.C
$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] STRINGS.C
$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] GETHOSTNAME.C
$ CC/DECC/PREFIX=ALL/DEFINE=VMS/INCLUDE=[] UNLINK.C
