#
#  MMS/MMK build file for MAILCOUNT
#
#  Hunter Goatley, June 3, 1995
#
.IFDEF EXE
.ELSE
EXE = .EXE
OBJ = .OBJ
.ENDIF

.IFDEF __ALPHA__
CC = CC/STANDARD=VAXC/L_DOUBLE=64
.ELSE
CC = CC/STANDARD=VAXC
.ENDIF

MAILCOUNT$(EXE) : MAILCOUNT$(OBJ),GETRED$(OBJ),FPARSE$(OBJ)
	$(LINK)$(LINKFLAGS)/NOTRACE $(MMS$SOURCE_LIST)

MAILCOUNT$(OBJ) :	MAILCOUNT.C
GETRED$(OBJ) :		GETRED.C
FPARSE$(OBJ) :		FPARSE.C
