$	LINK PINE, -
	ADDRBOOK,ADDRUTIL,ADRBKLIB,ARGS,CONTEXT,FILTER,FOLDER, -
	help,HELPTEXT,IMAP,INIT,MAILCMD,MAILINDX,MAILVIEW,NEWMAIL, -
	status,OTHER,PRINT,REPLY,SCREEN,SEND,SIGNALS,STRINGS,TTY_VMS,os_VMS, -
	[-.pico]pico/libr,[-.C-CLIENT]IMAP2,MAIL,MISC,NNTP,NNTPClient,NEWS_VMS,OSDEP_VMS,-
	RFC822,SMTP,SM_VMS,VMS_MAIL,sys$input:/opt
multinet:multinet_socket_library/share
sys$share:vaxcrtl/share
$ EXIT
