$ RUN /DETACHED -
      /PROCESS_NAME="Announce Daemon" -
      /PRIVILEGES=(PRMMBX) -
      /PRIORITY=15 -
      /NOSWAPPING -
      /UIC=[SYSTEM] -
      /WORKING_SET=128 -
      /MAXIMUM_WORKING_SET=128 -
      SYS$SYSTEM:ANNOUNCE_DAEMON
$ WAIT 00:00:10
$ DEFINE /SYSTEM SYS$ANNOUNCE "@''F$TRNLNM(""SYS$ANNOUNCE_MBX"")'"
$ EXIT
