	integer*4	NMA$C_OBJ_NIC
	integer*4	NMA$C_FNC_LOA
	integer*4	NMA$C_FNC_DUM
	integer*4	NMA$C_FNC_TRI
	integer*4	NMA$C_FNC_TES
	integer*4	NMA$C_FNC_CHA
	integer*4	NMA$C_FNC_REA
	integer*4	NMA$C_FNC_ZER
	integer*4	NMA$C_FNC_SYS
	integer*4	NMA$M_OPT_ENT
	integer*4	NMA$M_OPT_CLE
	integer*4	NMA$M_OPT_PER
	integer*4	NMA$M_OPT_INF
	integer*4	NMA$C_OPINF_SUM
	integer*4	NMA$C_OPINF_STA
	integer*4	NMA$C_OPINF_CHA
	integer*4	NMA$C_OPINF_COU
	integer*4	NMA$C_OPINF_EVE
	integer*4	NMA$M_OPT_ACC
	integer*4	NMA$M_OPT_REA
	integer*4	NMA$C_SYS_RST
	integer*4	NMA$C_SYS_RSX
	integer*4	NMA$C_SYS_TOP
	integer*4	NMA$C_SYS_VMS
	integer*4	NMA$C_SYS_RT
	integer*4	NMA$C_ENT_NOD
	integer*4	NMA$C_ENT_LIN
	integer*4	NMA$C_ENT_LOG
	integer*4	NMA$C_ENT_CIR
	integer*4	NMA$C_ENT_MOD
	integer*4	NMA$C_ENT_ARE
	integer*4	NMA$C_SENT_ALI
	integer*4	NMA$C_SENT_OBJ
	integer*4	NMA$C_SENT_PRO
	integer*4	NMA$C_SENT_SYS
	integer*4	NMA$C_SENT_LNK
	integer*4	NMA$M_ENT_EXE
	integer*4	NMA$C_ENT_ADJ
	integer*4	NMA$C_ENT_ACT
	integer*4	NMA$C_ENT_KNO
	integer*4	NMA$C_ENT_ADD
	integer*4	NMA$C_ENT_ALL
	integer*4	NMA$C_ENT_LOO
	integer*4	NMA$C_SNK_CON
	integer*4	NMA$C_SNK_FIL
	integer*4	NMA$C_SNK_MON
	integer*4	NMA$M_CNT_TYP
	integer*4	NMA$M_CNT_MAP
	integer*4	NMA$M_CNT_WID
	integer*4	NMA$M_CNT_COU
	integer*4	NMA$M_CNT_WIL
	integer*4	NMA$M_CNT_WIH
	integer*4	NMA$S_OPT_ENT
	integer*4	NMA$V_OPT_ENT
	integer*4	NMA$V_OPT_CLE
	integer*4	NMA$V_OPT_PER
	integer*4	NMA$S_OPT_INF
	integer*4	NMA$V_OPT_INF
	integer*4	NMA$V_OPT_ACC
	integer*4	NMA$V_OPT_REA
	integer*4	NMA$V_ENT_EXE
	integer*4	NMA$S_CNT_TYP
	integer*4	NMA$V_CNT_TYP
	integer*4	NMA$V_CNT_MAP
	integer*4	NMA$S_CNT_WID
	integer*4	NMA$V_CNT_WID
	integer*4	NMA$V_CNT_COU
	integer*4	NMA$V_CNT_WIL
	integer*4	NMA$V_CNT_WIH
	integer*4	NMA$M_PTY_TYP
	integer*4	NMA$C_PTY_MAX
	integer*4	NMA$M_PTY_CLE
	integer*4	NMA$M_PTY_MUL
	integer*4	NMA$M_PTY_COD
	integer*4	NMA$M_PTY_CMU
	integer*4	NMA$M_PTY_NLE
	integer*4	NMA$M_PTY_NTY
	integer*4	NMA$M_PTY_ASC
	integer*4	NMA$C_NTY_DU
	integer*4	NMA$C_NTY_DS
	integer*4	NMA$C_NTY_H
	integer*4	NMA$C_NTY_O
	integer*4	NMA$C_NLE_IMAGE
	integer*4	NMA$C_NLE_BYTE
	integer*4	NMA$C_NLE_WORD
	integer*4	NMA$C_NLE_LONG
	integer*4	NMA$C_NLE_QUAD
	integer*4	NMA$C_PTY_AI
	integer*4	NMA$C_PTY_HI
	integer*4	NMA$C_PTY_H1
	integer*4	NMA$C_PTY_H2
	integer*4	NMA$C_PTY_H4
	integer*4	NMA$C_PTY_DU1
	integer*4	NMA$C_PTY_DU2
	integer*4	NMA$C_PTY_CD1
	integer*4	NMA$C_PTY_CM2
	integer*4	NMA$C_PTY_CM3
	integer*4	NMA$C_PTY_CM4
	integer*4	NMA$C_PTY_CM5
	integer*4	NMA$C_PCCI_STA
	integer*4	NMA$C_PCCI_SUB
	integer*4	NMA$C_PCCI_SER
	integer*4	NMA$C_PCCI_LCT
	integer*4	NMA$C_PCCI_SPY
	integer*4	NMA$C_PCCI_SSB
	integer*4	NMA$C_PCCI_CNO
	integer*4	NMA$C_PCCI_COB
	integer*4	NMA$C_PCCI_LOO
	integer*4	NMA$C_PCCI_ADJ
	integer*4	NMA$C_PCCI_DRT
	integer*4	NMA$C_PCCI_BLO
	integer*4	NMA$C_PCCI_COS
	integer*4	NMA$C_PCCI_MRT
	integer*4	NMA$C_PCCI_RPR
	integer*4	NMA$C_PCCI_HET
	integer*4	NMA$C_PCCI_LIT
	integer*4	NMA$C_PCCI_BLK
	integer*4	NMA$C_PCCI_MRC
	integer*4	NMA$C_PCCI_RCT
	integer*4	NMA$C_PCCI_NUM
	integer*4	NMA$C_PCCI_USR
	integer*4	NMA$C_PCCI_POL
	integer*4	NMA$C_PCCI_PLS
	integer*4	NMA$C_PCCI_OWN
	integer*4	NMA$C_PCCI_LIN
	integer*4	NMA$C_PCCI_USE
	integer*4	NMA$C_PCCI_TYP
	integer*4	NMA$C_PCCI_DTE
	integer*4	NMA$C_PCCI_CHN
	integer*4	NMA$C_PCCI_MBL
	integer*4	NMA$C_PCCI_MWI
	integer*4	NMA$C_PCCI_TRI
	integer*4	NMA$C_PCCI_BBT
	integer*4	NMA$C_PCCI_TRT
	integer*4	NMA$C_PCCI_RTT
	integer*4	NMA$C_PCCI_MRB
	integer*4	NMA$C_PCCI_MTR
	integer*4	NMA$C_PCCI_ACB
	integer*4	NMA$C_PCCI_ACI
	integer*4	NMA$C_PCCI_IAB
	integer*4	NMA$C_PCCI_IAI
	integer*4	NMA$C_PCCI_IAT
	integer*4	NMA$C_PCCI_DYB
	integer*4	NMA$C_PCCI_DYI
	integer*4	NMA$C_PCCI_DYT
	integer*4	NMA$C_PCCI_DTH
	integer*4	NMA$C_PCCI_RSX_MAC
	integer*4	NMA$C_PCCI_RSX_LOG
	integer*4	NMA$C_PCCI_RSX_DLG
	integer*4	NMA$C_PCCI_RSX_ACT
	integer*4	NMA$C_PCCI_VER
	integer*4	NMA$C_PCCI_XPT
	integer*4	NMA$C_PCCI_MST
	integer*4	NMA$C_PCCI_SRV_LOG
	integer*4	NMA$C_PCCI_SRV_DLG
	integer*4	NMA$C_PCCI_SRV_ACT
	integer*4	NMA$C_PCLI_STA
	integer*4	NMA$C_PCLI_SUB
	integer*4	NMA$C_PCLI_SER
	integer*4	NMA$C_PCLI_LCT
	integer*4	NMA$C_PCLI_LOO
	integer*4	NMA$C_PCLI_ADJ
	integer*4	NMA$C_PCLI_BLO
	integer*4	NMA$C_PCLI_COS
	integer*4	NMA$C_PCLI_DEV
	integer*4	NMA$C_PCLI_BFN
	integer*4	NMA$C_PCLI_CON
	integer*4	NMA$C_PCLI_DUP
	integer*4	NMA$C_PCLI_PRO
	integer*4	NMA$C_PCLI_LTY
	integer*4	NMA$C_PCLI_CLO
	integer*4	NMA$C_PCLI_STI
	integer*4	NMA$C_PCLI_NTI
	integer*4	NMA$C_PCLI_RTT
	integer*4	NMA$C_PCLI_HTI
	integer*4	NMA$C_PCLI_MBL
	integer*4	NMA$C_PCLI_MRT
	integer*4	NMA$C_PCLI_MWI
	integer*4	NMA$C_PCLI_TRI
	integer*4	NMA$C_PCLI_SLT
	integer*4	NMA$C_PCLI_DDT
	integer*4	NMA$C_PCLI_DLT
	integer*4	NMA$C_PCLI_SRT
	integer*4	NMA$C_PCLI_HWA
	integer*4	NMA$C_PCLI_RSX_OWN
	integer*4	NMA$C_PCLI_RSX_CCS
	integer*4	NMA$C_PCLI_RSX_UCS
	integer*4	NMA$C_PCLI_RSX_VEC
	integer*4	NMA$C_PCLI_RSX_PRI
	integer*4	NMA$C_PCLI_RSX_MDE
	integer*4	NMA$C_PCLI_RSX_LLO
	integer*4	NMA$C_PCLI_RSX_LOG
	integer*4	NMA$C_PCLI_RSX_DLG
	integer*4	NMA$C_PCLI_RSX_ACT
	integer*4	NMA$C_PCLI_MCD
	integer*4	NMA$C_PCLI_XMD
	integer*4	NMA$C_PCLI_EPT
	integer*4	NMA$C_PCLI_BUS
	integer*4	NMA$C_PCLI_NMS
	integer*4	NMA$C_PCLI_PHA
	integer*4	NMA$C_PCLI_DPA
	integer*4	NMA$C_PCLI_PTY
	integer*4	NMA$C_PCLI_MCA
	integer*4	NMA$C_PCLI_ILP
	integer*4	NMA$C_PCLI_PRM
	integer*4	NMA$C_PCLI_MLT
	integer*4	NMA$C_PCLI_PAD
	integer*4	NMA$C_PCLI_DCH
	integer*4	NMA$C_PCLI_CRC
	integer*4	NMA$C_PCLI_HBQ
	integer*4	NMA$C_PCLI_ACC
	integer*4	NMA$C_PCLI_EKO
	integer*4	NMA$C_PCLI_BSZ
	integer*4	NMA$C_PCLI_DES
	integer*4	NMA$C_PCLI_RET
	integer*4	NMA$C_PCLI_MOD
	integer*4	NMA$C_PCLI_RIB
	integer*4	NMA$C_PCLI_MNTL
	integer*4	NMA$C_PCLI_INTL0
	integer*4	NMA$C_PCLI_INTL1
	integer*4	NMA$C_PCLI_INTL2
	integer*4	NMA$C_PCLI_INTL3
	integer*4	NMA$C_PCLI_FRA
	integer*4	NMA$C_PCLI_STI1
	integer*4	NMA$C_PCLI_STI2
	integer*4	NMA$C_PCLI_TMO
	integer*4	NMA$C_PCLI_MCL
	integer*4	NMA$C_PCLI_SYC
	integer*4	NMA$C_PCLI_BPC
	integer*4	NMA$C_PCLI_SRV_OWN
	integer*4	NMA$C_PCLI_SRV_UCS
	integer*4	NMA$C_PCLI_SRV_VEC
	integer*4	NMA$C_PCLI_SRV_PRI
	integer*4	NMA$C_PCLI_SRV_LOG
	integer*4	NMA$C_PCLI_SRV_DLG
	integer*4	NMA$C_PCLI_SRV_ACT
	integer*4	NMA$C_PCCO_RTR
	integer*4	NMA$C_PCLD_ASS
	integer*4	NMA$C_PCLP_ASS
	integer*4	NMA$C_PCCN_CIR
	integer*4	NMA$C_PCCN_SUR
	integer*4	NMA$C_PCCN_ELT
	integer*4	NMA$C_PCCN_PHA
	integer*4	NMA$C_PCCN_LRP
	integer*4	NMA$C_PCCN_MVR
	integer*4	NMA$C_PCCN_FCT
	integer*4	NMA$C_PCCN_CUS
	integer*4	NMA$C_PCCN_RTR
	integer*4	NMA$C_PCCN_CSZ
	integer*4	NMA$C_PCCN_RSZ
	integer*4	NMA$C_PCCN_HWA
	integer*4	NMA$C_PCCN_DTY
	integer*4	NMA$C_PCCN_SFI
	integer*4	NMA$C_PCCN_SPR
	integer*4	NMA$C_PCCN_DLK
	integer*4	NMA$C_PCLO_STA
	integer*4	NMA$C_PCLO_LNA
	integer*4	NMA$C_PCLO_SIN
	integer*4	NMA$C_PCLO_EVE
	integer*4	NMA$C_PCXA_NOD
	integer*4	NMA$C_PCXA_USR
	integer*4	NMA$C_PCXA_PSW
	integer*4	NMA$C_PCXA_ACC
	integer*4	NMA$C_PCXA_NET
	integer*4	NMA$C_PCXA_RSX_ADS
	integer*4	NMA$C_PCXA_RSX_ANB
	integer*4	NMA$C_PCXA_RSX_ASC
	integer*4	NMA$C_PCXA_SRV_ADS
	integer*4	NMA$C_PCXA_SRV_ANB
	integer*4	NMA$C_PCXA_SRV_ASC
	integer*4	NMA$C_PCXP_STA
	integer*4	NMA$C_PCXP_CTM
	integer*4	NMA$C_PCXP_ACH
	integer*4	NMA$C_PCXP_ASW
	integer*4	NMA$C_PCXP_DTE
	integer*4	NMA$C_PCXP_GRP
	integer*4	NMA$C_PCXP_NET
	integer*4	NMA$C_PCXP_LIN
	integer*4	NMA$C_PCXP_CHN
	integer*4	NMA$C_PCXP_MCH
	integer*4	NMA$C_PCXP_DBL
	integer*4	NMA$C_PCXP_DWI
	integer*4	NMA$C_PCXP_MBL
	integer*4	NMA$C_PCXP_MWI
	integer*4	NMA$C_PCXP_MCL
	integer*4	NMA$C_PCXP_MRS
	integer*4	NMA$C_PCXP_MST
	integer*4	NMA$C_PCXP_CAT
	integer*4	NMA$C_PCXP_CLT
	integer*4	NMA$C_PCXP_RST
	integer*4	NMA$C_PCXP_STT
	integer*4	NMA$C_PCXP_GDT
	integer*4	NMA$C_PCXP_GNM
	integer*4	NMA$C_PCXP_GTY
	integer*4	NMA$C_PCXP_RSX_PMC
	integer*4	NMA$C_PCXP_MNS
	integer*4	NMA$C_PCXP_MCI
	integer*4	NMA$C_PCXP_SBS
	integer*4	NMA$C_PCXP_SRV_PMC
	integer*4	NMA$C_PCXS_CTM
	integer*4	NMA$C_PCXS_ACI
	integer*4	NMA$C_PCXS_DST
	integer*4	NMA$C_PCXS_MCI
	integer*4	NMA$C_PCXS_NOD
	integer*4	NMA$C_PCXS_USR
	integer*4	NMA$C_PCXS_SPW
	integer*4	NMA$C_PCXS_RPW
	integer*4	NMA$C_PCXS_ACC
	integer*4	NMA$C_PCXS_OBJ
	integer*4	NMA$C_PCXS_PRI
	integer*4	NMA$C_PCXS_CMK
	integer*4	NMA$C_PCXS_CVL
	integer*4	NMA$C_PCXS_GRP
	integer*4	NMA$C_PCXS_NUM
	integer*4	NMA$C_PCXS_SAD
	integer*4	NMA$C_PCXS_RSX_5ST
	integer*4	NMA$C_PCXS_STA
	integer*4	NMA$C_PCXS_FIL
	integer*4	NMA$C_PCXS_SRV_5ST
	integer*4	NMA$C_PCXT_STA
	integer*4	NMA$C_PCXT_BSZ
	integer*4	NMA$C_PCXT_MBK
	integer*4	NMA$C_PCXT_FNM
	integer*4	NMA$C_PCXT_MBF
	integer*4	NMA$C_PCXT_CPL
	integer*4	NMA$C_PCXT_MVR
	integer*4	NMA$C_PCXT_TPT
	integer*4	NMA$C_PCXT_CPS
	integer*4	NMA$C_PCXT_TST
	integer*4	NMA$C_PCNO_STA
	integer*4	NMA$C_PCNO_PHA
	integer*4	NMA$C_PCNO_IDE
	integer*4	NMA$C_PCNO_MVE
	integer*4	NMA$C_PCNO_SLI
	integer*4	NMA$C_PCNO_SPA
	integer*4	NMA$C_PCNO_SDV
	integer*4	NMA$C_PCNO_CPU
	integer*4	NMA$C_PCNO_HWA
	integer*4	NMA$C_PCNO_SNV
	integer*4	NMA$C_PCNO_LOA
	integer*4	NMA$C_PCNO_SLO
	integer*4	NMA$C_PCNO_TLO
	integer*4	NMA$C_PCNO_DFL
	integer*4	NMA$C_PCNO_STY
	integer*4	NMA$C_PCNO_SID
	integer*4	NMA$C_PCNO_DUM
	integer*4	NMA$C_PCNO_SDU
	integer*4	NMA$C_PCNO_DAD
	integer*4	NMA$C_PCNO_DCT
	integer*4	NMA$C_PCNO_OHO
	integer*4	NMA$C_PCNO_IHO
	integer*4	NMA$C_PCNO_LPC
	integer*4	NMA$C_PCNO_LPL
	integer*4	NMA$C_PCNO_LPD
	integer*4	NMA$C_PCNO_LPA
	integer*4	NMA$C_PCNO_LPH
	integer*4	NMA$C_PCNO_LPN
	integer*4	NMA$C_PCNO_LAN
	integer*4	NMA$C_PCNO_CTI
	integer*4	NMA$C_PCNO_NNA
	integer*4	NMA$C_PCNO_NLI
	integer*4	NMA$C_PCNO_ADD
	integer*4	NMA$C_PCNO_ITI
	integer*4	NMA$C_PCNO_OTI
	integer*4	NMA$C_PCNO_ACL
	integer*4	NMA$C_PCNO_DEL
	integer*4	NMA$C_PCNO_NVE
	integer*4	NMA$C_PCNO_MLK
	integer*4	NMA$C_PCNO_DFA
	integer*4	NMA$C_PCNO_DWE
	integer*4	NMA$C_PCNO_IAT
	integer*4	NMA$C_PCNO_RFA
	integer*4	NMA$C_PCNO_DTY
	integer*4	NMA$C_PCNO_DCO
	integer*4	NMA$C_PCNO_DHO
	integer*4	NMA$C_PCNO_DLI
	integer*4	NMA$C_PCNO_NND
	integer*4	NMA$C_PCNO_RVE
	integer*4	NMA$C_PCNO_ETY
	integer*4	NMA$C_PCNO_RTI
	integer*4	NMA$C_PCNO_SAD
	integer*4	NMA$C_PCNO_BRT
	integer*4	NMA$C_PCNO_MAD
	integer*4	NMA$C_PCNO_MLN
	integer*4	NMA$C_PCNO_MCO
	integer*4	NMA$C_PCNO_MHO
	integer*4	NMA$C_PCNO_MVI
	integer*4	NMA$C_PCNO_MAR
	integer*4	NMA$C_PCNO_MBE
	integer*4	NMA$C_PCNO_MBR
	integer*4	NMA$C_PCNO_AMC
	integer*4	NMA$C_PCNO_AMH
	integer*4	NMA$C_PCNO_MBU
	integer*4	NMA$C_PCNO_BUS
	integer*4	NMA$C_PCNO_SBS
	integer*4	NMA$C_PCNO_FBS
	integer*4	NMA$C_PCNO_RSX_RPA
	integer*4	NMA$C_PCNO_RSX_TPA
	integer*4	NMA$C_PCNO_RSX_VER
	integer*4	NMA$C_PCNO_PUS
	integer*4	NMA$C_PCNO_PAC
	integer*4	NMA$C_PCNO_PPW
	integer*4	NMA$C_PCNO_NUS
	integer*4	NMA$C_PCNO_NAC
	integer*4	NMA$C_PCNO_NPW
	integer*4	NMA$C_PCNO_RPA
	integer*4	NMA$C_PCNO_TPA
	integer*4	NMA$C_PCNO_ACC
	integer*4	NMA$C_PCNO_DAC
	integer*4	NMA$C_PCNO_PIQ
	integer*4	NMA$C_PCNO_ALI
	integer*4	NMA$C_PCNO_PRX
	integer*4	NMA$C_PCNO_DPX
	integer*4	NMA$C_PCNO_SRV_RPA
	integer*4	NMA$C_PCNO_SRV_TPA
	integer*4	NMA$C_PCNO_SRV_VER
	integer*4	NMA$C_PCNO_SRV_ACB
	integer*4	NMA$C_PCNO_SRV_ASB
	integer*4	NMA$C_PCNO_SRV_ALB
	integer*4	NMA$C_PCNO_SRV_MCB
	integer*4	NMA$C_PCNO_SRV_MSB
	integer*4	NMA$C_PCNO_SRV_MLB
	integer*4	NMA$C_PCNO_SRV_LBS
	integer*4	NMA$C_PCNO_SRV_NRB
	integer*4	NMA$C_PCNO_SRV_CPT
	integer*4	NMA$C_PCNO_SRV_CPF
	integer*4	NMA$C_PCNO_SRV_CPL
	integer*4	NMA$C_PCNO_SRV_XPT
	integer*4	NMA$C_PCNO_SRV_XPF
	integer*4	NMA$C_PCNO_SRV_XPL
	integer*4	NMA$C_PCAR_STA
	integer*4	NMA$C_PCAR_COS
	integer*4	NMA$C_PCAR_HOP
	integer*4	NMA$C_PCAR_CIR
	integer*4	NMA$C_PCAR_NND
	integer*4	NMA$C_PCOB_OAN
	integer*4	NMA$C_PCOB_OAC
	integer*4	NMA$C_PCOB_ONA
	integer*4	NMA$C_PCOB_OCO
	integer*4	NMA$C_PCOB_OUS
	integer*4	NMA$C_PCOB_OVE
	integer*4	NMA$C_PCOB_NAM
	integer*4	NMA$C_PCOB_NUM
	integer*4	NMA$C_PCOB_FID
	integer*4	NMA$C_PCOB_PID
	integer*4	NMA$C_PCOB_PRV
	integer*4	NMA$C_PCOB_USR
	integer*4	NMA$C_PCOB_ACC
	integer*4	NMA$C_PCOB_PSW
	integer*4	NMA$C_PCOB_PRX
	integer*4	NMA$C_PCLK_STA
	integer*4	NMA$C_PCLK_PID
	integer*4	NMA$C_PCLK_NID
	integer*4	NMA$C_PCLK_LAD
	integer*4	NMA$C_PCLK_DLY
	integer*4	NMA$C_PCLK_RLN
	integer*4	NMA$C_PCLK_RID
	integer*4	NMA$C_PCLK_USR
	integer*4	NMA$C_PCLK_PRC
	integer*4	NMA$C_CTCIR_ZER
	integer*4	NMA$C_CTCIR_APR
	integer*4	NMA$C_CTCIR_DPS
	integer*4	NMA$C_CTCIR_ACL
	integer*4	NMA$C_CTCIR_CRL
	integer*4	NMA$C_CTCIR_TPR
	integer*4	NMA$C_CTCIR_TPS
	integer*4	NMA$C_CTCIR_TCL
	integer*4	NMA$C_CTCIR_LDN
	integer*4	NMA$C_CTCIR_IFL
	integer*4	NMA$C_CTCIR_BRC
	integer*4	NMA$C_CTCIR_BSN
	integer*4	NMA$C_CTCIR_MBY
	integer*4	NMA$C_CTCIR_DBR
	integer*4	NMA$C_CTCIR_DBS
	integer*4	NMA$C_CTCIR_DEI
	integer*4	NMA$C_CTCIR_DEO
	integer*4	NMA$C_CTCIR_RRT
	integer*4	NMA$C_CTCIR_LRT
	integer*4	NMA$C_CTCIR_RBE
	integer*4	NMA$C_CTCIR_LBE
	integer*4	NMA$C_CTCIR_SIE
	integer*4	NMA$C_CTCIR_SLT
	integer*4	NMA$C_CTCIR_UBU
	integer*4	NMA$C_CTCIR_RPE
	integer*4	NMA$C_CTCIR_LPE
	integer*4	NMA$C_CTCIR_LIR
	integer*4	NMA$C_CTCIR_RIR
	integer*4	NMA$C_CTCIR_NIR
	integer*4	NMA$C_CTCIR_MNE
	integer*4	NMA$C_CTCIR_ERI
	integer*4	NMA$C_CTCIR_ERO
	integer*4	NMA$C_CTCIR_RTO
	integer*4	NMA$C_CTCIR_LTO
	integer*4	NMA$C_CTCIR_BER
	integer*4	NMA$C_CTCIR_BEL
	integer*4	NMA$C_CTLIN_ZER
	integer*4	NMA$C_CTLIN_APR
	integer*4	NMA$C_CTLIN_DPS
	integer*4	NMA$C_CTLIN_ACL
	integer*4	NMA$C_CTLIN_TPR
	integer*4	NMA$C_CTLIN_TPS
	integer*4	NMA$C_CTLIN_TCL
	integer*4	NMA$C_CTLIN_LDN
	integer*4	NMA$C_CTLIN_IFL
	integer*4	NMA$C_CTLIN_BRC
	integer*4	NMA$C_CTLIN_BSN
	integer*4	NMA$C_CTLIN_MBY
	integer*4	NMA$C_CTLIN_DBR
	integer*4	NMA$C_CTLIN_DBS
	integer*4	NMA$C_CTLIN_MBL
	integer*4	NMA$C_CTLIN_BID
	integer*4	NMA$C_CTLIN_BS1
	integer*4	NMA$C_CTLIN_BSM
	integer*4	NMA$C_CTLIN_DEI
	integer*4	NMA$C_CTLIN_DEO
	integer*4	NMA$C_CTLIN_RRT
	integer*4	NMA$C_CTLIN_LRT
	integer*4	NMA$C_CTLIN_RBE
	integer*4	NMA$C_CTLIN_LBE
	integer*4	NMA$C_CTLIN_SIE
	integer*4	NMA$C_CTLIN_SLT
	integer*4	NMA$C_CTLIN_SFL
	integer*4	NMA$C_CTLIN_CDC
	integer*4	NMA$C_CTLIN_RFL
	integer*4	NMA$C_CTLIN_UFD
	integer*4	NMA$C_CTLIN_OVR
	integer*4	NMA$C_CTLIN_SBU
	integer*4	NMA$C_CTLIN_UBU
	integer*4	NMA$C_CTLIN_RPE
	integer*4	NMA$C_CTLIN_LPE
	integer*4	NMA$W_NODE
	integer*4	NMA$S_ADDR
	integer*4	NMA$V_ADDR
	integer*4	NMA$S_AREA
	integer*4	NMA$V_AREA
	integer*4	NMA$S_PTY_TYP
	integer*4	NMA$V_PTY_TYP
	integer*4	NMA$S_PTY_CLE
	integer*4	NMA$V_PTY_CLE
	integer*4	NMA$V_PTY_MUL
	integer*4	NMA$V_PTY_COD
	integer*4	NMA$S_PTY_CMU
	integer*4	NMA$V_PTY_CMU
	integer*4	NMA$S_PTY_NLE
	integer*4	NMA$V_PTY_NLE
	integer*4	NMA$S_PTY_NTY
	integer*4	NMA$V_PTY_NTY
	integer*4	NMA$V_PTY_ASC
	integer*4	NMA$M_CTLIN_BTL
	integer*4	NMA$M_CTLIN_FCS
	integer*4	NMA$M_CTLIN_TRJ
	integer*4	NMA$V_CTLIN_BTL
	integer*4	NMA$V_CTLIN_FCS
	integer*4	NMA$V_CTLIN_TRJ
	integer*4	NMA$M_CTLIN_RRJ
	integer*4	NMA$V_CTLIN_RRJ
	integer*4	NMA$M_CTLIN_RRN
	integer*4	NMA$V_CTLIN_RRN
	integer*4	NMA$M_CTLIN_TRN
	integer*4	NMA$V_CTLIN_TRN
	integer*4	NMA$M_CTLIN_INR
	integer*4	NMA$M_CTLIN_FMS
	integer*4	NMA$V_CTLIN_INR
	integer*4	NMA$V_CTLIN_FMS
	integer*4	NMA$M_CTLIN_TUN
	integer*4	NMA$M_CTLIN_RUN
	integer*4	NMA$M_CTLIN_FMR
	integer*4	NMA$C_CTLIN_MBS
	integer*4	NMA$C_CTLIN_MSN
	integer*4	NMA$C_CTLIN_RME
	integer*4	NMA$C_CTLIN_LCE
	integer*4	NMA$C_CTLIN_MSE
	integer*4	NMA$C_CTNOD_ZER
	integer*4	NMA$C_CTNOD_BRC
	integer*4	NMA$C_CTNOD_BSN
	integer*4	NMA$C_CTNOD_MRC
	integer*4	NMA$C_CTNOD_MSN
	integer*4	NMA$C_CTNOD_CRC
	integer*4	NMA$C_CTNOD_CSN
	integer*4	NMA$C_CTNOD_RTO
	integer*4	NMA$C_CTNOD_RSE
	integer*4	NMA$C_CTNOD_MLL
	integer*4	NMA$C_CTNOD_APL
	integer*4	NMA$C_CTNOD_NUL
	integer*4	NMA$C_CTNOD_NOL
	integer*4	NMA$C_CTNOD_OPL
	integer*4	NMA$C_CTNOD_PFE
	integer*4	NMA$C_CTNOD_RUL
	integer*4	NMA$C_CTNOD_VER
	integer*4	NMA$C_CTNOD_SRV_SYC
	integer*4	NMA$C_CTNOD_SRV_SYS
	integer*4	NMA$C_CTNOD_SRV_SYL
	integer*4	NMA$C_CTNOD_SRV_SYR
	integer*4	NMA$C_CTXP_ZER
	integer*4	NMA$C_CTXP_BRC
	integer*4	NMA$C_CTXP_BSN
	integer*4	NMA$C_CTXP_BLR
	integer*4	NMA$C_CTXP_BLS
	integer*4	NMA$C_CTXP_CRC
	integer*4	NMA$C_CTXP_CSN
	integer*4	NMA$C_CTXP_FSR
	integer*4	NMA$C_CTXP_FSS
	integer*4	NMA$C_CTXP_MSA
	integer*4	NMA$C_CTXP_MCA
	integer*4	NMA$C_CTXP_RSE
	integer*4	NMA$C_CTXP_LIR
	integer*4	NMA$C_CTXP_RIR
	integer*4	NMA$C_CTXP_NIR
	integer*4	NMA$C_CTXP_RST
	integer*4	NMA$C_CTXS_ZER
	integer*4	NMA$C_CTXS_MCA
	integer*4	NMA$C_CTXS_ICR
	integer*4	NMA$C_CTXS_LLR
	integer*4	NMA$C_LOOP_MIX
	integer*4	NMA$C_LOOP_ONE
	integer*4	NMA$C_LOOP_ZER
	integer*4	NMA$C_LOOP_DCNT
	integer*4	NMA$C_LOOP_DSIZ
	integer*4	NMA$C_LOOP_XMIT
	integer*4	NMA$C_LOOP_RECV
	integer*4	NMA$C_LOOP_FULL
	integer*4	NMA$C_STATE_ON
	integer*4	NMA$C_STATE_OFF
	integer*4	NMA$C_STATE_SER
	integer*4	NMA$C_STATE_CLE
	integer*4	NMA$C_STATE_HOL
	integer*4	NMA$C_STATE_SHU
	integer*4	NMA$C_STATE_RES
	integer*4	NMA$C_STATE_REA
	integer*4	NMA$C_STATE_UNR
	integer*4	NMA$C_ASS_ENA
	integer*4	NMA$C_ASS_DIS
	integer*4	NMA$C_SUR_ENA
	integer*4	NMA$C_SUR_DIS
	integer*4	NMA$C_LINSS_STA
	integer*4	NMA$C_LINSS_REF
	integer*4	NMA$C_LINSS_LOO
	integer*4	NMA$C_LINSS_LOA
	integer*4	NMA$C_LINSS_DUM
	integer*4	NMA$C_LINSS_TRI
	integer*4	NMA$C_LINSS_ASE
	integer*4	NMA$C_LINSS_ALO
	integer*4	NMA$C_LINSS_ADU
	integer*4	NMA$C_LINSS_ATR
	integer*4	NMA$C_LINSS_SYN
	integer*4	NMA$C_LINSS_FAI
	integer*4	NMA$C_LINSS_RUN
	integer*4	NMA$C_LINSS_UNS
	integer*4	NMA$C_LINSS_IDL
	integer*4	NMA$C_CIRTY_POI
	integer*4	NMA$C_CIRTY_CON
	integer*4	NMA$C_CIRTY_TRI
	integer*4	NMA$C_CIRTY_X25
	integer*4	NMA$C_CIRTY_DMC
	integer*4	NMA$C_CIRTY_NI
	integer*4	NMA$C_LINSV_ENA
	integer*4	NMA$C_LINSV_DIS
	integer*4	NMA$C_CIRPST_AUT
	integer*4	NMA$C_CIRPST_ACT
	integer*4	NMA$C_CIRPST_INA
	integer*4	NMA$C_CIRPST_DIE
	integer*4	NMA$C_CIRPST_DED
	integer*4	NMA$C_CIRBLK_ENA
	integer*4	NMA$C_CIRBLK_DIS
	integer*4	NMA$C_CIRUS_PER
	integer*4	NMA$C_CIRUS_INC
	integer*4	NMA$C_CIRUS_OUT
	integer*4	NMA$C_CIRBF_UNL
	integer*4	NMA$C_CIRVE_ENA
	integer*4	NMA$C_CIRVE_DIS
	integer*4	NMA$C_CIRXPT_ZND
	integer*4	NMA$C_CIRXPT_PH2
	integer*4	NMA$C_CIRXPT_PH3
	integer*4	NMA$C_CIRXPT_RO3
	integer*4	NMA$C_CIRXPT_NR4
	integer*4	NMA$C_DPX_FUL
	integer*4	NMA$C_DPX_HAL
	integer*4	NMA$C_LINCN_NOR
	integer*4	NMA$C_LINCN_LOO
	integer*4	NMA$C_LINPR_POI
	integer*4	NMA$C_LINPR_CON
	integer*4	NMA$C_LINPR_TRI
	integer*4	NMA$C_LINPR_DMC
	integer*4	NMA$C_LINPR_LAPB
	integer*4	NMA$C_LINPR_NI
	integer*4	NMA$C_LINPR_BSY
	integer*4	NMA$C_LINPR_MAS
	integer*4	NMA$C_LINPR_NEU
	integer*4	NMA$C_LINPR_SEC
	integer*4	NMA$C_LINCL_EXT
	integer*4	NMA$C_LINCL_INT
	integer*4	NMA$C_LINTY_POI
	integer*4	NMA$C_LINTY_CON
	integer*4	NMA$C_LINTY_TRI
	integer*4	NMA$C_LINTY_DMC
	integer*4	NMA$C_LINMC_SET
	integer*4	NMA$C_LINMC_CLR
	integer*4	NMA$C_LINMC_CAL
	integer*4	NMA$C_LINMC_SDF
	integer*4	NMA$C_ACC_SHR
	integer*4	NMA$C_ACC_LIM
	integer*4	NMA$C_ACC_EXC
	integer*4	NMA$C_LINMO_AUT
	integer*4	NMA$C_LINMO_SIL
	integer*4	NMA$C_X25MD_DTE
	integer*4	NMA$C_X25MD_DCE
	integer*4	NMA$C_X25MD_DTL
	integer*4	NMA$C_X25MD_DCL
	integer*4	NMA$C_NODTY_ROU
	integer*4	NMA$C_NODTY_NON
	integer*4	NMA$C_NODTY_PHA
	integer*4	NMA$C_NODTY_AREA
	integer*4	NMA$C_NODTY_RT4
	integer*4	NMA$C_NODTY_NR4
	integer*4	NMA$C_NODPW_SET
	integer*4	NMA$C_CPU_8
	integer*4	NMA$C_CPU_11
	integer*4	NMA$C_CPU_1020
	integer*4	NMA$C_CPU_VAX
	integer*4	NMA$C_NODSNV_PH3
	integer*4	NMA$C_NODSNV_PH4
	integer*4	NMA$C_SOFT_SECL
	integer*4	NMA$C_SOFT_TERL
	integer*4	NMA$C_SOFT_OSYS
	integer*4	NMA$C_SOFT_DIAG
	integer*4	NMA$C_ACES_NONE
	integer*4	NMA$C_ACES_INCO
	integer*4	NMA$C_ACES_OUTG
	integer*4	NMA$C_ACES_BOTH
	integer*4	NMA$C_ACES_REQU
	integer*4	NMA$C_XPRTY_BIL
	integer*4	NMA$C_XPRST_ON
	integer*4	NMA$C_XPRST_OFF
	integer*4	NMA$C_XPRST_SHU
	integer*4	NMA$C_XPRMN_ENA
	integer*4	NMA$C_XPRMN_DIS
	integer*4	NMA$C_XPRSB_RUN
	integer*4	NMA$C_XPRSB_UNS
	integer*4	NMA$C_XPRSB_SYN
	integer*4	NMA$C_JAN
	integer*4	NMA$C_FEB
	integer*4	NMA$C_MAR
	integer*4	NMA$C_APR
	integer*4	NMA$C_MAY
	integer*4	NMA$C_JUN
	integer*4	NMA$C_JUL
	integer*4	NMA$C_AUG
	integer*4	NMA$C_SEP
	integer*4	NMA$C_OCT
	integer*4	NMA$C_NOV
	integer*4	NMA$C_DEC
	integer*4	NMA$C_SOFD_DP
	integer*4	NMA$C_SOFD_UNA
	integer*4	NMA$C_SOFD_DU
	integer*4	NMA$C_SOFD_DL
	integer*4	NMA$C_SOFD_DQ
	integer*4	NMA$C_SOFD_DA
	integer*4	NMA$C_SOFD_DUP
	integer*4	NMA$C_SOFD_DMC
	integer*4	NMA$C_SOFD_DMP
	integer*4	NMA$C_SOFD_DTE
	integer*4	NMA$C_SOFD_KL8
	integer*4	NMA$C_SOFD_DMV
	integer*4	NMA$C_SOFD_DPV
	integer*4	NMA$C_SOFD_DMF
	integer*4	NMA$_SUCCESS
	integer*4	NMA$_SUCCFLDRPL
	integer*4	NMA$_BADFID
	integer*4	NMA$_BADDAT
	integer*4	NMA$_BADOPR
	integer*4	NMA$_BUFTOOSMALL
	integer*4	NMA$_FLDNOTFND
	integer*4	NMA$C_OPN_MIN
	integer*4	NMA$C_OPN_NODE
	integer*4	NMA$C_OPN_LINE
	integer*4	NMA$C_OPN_LOG
	integer*4	NMA$C_OPN_OBJ
	integer*4	NMA$C_OPN_CIR
	integer*4	NMA$C_OPN_X25
	integer*4	NMA$C_OPN_X29
	integer*4	NMA$C_OPN_CNF
	integer*4	NMA$C_OPN_MAX
	integer*4	NMA$C_OPN_ALL
	integer*4	NMA$C_OPN_AC_RO
	integer*4	NMA$C_OPN_AC_RW
	integer*4	NMA$C_FN2_DLL
	integer*4	NMA$C_FN2_ULD
	integer*4	NMA$C_FN2_TRI
	integer*4	NMA$C_FN2_LOO
	integer*4	NMA$C_FN2_TES
	integer*4	NMA$C_FN2_SET
	integer*4	NMA$C_FN2_REA
	integer*4	NMA$C_FN2_ZER
	integer*4	NMA$C_FN2_LNS
	integer*4	NMA$C_OP2_CHNST
	integer*4	NMA$C_OP2_CHLST
	integer*4	NMA$C_OP2_RENCT
	integer*4	NMA$C_OP2_RENST
	integer*4	NMA$C_OP2_RELCT
	integer*4	NMA$C_OP2_RELST
	integer*4	NMA$C_OP2_ZENCT
	integer*4	NMA$C_OP2_ZELCT
	integer*4	NMA$C_EN2_KNO
	integer*4	NMA$C_EN2_LID
	integer*4	NMA$C_EN2_LCN
	integer*4	NMA$C_STS_SUC
	integer*4	NMA$C_STS_MOR
	integer*4	NMA$C_STS_PAR
	integer*4	NMA$C_STS_DON
	integer*4	NMA$C_STS_FUN
	integer*4	NMA$C_STS_INV
	integer*4	NMA$C_STS_PRI
	integer*4	NMA$C_STS_SIZ
	integer*4	NMA$C_STS_MPR
	integer*4	NMA$C_STS_PTY
	integer*4	NMA$C_STS_MVE
	integer*4	NMA$C_STS_CMP
	integer*4	NMA$C_STS_IDE
	integer*4	NMA$C_STS_LCO
	integer*4	NMA$C_STS_STA
	integer*4	NMA$C_STS_FOP
	integer*4	NMA$C_STS_FCO
	integer*4	NMA$C_STS_RES
	integer*4	NMA$C_STS_PVA
	integer*4	NMA$C_STS_LPR
	integer*4	NMA$C_STS_FIO
	integer*4	NMA$C_STS_MLD
	integer*4	NMA$C_STS_ROO
	integer*4	NMA$C_STS_MCF
	integer*4	NMA$C_STS_PNA
	integer*4	NMA$C_STS_PLO
	integer*4	NMA$C_STS_HAR
	integer*4	NMA$C_STS_OPE
	integer*4	NMA$C_STS_SYS
	integer*4	NMA$C_STS_PGP
	integer*4	NMA$C_STS_BLR
	integer*4	NMA$C_STS_PMS
	integer*4	NMA$C_STS_ALI
	integer*4	NMA$C_STS_OBJ
	integer*4	NMA$C_STS_PRO
	integer*4	NMA$C_STS_LNK
	integer*4	NMA$C_FOPDTL_PDB
	integer*4	NMA$C_FOPDTL_LFL
	integer*4	NMA$C_FOPDTL_DFL
	integer*4	NMA$C_FOPDTL_SLF
	integer*4	NMA$C_FOPDTL_TLF
	integer*4	NMA$C_FOPDTL_SDF
	integer*4	NMA$C_NCEDTL_NNA
	integer*4	NMA$C_NCEDTL_INN
	integer*4	NMA$C_NCEDTL_UNA
	integer*4	NMA$C_NCEDTL_UNR
	integer*4	NMA$C_NCEDTL_RSC
	integer*4	NMA$C_NCEDTL_RJC
	integer*4	NMA$C_NCEDTL_ONA
	integer*4	NMA$C_NCEDTL_OBJ
	integer*4	NMA$C_NCEDTL_ACC
	integer*4	NMA$C_NCEDTL_BSY
	integer*4	NMA$C_NCEDTL_NRS
	integer*4	NMA$C_NCEDTL_NSD
	integer*4	NMA$C_NCEDTL_DIE
	integer*4	NMA$C_NCEDTL_DIS
	integer*4	NMA$C_NCEDTL_ABO
	integer*4	NMA$C_NCEDTL_ABM
	integer*4	NMA$C_OPEDTL_DCH
	integer*4	NMA$C_OPEDTL_TIM
	integer*4	NMA$C_OPEDTL_ORN
	integer*4	NMA$C_OPEDTL_ACT
	integer*4	NMA$C_OPEDTL_BAF
	integer*4	NMA$C_OPEDTL_RUN
	integer*4	NMA$C_OPEDTL_DSC
	integer*4	NMA$C_OPEDTL_FTL
	integer*4	NMA$C_OPEDTL_MNT
	integer*4	NMA$C_OPEDTL_LST
	integer*4	NMA$C_OPEDTL_THR
	integer*4	NMA$C_OPEDTL_TRB
	integer*4	NMA$C_OPEDTL_STA
	integer*4	NMA$V_CTLIN_TUN
	integer*4	NMA$V_CTLIN_RUN
	integer*4	NMA$V_CTLIN_FMR
	parameter	(NMA$C_OBJ_NIC = 19)
	parameter	(NMA$C_FNC_LOA = 15)
	parameter	(NMA$C_FNC_DUM = 16)
	parameter	(NMA$C_FNC_TRI = 17)
	parameter	(NMA$C_FNC_TES = 18)
	parameter	(NMA$C_FNC_CHA = 19)
	parameter	(NMA$C_FNC_REA = 20)
	parameter	(NMA$C_FNC_ZER = 21)
	parameter	(NMA$C_FNC_SYS = 22)
	parameter	(NMA$M_OPT_ENT = 7)
	parameter	(NMA$M_OPT_CLE = 64)
	parameter	(NMA$M_OPT_PER = 128)
	parameter	(NMA$M_OPT_INF = 112)
	parameter	(NMA$C_OPINF_SUM = 0)
	parameter	(NMA$C_OPINF_STA = 1)
	parameter	(NMA$C_OPINF_CHA = 2)
	parameter	(NMA$C_OPINF_COU = 3)
	parameter	(NMA$C_OPINF_EVE = 4)
	parameter	(NMA$M_OPT_ACC = 128)
	parameter	(NMA$M_OPT_REA = 128)
	parameter	(NMA$C_SYS_RST = 1)
	parameter	(NMA$C_SYS_RSX = 2)
	parameter	(NMA$C_SYS_TOP = 3)
	parameter	(NMA$C_SYS_VMS = 4)
	parameter	(NMA$C_SYS_RT = 5)
	parameter	(NMA$C_ENT_NOD = 0)
	parameter	(NMA$C_ENT_LIN = 1)
	parameter	(NMA$C_ENT_LOG = 2)
	parameter	(NMA$C_ENT_CIR = 3)
	parameter	(NMA$C_ENT_MOD = 4)
	parameter	(NMA$C_ENT_ARE = 5)
	parameter	(NMA$C_SENT_ALI = 3)
	parameter	(NMA$C_SENT_OBJ = 4)
	parameter	(NMA$C_SENT_PRO = 5)
	parameter	(NMA$C_SENT_SYS = 6)
	parameter	(NMA$C_SENT_LNK = 7)
	parameter	(NMA$M_ENT_EXE = 128)
	parameter	(NMA$C_ENT_ADJ = -4)
	parameter	(NMA$C_ENT_ACT = -2)
	parameter	(NMA$C_ENT_KNO = -1)
	parameter	(NMA$C_ENT_ADD = 0)
	parameter	(NMA$C_ENT_ALL = -3)
	parameter	(NMA$C_ENT_LOO = -3)
	parameter	(NMA$C_SNK_CON = 1)
	parameter	(NMA$C_SNK_FIL = 2)
	parameter	(NMA$C_SNK_MON = 3)
	parameter	(NMA$M_CNT_TYP = 4095)
	parameter	(NMA$M_CNT_MAP = 4096)
	parameter	(NMA$M_CNT_WID = 24576)
	parameter	(NMA$M_CNT_COU = 32768)
	parameter	(NMA$M_CNT_WIL = 8192)
	parameter	(NMA$M_CNT_WIH = 16384)
	parameter	(NMA$S_OPT_ENT = 3)
	parameter	(NMA$V_OPT_ENT = 0)
	parameter	(NMA$V_OPT_CLE = 6)
	parameter	(NMA$V_OPT_PER = 7)
	parameter	(NMA$S_OPT_INF = 3)
	parameter	(NMA$V_OPT_INF = 4)
	parameter	(NMA$V_OPT_ACC = 7)
	parameter	(NMA$V_OPT_REA = 7)
	parameter	(NMA$V_ENT_EXE = 7)
	parameter	(NMA$S_CNT_TYP = 12)
	parameter	(NMA$V_CNT_TYP = 0)
	parameter	(NMA$V_CNT_MAP = 12)
	parameter	(NMA$S_CNT_WID = 2)
	parameter	(NMA$V_CNT_WID = 13)
	parameter	(NMA$V_CNT_COU = 15)
	parameter	(NMA$V_CNT_WIL = 13)
	parameter	(NMA$V_CNT_WIH = 14)
	parameter	(NMA$M_PTY_TYP = 32767)
	parameter	(NMA$C_PTY_MAX = 15)
	parameter	(NMA$M_PTY_CLE = 63)
	parameter	(NMA$M_PTY_MUL = 64)
	parameter	(NMA$M_PTY_COD = 128)
	parameter	(NMA$M_PTY_CMU = 192)
	parameter	(NMA$M_PTY_NLE = 15)
	parameter	(NMA$M_PTY_NTY = 48)
	parameter	(NMA$M_PTY_ASC = 64)
	parameter	(NMA$C_NTY_DU = 0)
	parameter	(NMA$C_NTY_DS = 1)
	parameter	(NMA$C_NTY_H = 2)
	parameter	(NMA$C_NTY_O = 3)
	parameter	(NMA$C_NLE_IMAGE = 0)
	parameter	(NMA$C_NLE_BYTE = 1)
	parameter	(NMA$C_NLE_WORD = 2)
	parameter	(NMA$C_NLE_LONG = 4)
	parameter	(NMA$C_NLE_QUAD = 8)
	parameter	(NMA$C_PTY_AI = 64)
	parameter	(NMA$C_PTY_HI = 32)
	parameter	(NMA$C_PTY_H1 = 33)
	parameter	(NMA$C_PTY_H2 = 34)
	parameter	(NMA$C_PTY_H4 = 36)
	parameter	(NMA$C_PTY_DU1 = 1)
	parameter	(NMA$C_PTY_DU2 = 2)
	parameter	(NMA$C_PTY_CD1 = 129)
	parameter	(NMA$C_PTY_CM2 = 194)
	parameter	(NMA$C_PTY_CM3 = 195)
	parameter	(NMA$C_PTY_CM4 = 196)
	parameter	(NMA$C_PTY_CM5 = 197)
	parameter	(NMA$C_PCCI_STA = 0)
	parameter	(NMA$C_PCCI_SUB = 1)
	parameter	(NMA$C_PCCI_SER = 100)
	parameter	(NMA$C_PCCI_LCT = 110)
	parameter	(NMA$C_PCCI_SPY = 120)
	parameter	(NMA$C_PCCI_SSB = 121)
	parameter	(NMA$C_PCCI_CNO = 200)
	parameter	(NMA$C_PCCI_COB = 201)
	parameter	(NMA$C_PCCI_LOO = 400)
	parameter	(NMA$C_PCCI_ADJ = 800)
	parameter	(NMA$C_PCCI_DRT = 801)
	parameter	(NMA$C_PCCI_BLO = 810)
	parameter	(NMA$C_PCCI_COS = 900)
	parameter	(NMA$C_PCCI_MRT = 901)
	parameter	(NMA$C_PCCI_RPR = 902)
	parameter	(NMA$C_PCCI_HET = 906)
	parameter	(NMA$C_PCCI_LIT = 907)
	parameter	(NMA$C_PCCI_BLK = 910)
	parameter	(NMA$C_PCCI_MRC = 920)
	parameter	(NMA$C_PCCI_RCT = 921)
	parameter	(NMA$C_PCCI_NUM = 930)
	parameter	(NMA$C_PCCI_USR = 1000)
	parameter	(NMA$C_PCCI_POL = 1010)
	parameter	(NMA$C_PCCI_PLS = 1011)
	parameter	(NMA$C_PCCI_OWN = 1100)
	parameter	(NMA$C_PCCI_LIN = 1110)
	parameter	(NMA$C_PCCI_USE = 1111)
	parameter	(NMA$C_PCCI_TYP = 1112)
	parameter	(NMA$C_PCCI_DTE = 1120)
	parameter	(NMA$C_PCCI_CHN = 1121)
	parameter	(NMA$C_PCCI_MBL = 1122)
	parameter	(NMA$C_PCCI_MWI = 1123)
	parameter	(NMA$C_PCCI_TRI = 1140)
	parameter	(NMA$C_PCCI_BBT = 1141)
	parameter	(NMA$C_PCCI_TRT = 1142)
	parameter	(NMA$C_PCCI_RTT = 1143)
	parameter	(NMA$C_PCCI_MRB = 1145)
	parameter	(NMA$C_PCCI_MTR = 1146)
	parameter	(NMA$C_PCCI_ACB = 1150)
	parameter	(NMA$C_PCCI_ACI = 1151)
	parameter	(NMA$C_PCCI_IAB = 1152)
	parameter	(NMA$C_PCCI_IAI = 1153)
	parameter	(NMA$C_PCCI_IAT = 1154)
	parameter	(NMA$C_PCCI_DYB = 1155)
	parameter	(NMA$C_PCCI_DYI = 1156)
	parameter	(NMA$C_PCCI_DYT = 1157)
	parameter	(NMA$C_PCCI_DTH = 1158)
	parameter	(NMA$C_PCCI_RSX_MAC = 2320)
	parameter	(NMA$C_PCCI_RSX_LOG = 2380)
	parameter	(NMA$C_PCCI_RSX_DLG = 2385)
	parameter	(NMA$C_PCCI_RSX_ACT = 2390)
	parameter	(NMA$C_PCCI_VER = 2700)
	parameter	(NMA$C_PCCI_XPT = 2720)
	parameter	(NMA$C_PCCI_MST = 2810)
	parameter	(NMA$C_PCCI_SRV_LOG = 3380)
	parameter	(NMA$C_PCCI_SRV_DLG = 3385)
	parameter	(NMA$C_PCCI_SRV_ACT = 3390)
	parameter	(NMA$C_PCLI_STA = 0)
	parameter	(NMA$C_PCLI_SUB = 1)
	parameter	(NMA$C_PCLI_SER = 100)
	parameter	(NMA$C_PCLI_LCT = 110)
	parameter	(NMA$C_PCLI_LOO = 400)
	parameter	(NMA$C_PCLI_ADJ = 800)
	parameter	(NMA$C_PCLI_BLO = 810)
	parameter	(NMA$C_PCLI_COS = 900)
	parameter	(NMA$C_PCLI_DEV = 1100)
	parameter	(NMA$C_PCLI_BFN = 1105)
	parameter	(NMA$C_PCLI_CON = 1110)
	parameter	(NMA$C_PCLI_DUP = 1111)
	parameter	(NMA$C_PCLI_PRO = 1112)
	parameter	(NMA$C_PCLI_LTY = 1112)
	parameter	(NMA$C_PCLI_CLO = 1113)
	parameter	(NMA$C_PCLI_STI = 1120)
	parameter	(NMA$C_PCLI_NTI = 1121)
	parameter	(NMA$C_PCLI_RTT = 1121)
	parameter	(NMA$C_PCLI_HTI = 1122)
	parameter	(NMA$C_PCLI_MBL = 1130)
	parameter	(NMA$C_PCLI_MRT = 1131)
	parameter	(NMA$C_PCLI_MWI = 1132)
	parameter	(NMA$C_PCLI_TRI = 1140)
	parameter	(NMA$C_PCLI_SLT = 1150)
	parameter	(NMA$C_PCLI_DDT = 1151)
	parameter	(NMA$C_PCLI_DLT = 1152)
	parameter	(NMA$C_PCLI_SRT = 1153)
	parameter	(NMA$C_PCLI_HWA = 1160)
	parameter	(NMA$C_PCLI_RSX_OWN = 2300)
	parameter	(NMA$C_PCLI_RSX_CCS = 2310)
	parameter	(NMA$C_PCLI_RSX_UCS = 2311)
	parameter	(NMA$C_PCLI_RSX_VEC = 2312)
	parameter	(NMA$C_PCLI_RSX_PRI = 2313)
	parameter	(NMA$C_PCLI_RSX_MDE = 2321)
	parameter	(NMA$C_PCLI_RSX_LLO = 2330)
	parameter	(NMA$C_PCLI_RSX_LOG = 2380)
	parameter	(NMA$C_PCLI_RSX_DLG = 2385)
	parameter	(NMA$C_PCLI_RSX_ACT = 2390)
	parameter	(NMA$C_PCLI_MCD = 2701)
	parameter	(NMA$C_PCLI_XMD = 2710)
	parameter	(NMA$C_PCLI_EPT = 2720)
	parameter	(NMA$C_PCLI_BUS = 2801)
	parameter	(NMA$C_PCLI_NMS = 2810)
	parameter	(NMA$C_PCLI_PHA = 2820)
	parameter	(NMA$C_PCLI_DPA = 2821)
	parameter	(NMA$C_PCLI_PTY = 2830)
	parameter	(NMA$C_PCLI_MCA = 2831)
	parameter	(NMA$C_PCLI_ILP = 2839)
	parameter	(NMA$C_PCLI_PRM = 2840)
	parameter	(NMA$C_PCLI_MLT = 2841)
	parameter	(NMA$C_PCLI_PAD = 2842)
	parameter	(NMA$C_PCLI_DCH = 2843)
	parameter	(NMA$C_PCLI_CRC = 2844)
	parameter	(NMA$C_PCLI_HBQ = 2845)
	parameter	(NMA$C_PCLI_ACC = 2846)
	parameter	(NMA$C_PCLI_EKO = 2847)
	parameter	(NMA$C_PCLI_BSZ = 2848)
	parameter	(NMA$C_PCLI_DES = 2849)
	parameter	(NMA$C_PCLI_RET = 2850)
	parameter	(NMA$C_PCLI_MOD = 2851)
	parameter	(NMA$C_PCLI_RIB = 2852)
	parameter	(NMA$C_PCLI_MNTL = 2860)
	parameter	(NMA$C_PCLI_INTL0 = 2861)
	parameter	(NMA$C_PCLI_INTL1 = 2862)
	parameter	(NMA$C_PCLI_INTL2 = 2863)
	parameter	(NMA$C_PCLI_INTL3 = 2864)
	parameter	(NMA$C_PCLI_FRA = 2865)
	parameter	(NMA$C_PCLI_STI1 = 2866)
	parameter	(NMA$C_PCLI_STI2 = 2867)
	parameter	(NMA$C_PCLI_TMO = 2868)
	parameter	(NMA$C_PCLI_MCL = 2869)
	parameter	(NMA$C_PCLI_SYC = 2870)
	parameter	(NMA$C_PCLI_BPC = 2871)
	parameter	(NMA$C_PCLI_SRV_OWN = 3300)
	parameter	(NMA$C_PCLI_SRV_UCS = 3311)
	parameter	(NMA$C_PCLI_SRV_VEC = 3312)
	parameter	(NMA$C_PCLI_SRV_PRI = 3313)
	parameter	(NMA$C_PCLI_SRV_LOG = 3380)
	parameter	(NMA$C_PCLI_SRV_DLG = 3385)
	parameter	(NMA$C_PCLI_SRV_ACT = 3390)
	parameter	(NMA$C_PCCO_RTR = 110)
	parameter	(NMA$C_PCLD_ASS = 10)
	parameter	(NMA$C_PCLP_ASS = 10)
	parameter	(NMA$C_PCCN_CIR = 100)
	parameter	(NMA$C_PCCN_SUR = 110)
	parameter	(NMA$C_PCCN_ELT = 111)
	parameter	(NMA$C_PCCN_PHA = 120)
	parameter	(NMA$C_PCCN_LRP = 130)
	parameter	(NMA$C_PCCN_MVR = 20001)
	parameter	(NMA$C_PCCN_FCT = 20002)
	parameter	(NMA$C_PCCN_CUS = 20003)
	parameter	(NMA$C_PCCN_RTR = 20004)
	parameter	(NMA$C_PCCN_CSZ = 20005)
	parameter	(NMA$C_PCCN_RSZ = 20006)
	parameter	(NMA$C_PCCN_HWA = 20007)
	parameter	(NMA$C_PCCN_DTY = 20100)
	parameter	(NMA$C_PCCN_SFI = 20200)
	parameter	(NMA$C_PCCN_SPR = 20300)
	parameter	(NMA$C_PCCN_DLK = 20400)
	parameter	(NMA$C_PCLO_STA = 0)
	parameter	(NMA$C_PCLO_LNA = 100)
	parameter	(NMA$C_PCLO_SIN = 200)
	parameter	(NMA$C_PCLO_EVE = 201)
	parameter	(NMA$C_PCXA_NOD = 320)
	parameter	(NMA$C_PCXA_USR = 330)
	parameter	(NMA$C_PCXA_PSW = 331)
	parameter	(NMA$C_PCXA_ACC = 332)
	parameter	(NMA$C_PCXA_NET = 1110)
	parameter	(NMA$C_PCXA_RSX_ADS = 2310)
	parameter	(NMA$C_PCXA_RSX_ANB = 2320)
	parameter	(NMA$C_PCXA_RSX_ASC = 2330)
	parameter	(NMA$C_PCXA_SRV_ADS = 3310)
	parameter	(NMA$C_PCXA_SRV_ANB = 3320)
	parameter	(NMA$C_PCXA_SRV_ASC = 3330)
	parameter	(NMA$C_PCXP_STA = 0)
	parameter	(NMA$C_PCXP_CTM = 100)
	parameter	(NMA$C_PCXP_ACH = 1000)
	parameter	(NMA$C_PCXP_ASW = 1010)
	parameter	(NMA$C_PCXP_DTE = 1100)
	parameter	(NMA$C_PCXP_GRP = 1101)
	parameter	(NMA$C_PCXP_NET = 1110)
	parameter	(NMA$C_PCXP_LIN = 1120)
	parameter	(NMA$C_PCXP_CHN = 1130)
	parameter	(NMA$C_PCXP_MCH = 1131)
	parameter	(NMA$C_PCXP_DBL = 1140)
	parameter	(NMA$C_PCXP_DWI = 1141)
	parameter	(NMA$C_PCXP_MBL = 1150)
	parameter	(NMA$C_PCXP_MWI = 1151)
	parameter	(NMA$C_PCXP_MCL = 1152)
	parameter	(NMA$C_PCXP_MRS = 1153)
	parameter	(NMA$C_PCXP_MST = 1154)
	parameter	(NMA$C_PCXP_CAT = 1160)
	parameter	(NMA$C_PCXP_CLT = 1161)
	parameter	(NMA$C_PCXP_RST = 1162)
	parameter	(NMA$C_PCXP_STT = 1163)
	parameter	(NMA$C_PCXP_GDT = 1170)
	parameter	(NMA$C_PCXP_GNM = 1171)
	parameter	(NMA$C_PCXP_GTY = 1172)
	parameter	(NMA$C_PCXP_RSX_PMC = 2300)
	parameter	(NMA$C_PCXP_MNS = 2700)
	parameter	(NMA$C_PCXP_MCI = 2710)
	parameter	(NMA$C_PCXP_SBS = 2720)
	parameter	(NMA$C_PCXP_SRV_PMC = 3300)
	parameter	(NMA$C_PCXS_CTM = 100)
	parameter	(NMA$C_PCXS_ACI = 200)
	parameter	(NMA$C_PCXS_DST = 300)
	parameter	(NMA$C_PCXS_MCI = 310)
	parameter	(NMA$C_PCXS_NOD = 320)
	parameter	(NMA$C_PCXS_USR = 330)
	parameter	(NMA$C_PCXS_SPW = 331)
	parameter	(NMA$C_PCXS_RPW = 331)
	parameter	(NMA$C_PCXS_ACC = 332)
	parameter	(NMA$C_PCXS_OBJ = 340)
	parameter	(NMA$C_PCXS_PRI = 350)
	parameter	(NMA$C_PCXS_CMK = 351)
	parameter	(NMA$C_PCXS_CVL = 352)
	parameter	(NMA$C_PCXS_GRP = 353)
	parameter	(NMA$C_PCXS_NUM = 354)
	parameter	(NMA$C_PCXS_SAD = 355)
	parameter	(NMA$C_PCXS_RSX_5ST = 2310)
	parameter	(NMA$C_PCXS_STA = 2700)
	parameter	(NMA$C_PCXS_FIL = 2710)
	parameter	(NMA$C_PCXS_SRV_5ST = 3310)
	parameter	(NMA$C_PCXT_STA = 0)
	parameter	(NMA$C_PCXT_BSZ = 100)
	parameter	(NMA$C_PCXT_MBK = 101)
	parameter	(NMA$C_PCXT_FNM = 102)
	parameter	(NMA$C_PCXT_MBF = 103)
	parameter	(NMA$C_PCXT_CPL = 104)
	parameter	(NMA$C_PCXT_MVR = 105)
	parameter	(NMA$C_PCXT_TPT = 106)
	parameter	(NMA$C_PCXT_CPS = 110)
	parameter	(NMA$C_PCXT_TST = 111)
	parameter	(NMA$C_PCNO_STA = 0)
	parameter	(NMA$C_PCNO_PHA = 10)
	parameter	(NMA$C_PCNO_IDE = 100)
	parameter	(NMA$C_PCNO_MVE = 101)
	parameter	(NMA$C_PCNO_SLI = 110)
	parameter	(NMA$C_PCNO_SPA = 111)
	parameter	(NMA$C_PCNO_SDV = 112)
	parameter	(NMA$C_PCNO_CPU = 113)
	parameter	(NMA$C_PCNO_HWA = 114)
	parameter	(NMA$C_PCNO_SNV = 115)
	parameter	(NMA$C_PCNO_LOA = 120)
	parameter	(NMA$C_PCNO_SLO = 121)
	parameter	(NMA$C_PCNO_TLO = 122)
	parameter	(NMA$C_PCNO_DFL = 123)
	parameter	(NMA$C_PCNO_STY = 125)
	parameter	(NMA$C_PCNO_SID = 126)
	parameter	(NMA$C_PCNO_DUM = 130)
	parameter	(NMA$C_PCNO_SDU = 131)
	parameter	(NMA$C_PCNO_DAD = 135)
	parameter	(NMA$C_PCNO_DCT = 136)
	parameter	(NMA$C_PCNO_OHO = 140)
	parameter	(NMA$C_PCNO_IHO = 141)
	parameter	(NMA$C_PCNO_LPC = 150)
	parameter	(NMA$C_PCNO_LPL = 151)
	parameter	(NMA$C_PCNO_LPD = 152)
	parameter	(NMA$C_PCNO_LPA = 153)
	parameter	(NMA$C_PCNO_LPH = 154)
	parameter	(NMA$C_PCNO_LPN = 155)
	parameter	(NMA$C_PCNO_LAN = 156)
	parameter	(NMA$C_PCNO_CTI = 160)
	parameter	(NMA$C_PCNO_NNA = 500)
	parameter	(NMA$C_PCNO_NLI = 501)
	parameter	(NMA$C_PCNO_ADD = 502)
	parameter	(NMA$C_PCNO_ITI = 510)
	parameter	(NMA$C_PCNO_OTI = 511)
	parameter	(NMA$C_PCNO_ACL = 600)
	parameter	(NMA$C_PCNO_DEL = 601)
	parameter	(NMA$C_PCNO_NVE = 700)
	parameter	(NMA$C_PCNO_MLK = 710)
	parameter	(NMA$C_PCNO_DFA = 720)
	parameter	(NMA$C_PCNO_DWE = 721)
	parameter	(NMA$C_PCNO_IAT = 722)
	parameter	(NMA$C_PCNO_RFA = 723)
	parameter	(NMA$C_PCNO_DTY = 810)
	parameter	(NMA$C_PCNO_DCO = 820)
	parameter	(NMA$C_PCNO_DHO = 821)
	parameter	(NMA$C_PCNO_DLI = 822)
	parameter	(NMA$C_PCNO_NND = 830)
	parameter	(NMA$C_PCNO_RVE = 900)
	parameter	(NMA$C_PCNO_ETY = 901)
	parameter	(NMA$C_PCNO_RTI = 910)
	parameter	(NMA$C_PCNO_SAD = 911)
	parameter	(NMA$C_PCNO_BRT = 912)
	parameter	(NMA$C_PCNO_MAD = 920)
	parameter	(NMA$C_PCNO_MLN = 921)
	parameter	(NMA$C_PCNO_MCO = 922)
	parameter	(NMA$C_PCNO_MHO = 923)
	parameter	(NMA$C_PCNO_MVI = 924)
	parameter	(NMA$C_PCNO_MAR = 925)
	parameter	(NMA$C_PCNO_MBE = 926)
	parameter	(NMA$C_PCNO_MBR = 927)
	parameter	(NMA$C_PCNO_AMC = 928)
	parameter	(NMA$C_PCNO_AMH = 929)
	parameter	(NMA$C_PCNO_MBU = 930)
	parameter	(NMA$C_PCNO_BUS = 931)
	parameter	(NMA$C_PCNO_SBS = 932)
	parameter	(NMA$C_PCNO_FBS = 933)
	parameter	(NMA$C_PCNO_RSX_RPA = 2300)
	parameter	(NMA$C_PCNO_RSX_TPA = 2301)
	parameter	(NMA$C_PCNO_RSX_VER = 2310)
	parameter	(NMA$C_PCNO_PUS = 2704)
	parameter	(NMA$C_PCNO_PAC = 2705)
	parameter	(NMA$C_PCNO_PPW = 2706)
	parameter	(NMA$C_PCNO_NUS = 2712)
	parameter	(NMA$C_PCNO_NAC = 2713)
	parameter	(NMA$C_PCNO_NPW = 2714)
	parameter	(NMA$C_PCNO_RPA = 2720)
	parameter	(NMA$C_PCNO_TPA = 2721)
	parameter	(NMA$C_PCNO_ACC = 2730)
	parameter	(NMA$C_PCNO_DAC = 2731)
	parameter	(NMA$C_PCNO_PIQ = 2740)
	parameter	(NMA$C_PCNO_ALI = 2741)
	parameter	(NMA$C_PCNO_PRX = 2750)
	parameter	(NMA$C_PCNO_DPX = 2751)
	parameter	(NMA$C_PCNO_SRV_RPA = 3300)
	parameter	(NMA$C_PCNO_SRV_TPA = 3301)
	parameter	(NMA$C_PCNO_SRV_VER = 3310)
	parameter	(NMA$C_PCNO_SRV_ACB = 3402)
	parameter	(NMA$C_PCNO_SRV_ASB = 3404)
	parameter	(NMA$C_PCNO_SRV_ALB = 3406)
	parameter	(NMA$C_PCNO_SRV_MCB = 3410)
	parameter	(NMA$C_PCNO_SRV_MSB = 3420)
	parameter	(NMA$C_PCNO_SRV_MLB = 3430)
	parameter	(NMA$C_PCNO_SRV_LBS = 3431)
	parameter	(NMA$C_PCNO_SRV_NRB = 3440)
	parameter	(NMA$C_PCNO_SRV_CPT = 3450)
	parameter	(NMA$C_PCNO_SRV_CPF = 3452)
	parameter	(NMA$C_PCNO_SRV_CPL = 3454)
	parameter	(NMA$C_PCNO_SRV_XPT = 3460)
	parameter	(NMA$C_PCNO_SRV_XPF = 3462)
	parameter	(NMA$C_PCNO_SRV_XPL = 3464)
	parameter	(NMA$C_PCAR_STA = 0)
	parameter	(NMA$C_PCAR_COS = 820)
	parameter	(NMA$C_PCAR_HOP = 821)
	parameter	(NMA$C_PCAR_CIR = 822)
	parameter	(NMA$C_PCAR_NND = 830)
	parameter	(NMA$C_PCOB_OAN = 400)
	parameter	(NMA$C_PCOB_OAC = 410)
	parameter	(NMA$C_PCOB_ONA = 500)
	parameter	(NMA$C_PCOB_OCO = 510)
	parameter	(NMA$C_PCOB_OUS = 511)
	parameter	(NMA$C_PCOB_OVE = 520)
	parameter	(NMA$C_PCOB_NAM = 500)
	parameter	(NMA$C_PCOB_NUM = 513)
	parameter	(NMA$C_PCOB_FID = 530)
	parameter	(NMA$C_PCOB_PID = 535)
	parameter	(NMA$C_PCOB_PRV = 540)
	parameter	(NMA$C_PCOB_USR = 550)
	parameter	(NMA$C_PCOB_ACC = 551)
	parameter	(NMA$C_PCOB_PSW = 552)
	parameter	(NMA$C_PCOB_PRX = 560)
	parameter	(NMA$C_PCLK_STA = 0)
	parameter	(NMA$C_PCLK_PID = 101)
	parameter	(NMA$C_PCLK_NID = 102)
	parameter	(NMA$C_PCLK_LAD = 105)
	parameter	(NMA$C_PCLK_DLY = 110)
	parameter	(NMA$C_PCLK_RLN = 120)
	parameter	(NMA$C_PCLK_RID = 121)
	parameter	(NMA$C_PCLK_USR = 130)
	parameter	(NMA$C_PCLK_PRC = 131)
	parameter	(NMA$C_CTCIR_ZER = 0)
	parameter	(NMA$C_CTCIR_APR = 800)
	parameter	(NMA$C_CTCIR_DPS = 801)
	parameter	(NMA$C_CTCIR_ACL = 802)
	parameter	(NMA$C_CTCIR_CRL = 805)
	parameter	(NMA$C_CTCIR_TPR = 810)
	parameter	(NMA$C_CTCIR_TPS = 811)
	parameter	(NMA$C_CTCIR_TCL = 812)
	parameter	(NMA$C_CTCIR_LDN = 820)
	parameter	(NMA$C_CTCIR_IFL = 821)
	parameter	(NMA$C_CTCIR_BRC = 1000)
	parameter	(NMA$C_CTCIR_BSN = 1001)
	parameter	(NMA$C_CTCIR_MBY = 1002)
	parameter	(NMA$C_CTCIR_DBR = 1010)
	parameter	(NMA$C_CTCIR_DBS = 1011)
	parameter	(NMA$C_CTCIR_DEI = 1020)
	parameter	(NMA$C_CTCIR_DEO = 1021)
	parameter	(NMA$C_CTCIR_RRT = 1030)
	parameter	(NMA$C_CTCIR_LRT = 1031)
	parameter	(NMA$C_CTCIR_RBE = 1040)
	parameter	(NMA$C_CTCIR_LBE = 1041)
	parameter	(NMA$C_CTCIR_SIE = 1050)
	parameter	(NMA$C_CTCIR_SLT = 1051)
	parameter	(NMA$C_CTCIR_UBU = 1065)
	parameter	(NMA$C_CTCIR_RPE = 1100)
	parameter	(NMA$C_CTCIR_LPE = 1101)
	parameter	(NMA$C_CTCIR_LIR = 1240)
	parameter	(NMA$C_CTCIR_RIR = 1241)
	parameter	(NMA$C_CTCIR_NIR = 1242)
	parameter	(NMA$C_CTCIR_MNE = 2701)
	parameter	(NMA$C_CTCIR_ERI = 2750)
	parameter	(NMA$C_CTCIR_ERO = 2751)
	parameter	(NMA$C_CTCIR_RTO = 2752)
	parameter	(NMA$C_CTCIR_LTO = 2753)
	parameter	(NMA$C_CTCIR_BER = 2754)
	parameter	(NMA$C_CTCIR_BEL = 2755)
	parameter	(NMA$C_CTLIN_ZER = 0)
	parameter	(NMA$C_CTLIN_APR = 800)
	parameter	(NMA$C_CTLIN_DPS = 801)
	parameter	(NMA$C_CTLIN_ACL = 802)
	parameter	(NMA$C_CTLIN_TPR = 810)
	parameter	(NMA$C_CTLIN_TPS = 811)
	parameter	(NMA$C_CTLIN_TCL = 812)
	parameter	(NMA$C_CTLIN_LDN = 820)
	parameter	(NMA$C_CTLIN_IFL = 821)
	parameter	(NMA$C_CTLIN_BRC = 1000)
	parameter	(NMA$C_CTLIN_BSN = 1001)
	parameter	(NMA$C_CTLIN_MBY = 1002)
	parameter	(NMA$C_CTLIN_DBR = 1010)
	parameter	(NMA$C_CTLIN_DBS = 1011)
	parameter	(NMA$C_CTLIN_MBL = 1012)
	parameter	(NMA$C_CTLIN_BID = 1013)
	parameter	(NMA$C_CTLIN_BS1 = 1014)
	parameter	(NMA$C_CTLIN_BSM = 1015)
	parameter	(NMA$C_CTLIN_DEI = 1020)
	parameter	(NMA$C_CTLIN_DEO = 1021)
	parameter	(NMA$C_CTLIN_RRT = 1030)
	parameter	(NMA$C_CTLIN_LRT = 1031)
	parameter	(NMA$C_CTLIN_RBE = 1040)
	parameter	(NMA$C_CTLIN_LBE = 1041)
	parameter	(NMA$C_CTLIN_SIE = 1050)
	parameter	(NMA$C_CTLIN_SLT = 1051)
	parameter	(NMA$C_CTLIN_SFL = 1060)
	parameter	(NMA$C_CTLIN_CDC = 1061)
	parameter	(NMA$C_CTLIN_RFL = 1062)
	parameter	(NMA$C_CTLIN_UFD = 1063)
	parameter	(NMA$C_CTLIN_OVR = 1064)
	parameter	(NMA$C_CTLIN_SBU = 1065)
	parameter	(NMA$C_CTLIN_UBU = 1066)
	parameter	(NMA$C_CTLIN_RPE = 1100)
	parameter	(NMA$C_CTLIN_LPE = 1101)
	parameter	(NMA$W_NODE = 0)
	parameter	(NMA$S_ADDR = 10)
	parameter	(NMA$V_ADDR = 0)
	parameter	(NMA$S_AREA = 6)
	parameter	(NMA$V_AREA = 10)
	parameter	(NMA$S_PTY_TYP = 15)
	parameter	(NMA$V_PTY_TYP = 0)
	parameter	(NMA$S_PTY_CLE = 6)
	parameter	(NMA$V_PTY_CLE = 0)
	parameter	(NMA$V_PTY_MUL = 6)
	parameter	(NMA$V_PTY_COD = 7)
	parameter	(NMA$S_PTY_CMU = 2)
	parameter	(NMA$V_PTY_CMU = 6)
	parameter	(NMA$S_PTY_NLE = 4)
	parameter	(NMA$V_PTY_NLE = 0)
	parameter	(NMA$S_PTY_NTY = 2)
	parameter	(NMA$V_PTY_NTY = 4)
	parameter	(NMA$V_PTY_ASC = 6)
	parameter	(NMA$M_CTLIN_BTL = 8)
	parameter	(NMA$M_CTLIN_FCS = 16)
	parameter	(NMA$M_CTLIN_TRJ = 32)
	parameter	(NMA$V_CTLIN_BTL = 3)
	parameter	(NMA$V_CTLIN_FCS = 4)
	parameter	(NMA$V_CTLIN_TRJ = 5)
	parameter	(NMA$M_CTLIN_RRJ = 8)
	parameter	(NMA$V_CTLIN_RRJ = 3)
	parameter	(NMA$M_CTLIN_RRN = 4)
	parameter	(NMA$V_CTLIN_RRN = 2)
	parameter	(NMA$M_CTLIN_TRN = 4)
	parameter	(NMA$V_CTLIN_TRN = 2)
	parameter	(NMA$M_CTLIN_INR = 16)
	parameter	(NMA$M_CTLIN_FMS = 32)
	parameter	(NMA$V_CTLIN_INR = 4)
	parameter	(NMA$V_CTLIN_FMS = 5)
	parameter	(NMA$M_CTLIN_TUN = 4)
	parameter	(NMA$M_CTLIN_RUN = 16)
	parameter	(NMA$M_CTLIN_FMR = 32)
	parameter	(NMA$C_CTLIN_MBS = 2701)
	parameter	(NMA$C_CTLIN_MSN = 2702)
	parameter	(NMA$C_CTLIN_RME = 2750)
	parameter	(NMA$C_CTLIN_LCE = 2751)
	parameter	(NMA$C_CTLIN_MSE = 2752)
	parameter	(NMA$C_CTNOD_ZER = 0)
	parameter	(NMA$C_CTNOD_BRC = 600)
	parameter	(NMA$C_CTNOD_BSN = 601)
	parameter	(NMA$C_CTNOD_MRC = 610)
	parameter	(NMA$C_CTNOD_MSN = 611)
	parameter	(NMA$C_CTNOD_CRC = 620)
	parameter	(NMA$C_CTNOD_CSN = 621)
	parameter	(NMA$C_CTNOD_RTO = 630)
	parameter	(NMA$C_CTNOD_RSE = 640)
	parameter	(NMA$C_CTNOD_MLL = 700)
	parameter	(NMA$C_CTNOD_APL = 900)
	parameter	(NMA$C_CTNOD_NUL = 901)
	parameter	(NMA$C_CTNOD_NOL = 902)
	parameter	(NMA$C_CTNOD_OPL = 903)
	parameter	(NMA$C_CTNOD_PFE = 910)
	parameter	(NMA$C_CTNOD_RUL = 920)
	parameter	(NMA$C_CTNOD_VER = 930)
	parameter	(NMA$C_CTNOD_SRV_SYC = 3310)
	parameter	(NMA$C_CTNOD_SRV_SYS = 3320)
	parameter	(NMA$C_CTNOD_SRV_SYL = 3330)
	parameter	(NMA$C_CTNOD_SRV_SYR = 3340)
	parameter	(NMA$C_CTXP_ZER = 0)
	parameter	(NMA$C_CTXP_BRC = 1000)
	parameter	(NMA$C_CTXP_BSN = 1001)
	parameter	(NMA$C_CTXP_BLR = 1010)
	parameter	(NMA$C_CTXP_BLS = 1011)
	parameter	(NMA$C_CTXP_CRC = 1200)
	parameter	(NMA$C_CTXP_CSN = 1201)
	parameter	(NMA$C_CTXP_FSR = 1210)
	parameter	(NMA$C_CTXP_FSS = 1211)
	parameter	(NMA$C_CTXP_MSA = 1220)
	parameter	(NMA$C_CTXP_MCA = 1221)
	parameter	(NMA$C_CTXP_RSE = 1230)
	parameter	(NMA$C_CTXP_LIR = 1240)
	parameter	(NMA$C_CTXP_RIR = 1241)
	parameter	(NMA$C_CTXP_NIR = 1242)
	parameter	(NMA$C_CTXP_RST = 1250)
	parameter	(NMA$C_CTXS_ZER = 0)
	parameter	(NMA$C_CTXS_MCA = 200)
	parameter	(NMA$C_CTXS_ICR = 210)
	parameter	(NMA$C_CTXS_LLR = 211)
	parameter	(NMA$C_LOOP_MIX = 2)
	parameter	(NMA$C_LOOP_ONE = 1)
	parameter	(NMA$C_LOOP_ZER = 0)
	parameter	(NMA$C_LOOP_DCNT = 1)
	parameter	(NMA$C_LOOP_DSIZ = 40)
	parameter	(NMA$C_LOOP_XMIT = 0)
	parameter	(NMA$C_LOOP_RECV = 1)
	parameter	(NMA$C_LOOP_FULL = 2)
	parameter	(NMA$C_STATE_ON = 0)
	parameter	(NMA$C_STATE_OFF = 1)
	parameter	(NMA$C_STATE_SER = 2)
	parameter	(NMA$C_STATE_CLE = 3)
	parameter	(NMA$C_STATE_HOL = 2)
	parameter	(NMA$C_STATE_SHU = 2)
	parameter	(NMA$C_STATE_RES = 3)
	parameter	(NMA$C_STATE_REA = 4)
	parameter	(NMA$C_STATE_UNR = 5)
	parameter	(NMA$C_ASS_ENA = 0)
	parameter	(NMA$C_ASS_DIS = 1)
	parameter	(NMA$C_SUR_ENA = 0)
	parameter	(NMA$C_SUR_DIS = 1)
	parameter	(NMA$C_LINSS_STA = 0)
	parameter	(NMA$C_LINSS_REF = 1)
	parameter	(NMA$C_LINSS_LOO = 2)
	parameter	(NMA$C_LINSS_LOA = 3)
	parameter	(NMA$C_LINSS_DUM = 4)
	parameter	(NMA$C_LINSS_TRI = 5)
	parameter	(NMA$C_LINSS_ASE = 6)
	parameter	(NMA$C_LINSS_ALO = 7)
	parameter	(NMA$C_LINSS_ADU = 8)
	parameter	(NMA$C_LINSS_ATR = 9)
	parameter	(NMA$C_LINSS_SYN = 10)
	parameter	(NMA$C_LINSS_FAI = 11)
	parameter	(NMA$C_LINSS_RUN = 12)
	parameter	(NMA$C_LINSS_UNS = 13)
	parameter	(NMA$C_LINSS_IDL = 14)
	parameter	(NMA$C_CIRTY_POI = 0)
	parameter	(NMA$C_CIRTY_CON = 1)
	parameter	(NMA$C_CIRTY_TRI = 2)
	parameter	(NMA$C_CIRTY_X25 = 3)
	parameter	(NMA$C_CIRTY_DMC = 4)
	parameter	(NMA$C_CIRTY_NI = 6)
	parameter	(NMA$C_LINSV_ENA = 0)
	parameter	(NMA$C_LINSV_DIS = 1)
	parameter	(NMA$C_CIRPST_AUT = 1)
	parameter	(NMA$C_CIRPST_ACT = 2)
	parameter	(NMA$C_CIRPST_INA = 3)
	parameter	(NMA$C_CIRPST_DIE = 4)
	parameter	(NMA$C_CIRPST_DED = 5)
	parameter	(NMA$C_CIRBLK_ENA = 0)
	parameter	(NMA$C_CIRBLK_DIS = 1)
	parameter	(NMA$C_CIRUS_PER = 0)
	parameter	(NMA$C_CIRUS_INC = 1)
	parameter	(NMA$C_CIRUS_OUT = 2)
	parameter	(NMA$C_CIRBF_UNL = 255)
	parameter	(NMA$C_CIRVE_ENA = 0)
	parameter	(NMA$C_CIRVE_DIS = 1)
	parameter	(NMA$C_CIRXPT_ZND = 1)
	parameter	(NMA$C_CIRXPT_PH2 = 2)
	parameter	(NMA$C_CIRXPT_PH3 = 3)
	parameter	(NMA$C_CIRXPT_RO3 = 3)
	parameter	(NMA$C_CIRXPT_NR4 = 4)
	parameter	(NMA$C_DPX_FUL = 0)
	parameter	(NMA$C_DPX_HAL = 1)
	parameter	(NMA$C_LINCN_NOR = 0)
	parameter	(NMA$C_LINCN_LOO = 1)
	parameter	(NMA$C_LINPR_POI = 0)
	parameter	(NMA$C_LINPR_CON = 1)
	parameter	(NMA$C_LINPR_TRI = 2)
	parameter	(NMA$C_LINPR_DMC = 4)
	parameter	(NMA$C_LINPR_LAPB = 5)
	parameter	(NMA$C_LINPR_NI = 6)
	parameter	(NMA$C_LINPR_BSY = 9)
	parameter	(NMA$C_LINPR_MAS = 1)
	parameter	(NMA$C_LINPR_NEU = 2)
	parameter	(NMA$C_LINPR_SEC = 0)
	parameter	(NMA$C_LINCL_EXT = 0)
	parameter	(NMA$C_LINCL_INT = 1)
	parameter	(NMA$C_LINTY_POI = 0)
	parameter	(NMA$C_LINTY_CON = 1)
	parameter	(NMA$C_LINTY_TRI = 2)
	parameter	(NMA$C_LINTY_DMC = 3)
	parameter	(NMA$C_LINMC_SET = 1)
	parameter	(NMA$C_LINMC_CLR = 2)
	parameter	(NMA$C_LINMC_CAL = 3)
	parameter	(NMA$C_LINMC_SDF = 4)
	parameter	(NMA$C_ACC_SHR = 1)
	parameter	(NMA$C_ACC_LIM = 2)
	parameter	(NMA$C_ACC_EXC = 3)
	parameter	(NMA$C_LINMO_AUT = 1)
	parameter	(NMA$C_LINMO_SIL = 2)
	parameter	(NMA$C_X25MD_DTE = 1)
	parameter	(NMA$C_X25MD_DCE = 2)
	parameter	(NMA$C_X25MD_DTL = 3)
	parameter	(NMA$C_X25MD_DCL = 4)
	parameter	(NMA$C_NODTY_ROU = 0)
	parameter	(NMA$C_NODTY_NON = 1)
	parameter	(NMA$C_NODTY_PHA = 2)
	parameter	(NMA$C_NODTY_AREA = 3)
	parameter	(NMA$C_NODTY_RT4 = 4)
	parameter	(NMA$C_NODTY_NR4 = 5)
	parameter	(NMA$C_NODPW_SET = 0)
	parameter	(NMA$C_CPU_8 = 0)
	parameter	(NMA$C_CPU_11 = 1)
	parameter	(NMA$C_CPU_1020 = 2)
	parameter	(NMA$C_CPU_VAX = 3)
	parameter	(NMA$C_NODSNV_PH3 = 0)
	parameter	(NMA$C_NODSNV_PH4 = 1)
	parameter	(NMA$C_SOFT_SECL = 0)
	parameter	(NMA$C_SOFT_TERL = 1)
	parameter	(NMA$C_SOFT_OSYS = 2)
	parameter	(NMA$C_SOFT_DIAG = 3)
	parameter	(NMA$C_ACES_NONE = 0)
	parameter	(NMA$C_ACES_INCO = 1)
	parameter	(NMA$C_ACES_OUTG = 2)
	parameter	(NMA$C_ACES_BOTH = 3)
	parameter	(NMA$C_ACES_REQU = 4)
	parameter	(NMA$C_XPRTY_BIL = 1)
	parameter	(NMA$C_XPRST_ON = 0)
	parameter	(NMA$C_XPRST_OFF = 1)
	parameter	(NMA$C_XPRST_SHU = 2)
	parameter	(NMA$C_XPRMN_ENA = 0)
	parameter	(NMA$C_XPRMN_DIS = 1)
	parameter	(NMA$C_XPRSB_RUN = 12)
	parameter	(NMA$C_XPRSB_UNS = 13)
	parameter	(NMA$C_XPRSB_SYN = 10)
	parameter	(NMA$C_JAN = 1)
	parameter	(NMA$C_FEB = 2)
	parameter	(NMA$C_MAR = 3)
	parameter	(NMA$C_APR = 4)
	parameter	(NMA$C_MAY = 5)
	parameter	(NMA$C_JUN = 6)
	parameter	(NMA$C_JUL = 7)
	parameter	(NMA$C_AUG = 8)
	parameter	(NMA$C_SEP = 9)
	parameter	(NMA$C_OCT = 10)
	parameter	(NMA$C_NOV = 11)
	parameter	(NMA$C_DEC = 12)
	parameter	(NMA$C_SOFD_DP = 0)
	parameter	(NMA$C_SOFD_UNA = 1)
	parameter	(NMA$C_SOFD_DU = 2)
	parameter	(NMA$C_SOFD_DL = 4)
	parameter	(NMA$C_SOFD_DQ = 6)
	parameter	(NMA$C_SOFD_DA = 8)
	parameter	(NMA$C_SOFD_DUP = 10)
	parameter	(NMA$C_SOFD_DMC = 12)
	parameter	(NMA$C_SOFD_DMP = 18)
	parameter	(NMA$C_SOFD_DTE = 20)
	parameter	(NMA$C_SOFD_KL8 = 32)
	parameter	(NMA$C_SOFD_DMV = 34)
	parameter	(NMA$C_SOFD_DPV = 36)
	parameter	(NMA$C_SOFD_DMF = 38)
	parameter	(NMA$_SUCCESS = 1)
	parameter	(NMA$_SUCCFLDRPL = 9)
	parameter	(NMA$_BADFID = 0)
	parameter	(NMA$_BADDAT = 8)
	parameter	(NMA$_BADOPR = 16)
	parameter	(NMA$_BUFTOOSMALL = 24)
	parameter	(NMA$_FLDNOTFND = 32)
	parameter	(NMA$C_OPN_MIN = 0)
	parameter	(NMA$C_OPN_NODE = 0)
	parameter	(NMA$C_OPN_LINE = 1)
	parameter	(NMA$C_OPN_LOG = 2)
	parameter	(NMA$C_OPN_OBJ = 3)
	parameter	(NMA$C_OPN_CIR = 4)
	parameter	(NMA$C_OPN_X25 = 5)
	parameter	(NMA$C_OPN_X29 = 6)
	parameter	(NMA$C_OPN_CNF = 7)
	parameter	(NMA$C_OPN_MAX = 7)
	parameter	(NMA$C_OPN_ALL = 127)
	parameter	(NMA$C_OPN_AC_RO = 0)
	parameter	(NMA$C_OPN_AC_RW = 1)
	parameter	(NMA$C_FN2_DLL = 2)
	parameter	(NMA$C_FN2_ULD = 3)
	parameter	(NMA$C_FN2_TRI = 4)
	parameter	(NMA$C_FN2_LOO = 5)
	parameter	(NMA$C_FN2_TES = 6)
	parameter	(NMA$C_FN2_SET = 7)
	parameter	(NMA$C_FN2_REA = 8)
	parameter	(NMA$C_FN2_ZER = 9)
	parameter	(NMA$C_FN2_LNS = 14)
	parameter	(NMA$C_OP2_CHNST = 5)
	parameter	(NMA$C_OP2_CHLST = 8)
	parameter	(NMA$C_OP2_RENCT = 0)
	parameter	(NMA$C_OP2_RENST = 1)
	parameter	(NMA$C_OP2_RELCT = 4)
	parameter	(NMA$C_OP2_RELST = 5)
	parameter	(NMA$C_OP2_ZENCT = 0)
	parameter	(NMA$C_OP2_ZELCT = 2)
	parameter	(NMA$C_EN2_KNO = 0)
	parameter	(NMA$C_EN2_LID = 1)
	parameter	(NMA$C_EN2_LCN = 2)
	parameter	(NMA$C_STS_SUC = 1)
	parameter	(NMA$C_STS_MOR = 2)
	parameter	(NMA$C_STS_PAR = 3)
	parameter	(NMA$C_STS_DON = -128)
	parameter	(NMA$C_STS_FUN = -1)
	parameter	(NMA$C_STS_INV = -2)
	parameter	(NMA$C_STS_PRI = -3)
	parameter	(NMA$C_STS_SIZ = -4)
	parameter	(NMA$C_STS_MPR = -5)
	parameter	(NMA$C_STS_PTY = -6)
	parameter	(NMA$C_STS_MVE = -7)
	parameter	(NMA$C_STS_CMP = -8)
	parameter	(NMA$C_STS_IDE = -9)
	parameter	(NMA$C_STS_LCO = -10)
	parameter	(NMA$C_STS_STA = -11)
	parameter	(NMA$C_STS_FOP = -13)
	parameter	(NMA$C_STS_FCO = -14)
	parameter	(NMA$C_STS_RES = -15)
	parameter	(NMA$C_STS_PVA = -16)
	parameter	(NMA$C_STS_LPR = -17)
	parameter	(NMA$C_STS_FIO = -18)
	parameter	(NMA$C_STS_MLD = -19)
	parameter	(NMA$C_STS_ROO = -20)
	parameter	(NMA$C_STS_MCF = -21)
	parameter	(NMA$C_STS_PNA = -22)
	parameter	(NMA$C_STS_PLO = -23)
	parameter	(NMA$C_STS_HAR = -24)
	parameter	(NMA$C_STS_OPE = -25)
	parameter	(NMA$C_STS_SYS = -26)
	parameter	(NMA$C_STS_PGP = -27)
	parameter	(NMA$C_STS_BLR = -28)
	parameter	(NMA$C_STS_PMS = -29)
	parameter	(NMA$C_STS_ALI = -127)
	parameter	(NMA$C_STS_OBJ = -126)
	parameter	(NMA$C_STS_PRO = -125)
	parameter	(NMA$C_STS_LNK = -124)
	parameter	(NMA$C_FOPDTL_PDB = 0)
	parameter	(NMA$C_FOPDTL_LFL = 1)
	parameter	(NMA$C_FOPDTL_DFL = 2)
	parameter	(NMA$C_FOPDTL_SLF = 3)
	parameter	(NMA$C_FOPDTL_TLF = 4)
	parameter	(NMA$C_FOPDTL_SDF = 5)
	parameter	(NMA$C_NCEDTL_NNA = 0)
	parameter	(NMA$C_NCEDTL_INN = 1)
	parameter	(NMA$C_NCEDTL_UNA = 2)
	parameter	(NMA$C_NCEDTL_UNR = 3)
	parameter	(NMA$C_NCEDTL_RSC = 4)
	parameter	(NMA$C_NCEDTL_RJC = 5)
	parameter	(NMA$C_NCEDTL_ONA = 6)
	parameter	(NMA$C_NCEDTL_OBJ = 7)
	parameter	(NMA$C_NCEDTL_ACC = 8)
	parameter	(NMA$C_NCEDTL_BSY = 9)
	parameter	(NMA$C_NCEDTL_NRS = 10)
	parameter	(NMA$C_NCEDTL_NSD = 11)
	parameter	(NMA$C_NCEDTL_DIE = 12)
	parameter	(NMA$C_NCEDTL_DIS = 13)
	parameter	(NMA$C_NCEDTL_ABO = 14)
	parameter	(NMA$C_NCEDTL_ABM = 15)
	parameter	(NMA$C_OPEDTL_DCH = 0)
	parameter	(NMA$C_OPEDTL_TIM = 1)
	parameter	(NMA$C_OPEDTL_ORN = 2)
	parameter	(NMA$C_OPEDTL_ACT = 3)
	parameter	(NMA$C_OPEDTL_BAF = 4)
	parameter	(NMA$C_OPEDTL_RUN = 5)
	parameter	(NMA$C_OPEDTL_DSC = 6)
	parameter	(NMA$C_OPEDTL_FTL = 8)
	parameter	(NMA$C_OPEDTL_MNT = 11)
	parameter	(NMA$C_OPEDTL_LST = 12)
	parameter	(NMA$C_OPEDTL_THR = 13)
	parameter	(NMA$C_OPEDTL_TRB = 14)
	parameter	(NMA$C_OPEDTL_STA = 15)
	parameter	(NMA$V_CTLIN_TUN = 2)
	parameter	(NMA$V_CTLIN_RUN = 4)
	parameter	(NMA$V_CTLIN_FMR = 5)
