$ CXX/PREFIX=ALL/DEFINE:VMS CARD.CPP
$ CXX/PREFIX=ALL/DEFINE:VMS CARIBBEANSTUD.CPP
$ CXX/PREFIX=ALL/DEFINE:VMS DEALER.CPP
$ CXX/PREFIX=ALL/DEFINE:VMS DECK.CPP
$ CXX/PREFIX=ALL/DEFINE:VMS HANDS.CPP
$ CXX/PREFIX=ALL/DEFINE:VMS PLAYER.CPP
$ CXX/PREFIX=ALL/DEFINE:VMS SEAT.CPP
$ CXX/PREFIX=ALL/DEFINE:VMS TABLE.CPP
