#ifdef __STDC__
/* psf.c */
int main(int argc, char *argv[]);
void create_fork(void);
void write_accounting(long pages_printed, int log_exit);
void time_stamp(void);
void expire(char *s);
int getc_from_printer(void);
void abort_job(void);
void abort_exit(void);
void request_pagecount(int cancel);
long get_page_count(void);
void wait_for_eoj(int c);
measure *locate_pagetype(char *desired, int printerr);
double cvt_unit(char *which);
void scale_factors(void);
void prologue(void);
void set_tray(int set_paper_tray);
void set_bin(int set_paper_bin);
void showpage(int end_of_file);
void set_frame(void);
void set_y_coord(void);
void put_top(void);
void process_file(void);
int escape_sequence(int which);
void moveto(int x, int y, int do_move);
void findfont(void);
void start_file(void);
void terminate_printer(void);
void draw_cross(void);
void set_clip_path(int x1, int y1, int x2, int y2);
void output_book(char *bookfile);
char *nexttok(char *ss, char *q);
int tscan(char s[], char t[]);
void get_time(char *t);
int compare(char *a, char *b);
int partial_compare(char *a, char *b);
void trim(char *s);
void bad_file(void);
int xtoi(int c);
void catch(int signo);
void output_trouble(int rc);
void replacement_fonts(void);
int otoi(char *s);
void usage(void);
void size_display(void);
#else
/* psf.c */
int main();
void create_fork();
void write_accounting();
void time_stamp();
void expire();
int getc_from_printer();
void abort_job();
void abort_exit();
void request_pagecount();
long get_page_count();
void wait_for_eoj();
measure *locate_pagetype();
double cvt_unit();
void scale_factors();
void prologue();
void set_tray();
void set_bin();
void showpage();
void set_frame();
void set_y_coord();
void put_top();
void process_file();
int escape_sequence();
void moveto();
void findfont();
void start_file();
void terminate_printer();
void draw_cross();
void set_clip_path();
void output_book();
char *nexttok();
int tscan();
void get_time();
int compare();
int partial_compare();
void trim();
void bad_file();
int xtoi();
void catch();
void output_trouble();
void replacement_fonts();
int otoi();
void usage();
void size_display();
#endif
